### ISSUE TITLE
Draft integration revision must not appear in history

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1000]
![image](https://user-images.githubusercontent.com/99080/30687067-79496bc6-9eba-11e7-9257-da8048efe52f.png)

@gashcrumb we already discussed this in another issue (sorry, forgot the number), but actually when I decide to save as "Draft" after creating an integration there should be no history table (and it can't be duplicated anyway as it is already the 'draft').

Feel free to close this issue at will, i'm just in issue spam mode, opening everything I'm stumbling upon.

**Comment by gashcrumb** [comment]
@dongniwang Wonder, if there's no data for the history table should we just hide the whole row?

**Comment by dongniwang** [comment]
@gashcrumb 

Yes. I would suggest to hide the whole row. And display a message in the area, e.g. "No data available". 

![screen shot 2017-09-21 at 9 55 10 am](https://user-images.githubusercontent.com/24943812/30699523-fafef440-9eb2-11e7-8911-4814748f2d61.png)

**Comment by gashcrumb** [comment]
@dongniwang sounds good!

@rhuss it feels like the UI has to infer a lot with the information coming back, does it make sense to consider doing more of this filtering server-side in the future?  Otherwise we're transferring data that's going to get basically thrown away.

**Comment by gashcrumb** [comment]
@rhuss The revision values kinda don't make sense, I created an integration and clicked 'save as draft' and the revision is:

![capture](https://user-images.githubusercontent.com/351660/30703534-fb45fcae-9ebd-11e7-8ccb-05ea6d93664f.PNG)

Why would the `targetState` be `pending`?  Also, should I filter on `currentState` or `targetState`?

I wonder if maybe we shouldn't muck about with this too much until we revisit it post TP1 :-)

**Comment by gashcrumb** [comment]
Finally, I'm not sure I agree that non-published changes shouldn't be listed, it makes for a useful undo feature.

**Comment by rhuss** [comment]
@gashcrumb I completely agree that pending shouldn't be a target state (and its not a state at all after the new mode, but infered when current != desired).

As cool as an undo would be, having a history for non-published integrations (aka 'draft') makes the model more complex and we should the rethink the invariant _there can be at max 1 revision in draft state_ (which makes the state model much simpler). 

Also agree that the return value of the rest call should fitter the UI usage better.

Unfortunately I'm have not much time left for today (have to leave in an hour), maybe someone else can jump on this, too ? // @iocanel @jimmidyson think this is still somewhat critical to TP1.

**Comment by gashcrumb** [comment]
I think with the reworking of the details page this issue isn't applicable, especially given that we're hiding the history table at the moment.
