### ISSUE TITLE
Make "Syndesis" logo and HTML title configurable

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1005]
We need to be able to configure the Syndesis logo and the HTML <title> to be exchanged with the branded logo. Would be cool if we could fetch this from the configuration like config.json so that we can exchange it on runtime.

This is somewhat urgent we do need this for the release tomorrow :)

**Comment by gashcrumb** [comment]
this duplicates https://github.com/syndesisio/syndesis-ui/issues/927
