### ISSUE TITLE
Twitter Mention hops to 'Configure Action' screen, which is not required

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1010]
Just happened with the latest update:

![image](https://user-images.githubusercontent.com/99080/30705893-0cbc2c68-9ef7-11e7-8be1-44f2f79f869e.png)

**Comment by gashcrumb** [comment]
It always does, that's the page that fetches the form data.  That's definitely an old view though the 'Next >' button shouldn't be up at the top-right, I wonder if you're running against old code.

**Comment by rhuss** [comment]
Did a fresh update and it works. Strangely it worked before, too.

Found out that on my previous updates, the upstream rebase failed, again because of yarn.lock being different locally than comitted. As soon as I removed it, it worked nicely.

Sorry for the noise ....
