### ISSUE TITLE
Adding spacing (or padding) to Data Mapper UI 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ui#1023]
Not sure if I should file this issue in this repo. 

Looking at the data mapper on a laptop screen, and was wondering if it's possible to add some spacing so that the integration visualization and the source card can be visually separated. Same for the Mapping details pane. Can we make that less closer to the edge of the screen?  

![image](https://user-images.githubusercontent.com/24943812/30879983-1600fdcc-a2cf-11e7-9a56-407ddcee2493.png)

**Comment by astefanutti** [comment]
Should be fixed with f49b41ef411cdd0b98d00d018acce7f5bc14f25e.
