### ISSUE TITLE
Add "log out" option to user account dropdown 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ui#1035]
Right now, nothing is available if you click on user icon. Should add a way for users to log out. See screenshot below from [PatternFly](http://www.patternfly.org/pattern-library/application-framework/masthead/). 

![image](https://user-images.githubusercontent.com/24943812/30968765-5f7ab8a2-a42e-11e7-807e-e8b24775e78f.png)

**Comment by gashcrumb** [comment]
Outstanding questions on this:

1)  What backend endpoint do we need to hit to trigger a log out
2)  What page do we forward the user to after a successful logout

**Comment by dongniwang** [comment]
I have no idea what we need to do for question 1. But for 2, can we bring them to the marketing landing page for now?

**Comment by gashcrumb** [comment]
Just wanted to document a bit why there isn't currently a logout button :-)

So ideally I'd probably make the logout URL configurable via the template, that way it can be set depending on if it's an upstream vs product build.

@jimmidyson for logging out do we just need to clear our auth token or is there an endpoint the UI could request on to trigger a logout?  Is this something that might also need to be configured in the `config.json`?

**Comment by zregvart** [comment]
@gashcrumb AFAIK there is a [Keycloak logout URL](http://www.keycloak.org/docs/3.3/securing_apps/topics/oidc/java/logout.html) that we could use that would be:

`https://hostname/auth/realms/syndesis/protocol/openid-connect/logout`

But from what I hear we'll be removing Keycloak so we might need to create an API endpoint to do that. Which is weird as the backend is stateless so loosing the token would amount to the same.

**Comment by gashcrumb** [comment]
So then maybe for now we just clear the auth token and then forward the user on to whatever logout link we have configured...

i.e. -> https://github.com/syndesisio/syndesis-ui/blob/master/src/app/app.module.ts#L108
