### ISSUE TITLE
Settings page description text should reflect branding changes

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#1041]
- There is a description that should be updated according to branding
- the `Syndesis Help` link points nowhere.

`Register Syndesis with the applications you want to connect to in an integration. Find out more about this at Syndesis Help.`

![screen shot 2017-10-03 at 15 25 14](https://user-images.githubusercontent.com/5637792/31127428-35e6940a-a84f-11e7-9423-9544763cc4f2.png)

**Comment by dsimansk** [comment]
@gashcrumb could you possible squeeze it somewhere? :)

**Comment by gashcrumb** [comment]
@TovaCohen wonder, do you know what URL this particular help link should point to?

**Comment by dsimansk** [comment]
Should be `https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html-single/fuse_ignite_sample_integration_tutorial/` same as that top right menu.

**Comment by TovaCohen** [comment]
David is, of course, correct. That's where the tutorial will be available when we release TP1. For now, the full tutorial is available internally at a staged/preview URL.
