### ISSUE TITLE
Update Dockerfile for productised image

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1047]
@cunningt we updated the Dockerfile to add a symbolic link to the configuration in https://github.com/syndesisio/syndesis-ui/blob/27ad6ca0162fb0f17fbee72b8ade5659a3fddc54/docker/Dockerfile#L41-L42 

The reason is that we can't use subPath mounts anymore so wee need to mount a whole directory (into config that time). This directory does not exist for plain image but will be mounted during runtime.

Could you please adapt the product image to reflect this change ?

thanks ...

**Comment by cunningt** [comment]
Closing as out of date - this is a TP1 issue, and all that was needed here was a new product build.
