### ISSUE TITLE
Autocomplete field not sorted

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1054]
for the salesforce meta info of the objectname

![image](https://user-images.githubusercontent.com/99080/31278695-4892151c-aaa6-11e7-98f5-702ba17c119f.png)

**Comment by zregvart** [comment]
Should the backend do the sorting, in that case this belongs to the verifier. I think the order is the order in which the Salesforce gives these.

**Comment by akieling** [comment]
@zregvart if it's quick, I would sort in the backend but it can be done in the UI as well.... let me know...

**Comment by dongniwang** [comment]
Two options here:
- If this is how Salesforce gives the objects, does it mean users are more familiar with this order. If yes, i think we can keep it this way. 
- If no, can we just sort it in the backend? How long is a normal list?

**Comment by zregvart** [comment]
I think it would make the most sense to have it sorted, not sure that the while list of objects is ever presented to users in Salesforce. They usually have just a few tabs near the top of the screen customized to their role (or personalized by them). The list could contain hundreds (developer instance has about 300) objects.

**Comment by dongniwang** [comment]
Thanks @zregvart. In that case (~300 objects), then I would suggest to have it sorted in the dropdown menu.
