### ISSUE TITLE
Cannot edit an existing datamapping

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1055]
When trying to edit an existing datamapping from a saved integration I get:

![image](https://user-images.githubusercontent.com/99080/31282611-6319a988-aab3-11e7-96d5-5badaa753a00.png)

Target is salesforce.

![image](https://user-images.githubusercontent.com/99080/31282640-77074e82-aab3-11e7-99d9-05930044b3b4.png)

**Comment by zregvart** [comment]
This is what we discussed in #1034. We need to add call to fetch the input/output data shapes before we initialize datamapper.

**Comment by gashcrumb** [comment]
Should be fixed with that PR merged
