### ISSUE TITLE
There should be no "deploy" button when intgeration is active

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1056]
![image](https://user-images.githubusercontent.com/99080/31282778-de068ef4-aab3-11e7-923c-0427e2567bf4.png)

Instead there should be "Undeploy" and / or "Deactivate" ?

**Comment by dongniwang** [comment]
This is actually a confusing screenshot...How come the integration is in Draft state but with an active version?...

**Comment by gashcrumb** [comment]
Currently there's no qualifier on what buttons are shown in that history list as the whole thing feels a bit WIP and ill-defined to be honest.  Right now what `Deploy` actually does is update the integration with the steps defined in that revision, but it's probably not what we really want it to do, is it?

**Comment by dongniwang** [comment]
Yes. @sjcox-rh and I are working on making improvements to this integration details page. 

So maybe we can hide "deploy" for now if integration is active? And users can use "edit integration" to make updates...

cc: @sjcox-rh @amysueg

**Comment by gashcrumb** [comment]
@dongniwang we should maybe also figure out which term to use consistently, `publish` vs `deploy` vs `start` etc :-)
