### ISSUE TITLE
Two active integration in UI but only 1 running

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1057]
![image](https://user-images.githubusercontent.com/99080/31282904-3c8a3fca-aab4-11e7-804c-6a913cf9467b.png)

Path:

* Create integration
* Edit integration (adding filter step)
* "Save as Draft" 
* Then "Start integration" in details page

Actually the original integration in version 1 should be deactivated.

**Comment by dongniwang** [comment]
Yes. Related to https://github.com/syndesisio/syndesis-ui/issues/1056.

**Comment by gashcrumb** [comment]
Yeah, I think this is really a duplicate given the behavior.
