### ISSUE TITLE
Can't reuse integration name of an already deleted integration

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1062]
If using a name for an integration which has already deleted, this leads to:

![image](https://user-images.githubusercontent.com/99080/31295270-40285dae-aade-11e7-8415-f697b4b732d7.png)

Beside that this should be possible, the error message is bogus and does not show the real reason (see the console for the output)

**Comment by gashcrumb** [comment]
Yeah, we need to sort the name validation so it's server-side validated when it's changed in the text inputs, vs when you click save or publish or whatever we call it in the future.

**Comment by zregvart** [comment]
yup syndesisio/syndesis-rest#663

**Comment by akieling** [comment]
This is a sindesis-rest issue.

**Comment by rhuss** [comment]
Issue moved to [syndesisio/syndesis-rest #687](https://github.com/syndesisio/syndesis-rest/issues/687) via [**ZenHub**](https://www.zenhub.com/)
