### ISSUE TITLE
Provide a page for "About" or remove the menu entry

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#1069]
when clicking on about, nothing is happening
![image](https://user-images.githubusercontent.com/1105127/31430947-9e733cf2-ae72-11e7-8400-34545348e066.png)

**Comment by kahboom** [comment]
@sjcox-rh @dongniwang @kcbabo - Some questions:

1. Are we keeping this or removing it?
2. If keeping, do we have the content for this?
3. If keeping, will this be a page or modal?

**Comment by sjcox-rh** [comment]
Eventually we need one, it's just a matter of when we want to pull this feature in. @kcbabo 

When we implement it, it would be a modal from PatternFly.
http://www.patternfly.org/pattern-library/communication/about-modal/
@kahboom

**Comment by kcbabo** [comment]
Might be a handy place to put build/version information until we have a support page.

**Comment by kahboom** [comment]
Any other content? I can add in the modal, but it will be pretty bare in the meantime, so I wonder if we should be adding it at all. Up to you @kcbabo ! 👍

**Comment by gashcrumb** [comment]
Actually did have an issue for this already -> https://github.com/syndesisio/syndesis-ui/issues/844

was hoping we could show build info across all the components, not just the UI, but even that would be a start.  Problem is this info isn't baked into the distro when it's built I don't think.  So there's probably more work than just the modal.
