### ISSUE TITLE
Remove "My Account" submenu or provide a dummy page

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#1070]
when trying to click on Settings -> My Account , nothing is happening, it would  be better either to remove it or to provide even an almost empty page with very few non-editable details
![image](https://user-images.githubusercontent.com/1105127/31431058-ec466788-ae72-11e7-90f5-8389c60c6eb8.png)

**Comment by kahboom** [comment]
@sjcox-rh @dongniwang @kcbabo - Some questions:

1. Are we keeping this or removing it?
2. Do we have designs for it?

If we are keeping it, I'll need to get in touch with the API guys so see what we are missing for this and what type of actions we'd need once designs are in place, if they aren't already. Thanks! :)

**Comment by sjcox-rh** [comment]
@kahboom I think it would be best to remove the My Account page from settings and move that content under the username in the masthead on the right. We don't have a design for it yet, but in the Information Architecture we just put together, we discussed having two options that appear in the drop down when the user clicks on their username: Log Out and My Account.

@dongniwang @amysueg, let me know if you agree with this or not!

**Comment by gashcrumb** [comment]
There's no page there, that's just a placeholder link in the tab bar.

**Comment by kahboom** [comment]
@sjcox-rh - Since we don't have a page for it yet, it's not even in the settings really, and we don't have a design, I'll just remove the placeholder link for now. I was wondering if we had a design or something that I wasn't aware of and could proceed to implement.
