### ISSUE TITLE
Strange UI for new integration when no connection is available

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1071]
Just reported by Lars:

![bildschirmfoto von 2017-10-11 10-00-46](https://user-images.githubusercontent.com/99080/31431087-fbcc38e0-ae72-11e7-84c9-78097d5834b3.png)

IMO there should be only the lower 'create connection', or even having 'Create integration' disabled when there are no connections defined.

**Comment by gashcrumb** [comment]
Yeah, that's just a bug, that last 'tile' is shown unconditionally at the moment.
