### ISSUE TITLE
Use same terminology than twitter for the twitterOAuth Application management

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#1074]
in Syndesis Client ID and Client Sercret is used although on Twitter it it COnsumer ID and Consumer Secret

**Comment by gashcrumb** [comment]
This has been brought up before -> https://github.com/syndesisio/syndesis-ui/issues/1039

Probably should drive the form from the backend really.

**Comment by gashcrumb** [comment]
Let's track this in #1039
