### ISSUE TITLE
Use same terminology than twitter for the Salesforce OAuth Application management

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#1075]
it is client ID and CLient Secret in Syndesis, it is Consumer Key, Consumer Secret in Salesforce

![image](https://user-images.githubusercontent.com/1105127/31434106-b8b001dc-ae7b-11e7-9db0-b9d92834ff63.png)

**Comment by gashcrumb** [comment]
This has been brought up before -> https://github.com/syndesisio/syndesis-ui/issues/1039

Probably should drive the form from the backend really.

**Comment by gashcrumb** [comment]
Let's track this in #1039
