### ISSUE TITLE
On Edge, When typing "enter" while creating tag, the page is validated

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#1077]
When typing "enter" while creating tag, the page is validated instead of just adding the tag
![image](https://user-images.githubusercontent.com/1105127/31434266-2e574652-ae7c-11e7-844a-d9519fd6efc2.png)

**Comment by gashcrumb** [comment]
The tag input has key handlers for `,` and ` ` but we should probably also keep the one for `Enter` also

**Comment by akieling** [comment]
@apupier I couldn't reproduce the issue. What browser are you using? Can you test on another one to check if it's browser specific?

**Comment by apupier** [comment]
@akieling I reproduce only on Microsoft Edge
it is working fine on Chrome and Firefox
