### ISSUE TITLE
Left menu can overlap the content in some cases

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#1079]
I was trying to create an "integration", for the second step seems that there is an issue so i wanted to go back to Connections, i noticed that it is overlapped.
![image](https://user-images.githubusercontent.com/1105127/31437820-e29888f6-ae86-11e7-8904-ac2ad4d5a132.png)

**Comment by gashcrumb** [comment]
This is known but not yet resolved -> https://github.com/syndesisio/syndesis-ui/issues/850
