### ISSUE TITLE
Contextual Help & Tooltips

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#1087]
## Overview
Add tooltips, or contextual help, for users.

First pass-thru will just have manually added tooltips, but second pass-thru should use Maven plugin-generated JSON file provided by the API. The format of this file is not yet determined, but the content of the tooltips should ideally use existing documentation provided by the Docs team.

cc @lburgazzoli @rhuss 

## Reference
- Docs GH Issue: https://github.com/syndesisio/syndesis-documentation/issues/23 & https://github.com/syndesisio/syndesis-documentation/issues/20
- FTUE Designs & Text for Guided Tour & Tooltips: https://docs.google.com/presentation/d/1C7L0acXdA-kjNdl22Bh8HZnof6RaiFpmpugC4qOc72U/edit?ts=59bc3355#slide=id.g25316bef4b_0_42 (tooltips begin on slide 24)
- FTUE Journey Map: https://docs.google.com/presentation/d/15vxQIX9TCUXAS8-JLD2m_10TLd0sbFjIMZwW9p0zRww/edit#slide=id.p

**Comment by rhuss** [comment]
@kahboom actually the idea is not to serve the tooltips via the syndesis-rest API but already include it in the UI package. During the yarn build, the build should download the tooltip json from a fixed URL at GitHub and then use this. This file on Github is created by the maven-plugin and then committed. 

When we have switched to monorepo, this download from an URL can then be replaced by a relative file reference into the documentation directory then.

**Comment by kahboom** [comment]
@rhuss - Sorry if I was not clear; what you have described is how I understood it. I agree it will be easier once it's on a single repository. I should have said that the first pass-thru the tooltip _content_ is added in manually. For the second, more automated example that leverages the Maven plugin, I meant that the content is provided via the tooltip JSON, and that content is then used to populate the tooltips that are created in the UI.

**Comment by kahboom** [comment]
@dongniwang @gashcrumb - I've been looking through the tooltips here and don't see that we are still missing any: https://docs.google.com/presentation/d/1C7L0acXdA-kjNdl22Bh8HZnof6RaiFpmpugC4qOc72U/edit?ts=59bc3355#slide=id.g25316bef4b_0_42

Anything else I need to add / other tooltips?

**Comment by dongniwang** [comment]
I think we're good for now. We can see if users provide any feedback on needing more tooltips. Thank you!
