### ISSUE TITLE
Basic filter conditions aren't fully expanded

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#1100]
Probably due to page height, just a first 4 options are displayed.

FYI @lvydra 

![screen shot 2017-10-16 at 13 37 22](https://user-images.githubusercontent.com/5637792/31610126-397b56f0-b277-11e7-8f81-80b118d8e925.png)

**Comment by dsimansk** [comment]
@gashcrumb pls could you take a look? Probably related to PR https://github.com/syndesisio/syndesis-ui/pull/1094

**Comment by rhuss** [comment]
Is this quick to fix ? I ask because that labelled for TP2 but we want to get out TP2 asap.

**Comment by dsimansk** [comment]
Should be fixed in https://github.com/syndesisio/syndesis-ui/pull/1102. Needs a little review push I guess.

**Comment by kahboom** [comment]
Was waiting for a minor change, just went ahead and merged it in anyway so
as not to block.

Regards,

*Rachel Yordán*
Senior Software Engineer
Red Hat, Inc. | Middleware
ryordan@redhat.com
