### ISSUE TITLE
yarn warning on CI

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#1103]
When we move to yarn 1.2.1 (current latest) we'll see this on the CI

warning You are using Node "7.9.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"

We can probably move to node 8.x for the build, at least it's working for me here locally.

**Comment by gashcrumb** [comment]
Ah, this PR fixed this one too -> https://github.com/syndesisio/syndesis-ui/pull/1117/files

**Comment by jimmidyson** [comment]
That PR fixed things without me even knowing they were issues...
