### ISSUE TITLE
Cannot create a second integration

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1116]
When creating a second integration the following happens:

![image](https://user-images.githubusercontent.com/99080/31763484-b0b0e8f4-b4be-11e7-821f-609acbc77e86.png)

**Comment by rhuss** [comment]
This happens also when you delete an integration and try to create a new one.

**Comment by gashcrumb** [comment]
At what point exactly?  Like right when you click the 'Create Integration' button?

**Comment by gashcrumb** [comment]
So far I can't reproduce this.

**Comment by rhuss** [comment]
Just cant reproduce it either. Let me try it again later with the latest version ...

**Comment by gashcrumb** [comment]
Interesting, maybe just clear your cache before testing just to be on the safe side perhaps?

**Comment by gashcrumb** [comment]
I think this must have been a fluke, let's close this for now, can be re-opened if there's reproducible circumstances that show the problem consistently.
