### ISSUE TITLE
Dashboard looks inconsistent in TP2

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1123]
The vanilla dashboard in TP2 with one predefined connection looks like:

![image](https://user-images.githubusercontent.com/99080/31788308-a49de7c4-b50e-11e7-8043-a5c7dcec3e66.png)

This looks a bit random and asymmetric. The "Create" buttons are in no way aligned. Also, why is there a "Dashboard: " prefix for Connections and Integration in the main view. Looks redundant to me. "Integration" and "connections" alone would be enough.

As visual separator between those two sections might help to resolve the asymmetry, too. 

Just some random thoughts ... ;-)

**Comment by gashcrumb** [comment]
Yeah, empty state for integrations and then non-empty state for connections, definitely an odd mix :-)

**Comment by dongniwang** [comment]
I think it's OK that we have this layout for now. I believe normally, after creating connections, users would create integrations right away, so they would only see this screen for a short amount of time.

But I do agree we could make some visual improvements to this screen.

**Comment by gashcrumb** [comment]
Let's close this issue then so more focused issues on improvements can be created and tracked instead.
