### ISSUE TITLE
Disable "Duplicate" button in integration details

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1125]
Actually the duplicate button tries to create a second integration which overwrites the original one. Since there's a limit of 1 integration, pressing this button leads to a dead end.

Actually the whole revision handling is not worked out (history table currenlty only contains a single entry, this wont change until we fully implement the integration revision handling as planed, eg. in https://github.com/syndesisio/syndesis-rest/pull/493

For TP2 I highly recommend to remove this button.

**Comment by gashcrumb** [comment]
If we want it in I've created a PR for it...
