### ISSUE TITLE
Help setting up dev environment

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis-ui#1126]
Hi, I'm trying to setup a dev environment, but I'm facing some issue:

I have followed this steps:

```
# Configure the UI and Minishfit for dev mode.
./scripts/minishift-setup.sh

# install the dependencies
yarn

# start the server
yarn start:minishift
```

and despite `minishift-setup.sh` fetches the correct Minishift ip address and replaces it in `src/config.json` when I then start the dev server, I can see that the api call are still going towards `localhost:4200`:

```
Request URL:http://localhost:4200/api/v1/event/reservations
Request Method:POST
Status Code:404 Not Found
Remote Address:127.0.0.1:4200
```

What am I missing? Do I need to put a different url in the browser, other than http://localhost:4200 to connect to the remote minishift instance?

**Comment by gashcrumb** [comment]
Yeah, it's in the main README.md at the top, you want to use this URL:

`http://$(oc get routes syndesis --template "{{.spec.host}}")`

On linux you can use `xdg-open` on the CLI, mac use `open` and windows you can use `start`

**Comment by paoloantinori** [comment]
Ah, ok. Invoked that as well, but didn't work:

```
15:24 $ echo $(oc get routes syndesis --template "{{.spec.host}}")
Error from server (NotFound): routes.route.openshift.io "syndesis" not found
```

And indeed I have no route defined:

```
15:46 $ oc get routes
No resources found.
```

Despite this is not blocking me to use Syndesis locally.

Any idea what's going on here?

**Comment by paoloantinori** [comment]
Ah, wait. That commands was used just to pick the `nip.io` url right?

So if I have already  something like syndesis-ui-default.192.168.42.205.nip.io I'm good? Meaning that my local syndesis-ui dev is accessible from syndesis-ui-default.192.168.42.205.nip.io instead than from `localhost:4200` ? Do you confirm @gashcrumb  ?

**Comment by gashcrumb** [comment]
Correct, a quick test is to add some markup to say `app.component.html` and refresh.  Note that currently a manual refresh is required as the proxy doesn't support websockets yet.
