### ISSUE TITLE
Can not create a second integration

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1134]
* Create an intergration
* "Save as Draft"
* go to intergration list via the menu
* "Create Integration" button

--> 

![image](https://user-images.githubusercontent.com/99080/31990119-7680c5fe-b974-11e7-93a7-9fee88336cbc.png)

hope its reproducible, it doesn't always happen to me, but quite often.

**Comment by zregvart** [comment]
I managed to get this once, but since then not a single time out of about 20 tries.

**Comment by gashcrumb** [comment]
Figured out the right steps, you've gotta do it from the data mapper step, i.e. create the integration, add a data mapper, then go back to the list either by expanding the side-navigation or clicking on the `Integrations` breadcrumb then click on `Create`, 100% reproducible then.
