### ISSUE TITLE
Remove Integration history table for TP2

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#1137]
I suggest removing the whole table with the history entries for TP2.

Why ?

* "Duplicate" button doesn't work as expected
* Edit or Redeployment does not add lines to this list. There's always only a version 1
* It's not updated during a redeployment and always stays active.
* So, it's useless, only confuses people and raises questions.

We for sure need to revisit the whole status management which is half-baked at the moment. I would start from the backend to get the model straight and then we can talk about the UI (the otherwise round than usual because the state model is crucial for the overall logic).

// @kcbabo @gashcrumb @syndesisio/design-ux @chirino

**Comment by kcbabo** [comment]
Agree - if it's broken and doesn't provide any value in its current form, then it should be dropped.

We do need to track history/status as an independent deliverable though.  This will be required functionality for GA from my POV.

**Comment by gashcrumb** [comment]
+1

**Comment by dongniwang** [comment]
Agreed. And this is part of a bigger story - integration health, metrics and monitoring.
