### ISSUE TITLE
Tooltip is covered by the breadcrumb and action buttons

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ui#1141]
Can we display the tooltips right below the icons so it would not be covered by the top breadcrumb area? 

![image](https://user-images.githubusercontent.com/24943812/32020884-a694fd16-b99f-11e7-8b69-3c1f9f6c3954.png)

**Comment by gashcrumb** [comment]
We actually have an issue open for this -> https://github.com/syndesisio/syndesis-ui/issues/1027
