### ISSUE TITLE
Can we turn off auto assignment for pull requests?

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#1147]
I don't personally find it helpful and I think gives a false sense of responsiveness, when in fact there's no guarantee that the person assigned to review the PR actually has the time to do it.

I'd much rather just specifically mention someone in the PR if it's critical that the PR be reviewed/merged right away.  Or I can always just assign a reviewer when I create the PR.

Plus, the bot always seems to pick on poor @kahboom 

@jimmidyson @rhuss FYI

**Comment by dsimansk** [comment]
Afaik, the quick win [is hidden here](https://github.com/syndesisio/syndesis-ui/blob/master/.mention-bot#L12).

**Comment by gashcrumb** [comment]
@dsimansk OMG, thank you so much :-)  I'll just fix this myself then...
