### ISSUE TITLE
datamapper buttons are links

### ISSUE THREAD

**Issue by Stefan365** [syndesisio/syndesis-ui#1156]
Datamapper buttons "Add Source" and "Add Transaction" are not <button> but <a>

![datamapper_buttons](https://user-images.githubusercontent.com/2714974/32227122-b029ade0-be4a-11e7-9ed0-b3407a8b9ed9.png)

**Comment by gashcrumb** [comment]
+1, these should be `<button>` elements

**Comment by gashcrumb** [comment]
This issue was moved to atlasmap/atlasmap-ui#121
