### ISSUE TITLE
Shared Feature Module

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#116]
Create a Shared Feature module, as specified in the Angular 2 official style guide [here](https://angular.io/styleguide#04-10). We would be using this for things that are not singletons, and will be instantiated for each component that uses it, such as filter pipes. Possible challenges are getting it to work properly with AOT and lazy loading (and angular-cli), but may not run into any issues at all.

For non-singletons we will be using a Shared Feature Module (see #117).

**Comment by gashcrumb** [comment]
We have the `common` module, think this is all set.
