### ISSUE TITLE
Core Feature Module

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#117]
Create a Core Feature module, as specified in the Angular 2 official style guide [here](https://angular.io/styleguide#04-11). We would be using this for things that are singletons, and will _not_ be instantiated for each component that uses it, such as the navigation bar or footer. Possible challenges are getting it to work properly with AOT and lazy loading (and angular-cli), but may not run into any issues at all.

For non-singletons we will be using a Shared Feature Module (see #116).

**Comment by gashcrumb** [comment]
I think the common module is fine.
