### ISSUE TITLE
Filter actions based on EI_Pattern (to or from)

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/syndesis-ui#1180]
Actions can be a 'to' or a 'from'. 

- 'from' starts of an integration
- 'to' does not start but is at the end (or the middle) of an integration

**Comment by gashcrumb** [comment]
Is this not a duplicate of https://github.com/syndesisio/syndesis-ui/issues/1131?

**Comment by KurtStam** [comment]
it is.
