### ISSUE TITLE
Standardize the code linting flow for all contributors

### ISSUE THREAD

**Issue by deeleman** [syndesisio/syndesis-ui#1184]
With more developers coming on board we should strive to keep consistency in our code in regards of format, style and syntax. Applying a linting phase bound to the transpilation/versioning phases of development seems a good start.

The idea is to ensure that all developers get their code linted regardless the IDE in use and also get tips and hints on malformed code on dev-time. On a side note, a proper linting upon committing code will reduce the time required for peer-reviewing our code.

**Requirements**

- [x] Update lint config manifest with industry standard conventions for Angular/TypeScript projects whereas required
- [x] Ensure a linting pass is applied upon committing code to the forked repo
- [x] Update all install scripts necessary to make these rules available upon bootstrapping the frontend app
- [x] Refactor and format the code whereas necessary to fulfill the new linter rules.

**Comment by kahboom** [comment]
Yay!

**Comment by deeleman** [comment]
RE the requirement:

> Enable automated code linting regardless the IDE in use as a background process.

The idea was to hook up the linting process to the TS compiler daemon but this might be a bit overkill. The new ruleset will be pretty strict and might hinder debugging tasks requiring debugging tools such as `console.log` or `debugger`. Since a linting pass is conducted upon committing code, this step seems redundant to me. Those who require linting on dev-time will find better workarounds (such as plugins or IDE extensions) for this.

On a side note, the new linting ruleset yields literally hundreds of alerts on the current codebase so an additional to-do item has been added to this issue to address the necessary refactoring tasks.

**Comment by gashcrumb** [comment]
Wonder, there's a `yarn format` task that runs `prettier` against the codebase, maybe it'd make sense to get that working with the lint rules so that worst case folks can just run `yarn format` before committing?

**Comment by gashcrumb** [comment]
Also `yarn format` could help with those hundreds of lint warnings :-)

**Comment by deeleman** [comment]
The linting process goes beyond reformatting code: It catches bugs on an early stage and triggers code recommendations to embrace agreed conventions. Eg: placing class members in the correct location to ease finding stuff in the future, make sure no debugger calls are left in the code, detect unused class members, spot duplicated imports, etc.

Therefore prettier, [which only beautifies code](https://prettier.io/docs/en/comparison.html) according to certain predefined rules, falls short in that area. The case for sliding linters into our workflow is to make sure that our code not only does look the same, but also has the same structure so we can easily understand whatever code construct at a glance.

On a side note, or linter is now hooked up with Codelyzer at full, which means that our code will not only be linted, but also audited to make sure we conform to the Angular styleguide. 

> Also yarn format could help with those hundreds of lint warnings :-)

`$ yarn lint --fix` does exactly that, but I prefer to review all those alerts first, at least by now. Otherwise I will not know if our implementation does a good job on detecting malformed code. this also allows me to assess wether the chosen ruleset is either too strict or too naive.

;)

**Comment by deeleman** [comment]
Reviewing the ling errors by hand is also a good way to get acquainted in depth with the codebase and better understand its different entities. ;)

**Comment by gashcrumb** [comment]
> Reviewing the ling errors by hand is also a good way to get acquainted in depth with the codebase and better understand its different entities. ;)

Absolutely :-)
