### ISSUE TITLE
Add a way to remove rule from Basic Filter Step

### ISSUE THREAD

**Issue by tplevko** [syndesisio/syndesis-ui#1188]
There is no way to remove an existing filter step rule from Basic Filter. It causes problems when creating/editing the Basic filter step, one has the option to remove it, but I don't think this is a good way to edit the Basic filter step.
![basicfilterstep](https://user-images.githubusercontent.com/4180208/32538793-973d8a90-c467-11e7-8d50-9b251ffee9b9.png)

**Comment by dongniwang** [comment]
@gashcrumb @kahboom 

Is this a browser issue? I thought I see the trash can icon when i was trying the TP version. I was using chrome.

**Comment by dongniwang** [comment]
@gashcrumb @kahboom 

Is this a browser issue? I thought I see the trash can icon when i was trying the TP version. I was using chrome.

**Comment by dongniwang** [comment]
@gashcrumb @kahboom 

Is this a browser issue? I thought I see the trash can icon when i was trying the TP version. I was using chrome.

**Comment by gashcrumb** [comment]
Lemme look now, it's there in the template but that doesn't mean it's getting rendered properly :-)

**Comment by gashcrumb** [comment]
This actually appears to be due to changes in `ng-dynamic-forms` and how it references the template for array items.
