### ISSUE TITLE
Dashboard: integration count seems to be too low

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#1192]
There's something weird about the number floating so close to chars :)

![screen shot 2017-11-08 at 15 16 21](https://user-images.githubusercontent.com/5637792/32553698-e32c744a-c497-11e7-9a61-2980c4f51b8d.png)

**Comment by gashcrumb** [comment]
Yep, we actually have this one already, just haven't gotten to it yet -> https://github.com/syndesisio/syndesis-ui/issues/1135
