### ISSUE TITLE
Autosuggestion field offset in Basic Filter

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis-ui#1197]
_From @rhuss on August 23, 2017 14:27_

The basic filter has a strange offest in the autosuggestion field sometimes:

![image](https://user-images.githubusercontent.com/99080/29620865-727482c4-881f-11e7-8681-c46dd269713c.png)

Interestingly this happens for me when my browser in the first (horizontal) half of the screen only. When I move the browser to the right so its in the second half, everything is aligned. Maybe also worth to mention that I have a three monitor setup where the browser is on the middle screen.

really strange.

Heres the screen shot with the browser on the right side:

![image](https://user-images.githubusercontent.com/99080/29621009-d66a3f94-881f-11e7-8f14-3d3d2ae8b51f.png)

_Copied from original issue: atlasmap/atlasmap-runtime#157_

**Comment by gashcrumb** [comment]
We actually have this issue reported already -> https://github.com/syndesisio/syndesis-ui/issues/999
