### ISSUE TITLE
Demo Component for UI Widgets & Charts

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#127]
A demo area and component for viewing and manually testing reusable UI widgets and charts.

**Comment by gashcrumb** [comment]
Do we still need this?  Doesn't seem like it...

**Comment by kahboom** [comment]
Still think this could be useful. For instance, when a reusable UI widget is not complete (e.g. guided tour, toast notifications), or if we want a reference to all of them, like a type of documentation of how to use them in practice complete with a demo/tests--similarly to what PF has here: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/ --then it could be very useful.

**Comment by gashcrumb** [comment]
I'd say most likely if we produce widgets we should probably just contribute them straight to patternfly-ng and consume them that way.
