### ISSUE TITLE
Documentation for UI

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#131]
Automatically generated documentation could be very useful for encouraging contribution, as we are using many third party dependencies, and many developers are new to Angular 2 on its own. For instance, we are using Angular CLI, and just going through its dependencies, as well as how Webpack works, etc. To facilitate this, it makes sense to have some type of technical overview along with automatically generated documentation.

**Comment by kahboom** [comment]
Will be using [Compodoc](https://github.com/compodoc/compodoc). I'll try to get around to that this week.

**Comment by gashcrumb** [comment]
I think we can take off the low priority label, I think this is higher priority as we get new eyes on the code.

**Comment by kahboom** [comment]
Thanks @gashcrumb - didn't even realize I had that label on there haha.
