### ISSUE TITLE
Integrate ngIdle

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#182]
After a few minutes of inactivity you can no longer navigate through the application as refresh token requests are halted. At that point the user has to refresh the page in order to then be able to navigate where they'd like. Integrating ngIdle can resolve this, though for now we can have a workaround like in [this PR](https://github.com/redhat-ipaas/ipaas-ui/pull/181).

**Comment by jimmidyson** [comment]
Is this still a problem?

**Comment by kahboom** [comment]
Nope, thanks.
