### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#184]
Support mobile devices like tablets, smartphones, etc. There are many approaches and corresponding libraries/solutions out there for mobile compatibility. 

## Responsive UI
- [Bootstrap](http://getbootstrap.com) out of the box helps with this using their grid layout (`col-xs` versus `col-lg` for screen sizes, for instance).
- The official Angular team recommends using Progressive Web Apps exemplified through their [Mobile Toolkit](https://mobile.angular.io/), which leverages Angular CLI.
- Not sure if something like [Framework7](https://github.com/nolimits4web/framework7/) is an option as well for responsive. Looks like the jQuery could be problematic with Angular, so I'd have to do more research.

## Native Apps
Another question is whether or not down the line we want to use something like [Ionic](https://github.com/driftyco/ionic) or [Titanium](https://github.com/appcelerator/titanium_mobile) to port the application over as a native iOS and/or Android app? I've heard very positive things about Ionic. This may be thinking too far ahead, but may be worth researching depending on how users will be using iPaaS.

Another good resource that could be of relevance is [Modernizer](https://github.com/Modernizr/Modernizr).

**Comment by gashcrumb** [comment]
Let's just hide this until we have a business requirement for it (and designs)
