### ISSUE TITLE
UI component dependency alignment

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#188]
We need a method of aligning dependencies across components, first for datamapper-ui and ipaas-ui, eventually there could be other components.

From https://github.com/redhat-ipaas/ipaas-rest/issues/123

**Comment by gashcrumb** [comment]
According to [this](https://github.com/npm/npm/issues/8112), either we manually sync `package.json` files via some tooling, or use a 'master' package with all the shared dependencies I guess.

**Comment by gashcrumb** [comment]
@mattrpav CC

**Comment by mattrpav** [comment]
Is there an update or an ETA at this point?

**Comment by gashcrumb** [comment]
For now we'll manually sync dependencies, should be fine.
