### ISSUE TITLE
Add redirect to login page when token times out

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#217]
Currently only a 401 happens for an Ajax request and the UI doesn't change.

**Comment by kahboom** [comment]
Possibly relates to #182 .

**Comment by kahboom** [comment]
Speaking w/ the UXD team & @gashcrumb - we will probably need a design for a login page or some type of similar notification to the user to let them know that their session has timed out.

**Comment by astefanutti** [comment]
An option would be to pop an error notification toast with an appropriate message and a link to reload the page / to the login page. That may be more informative than a console log and less disruptive than an automated redirect.

**Comment by gashcrumb** [comment]
@astefanutti +1 this is exactly what the openshift console does and I think that works nicely.

**Comment by astefanutti** [comment]
@gashcrumb great! Let me do that, that'll be better than the current console log and we can still further improve it if needed.
