### ISSUE TITLE
Create help icon in UI with link to iPaaS product documentation

### ISSUE THREAD

**Issue by fbolton** [syndesisio/syndesis-ui#243]
This is a suggestion that comes from Nacia Owens, as low-cost way of integrating the iPaaS docs (created by the Fuse documentation team) with the UI:

> here's an idea that might be quick to implement: can you include a simple, clickable help icon (?) in the banner that would take the user to the iPaaS document on the portal? If Fintan provides the URL for the page where the iPaaS doc will be published, it might be possible to implement this link as a first step towards providing help in the UI?

**Comment by naciao** [comment]
Revising the timeline for this item: the documentation target for the linked help icon will be delivered for the technology preview, not for the demo.

**Comment by naciao** [comment]
Suggest that we promote this up and out of the backlog, perhaps re-evaluate what kind of embedded help would be most useful to the citizen integrator, and plan to provide some help in the UI for the technology preview.

**Comment by dongniwang** [comment]
@gashcrumb @kahboom Any objections of me moving this to the ux repo? If possible, let's target this for sprint 16? 

cc: @sjcox-rh

**Comment by gashcrumb** [comment]
+1 go for it!

**Comment by dongniwang** [comment]
Issue moved to [syndesisio/syndesis-ux #31](https://github.com/syndesisio/syndesis-ux/issues/31) via [**ZenHub**](https://www.zenhub.com/)
