### ISSUE TITLE
Integration List - Responsive state needs refining

### ISSUE THREAD

**Issue by sjcox-rh** [syndesisio/syndesis-ui#249]
As I made the window size smaller, realized that the list view on the integration list page is not truly responsive. All the icons on the left shifted when they should remain unchanged. We could provide guidance if needed!

<img width="732" alt="screen shot 2017-03-13 at 12 18 45 pm" src="https://cloud.githubusercontent.com/assets/16257540/23872234/b500aefc-07ea-11e7-96f4-925d82045970.png">

**Comment by kahboom** [comment]
@sjcox-rh Should icons disappear completely when the window is resized or should they just decrease in size, or perhaps show another icon altogether?

**Comment by sjcox-rh** [comment]
@kahboom I would say the icons would decrease in size instead of disappear. If any of the items have to disappear I would recommend the descriptive text could go away when necessary. @dongniwang What do you think?

**Comment by dongniwang** [comment]
I agreed with @sjcox-rh, icons would decrease. Also, we probably want to define a minimum size for the icons.

**Comment by gashcrumb** [comment]
So for now, let's focus on optimizing for 1280x720

**Comment by kahboom** [comment]
Sounds good!

**Comment by akieling** [comment]
The issue with the icons on the left doesn't seem to be happening anymore.

**Comment by astefanutti** [comment]
I've done some improvements while working on #647 (using patternfly-ng). It may not be perfect but should be better at least, like keeping the icons on a single line, and be consistent with what Patternfly provides.

**Comment by gashcrumb** [comment]
Wonder then, can this issue be closed?

**Comment by gashcrumb** [comment]
Yes it can.
