### ISSUE TITLE
Create Integration - Back button behaves incorrectly

### ISSUE THREAD

**Issue by sjcox-rh** [syndesisio/syndesis-ui#251]
Once you finish setting up the start connection and begin setting up the finish connection, the back button doesn't work correctly. Ideally it would take the user back to the last substep of the Start connection. Currently it takes the user to the integration list page and they lose the whole integration and have to start over.

<img width="1024" alt="screen shot 2017-03-13 at 12 21 09 pm" src="https://cloud.githubusercontent.com/assets/16257540/23872401/5f1e743c-07eb-11e7-8031-8a6039280f07.png">

**Comment by gashcrumb** [comment]
Makes sense.  I'll try and pass along state that the back button can use to figure out the previous page, with a fallback to going to the previous step in the flow should we not have that state, we'll see how that works out :-)

**Comment by akieling** [comment]
@sjcox-rh The back button has been removed.

**Comment by sjcox-rh** [comment]
Thanks @akieling! There is another story to focus on buttons so good to remove the "back" button for now.
