### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#255]
## Overview
Create the landing page that users see before they are logged in. Entails the following:
- Add HTML & SCSS to reflect designs. Minimal logic should be required.

### Relevant Designs

![ipaas_landingpage](https://cloud.githubusercontent.com/assets/3844502/24212802/e9c92362-0f06-11e7-860c-6ed8f1bb657a.png)

## Reference
- [JIRA: UI](https://issues.jboss.org/browse/IPAAS-252)
- [JIRA: User Story](https://issues.jboss.org/browse/IPAAS-232)

**Comment by gashcrumb** [comment]
Is this relevant still?

**Comment by kahboom** [comment]
I believe it is, for the marketing page, but we can close it since I believe a member from the redhat.com team is working on this per @dongniwang .

**Comment by dongniwang** [comment]
> I believe it is, for the marketing page, but we can close it since I believe a member from the redhat.com team is working on this per @dongniwang .

cc: @kcbabo @catrobson

**Comment by kcbabo** [comment]
Yeah, this is for redhat.com page, so no impact on syndesis-ui.  Might make sense to track this via syndesis-project instead of syndesis-ui.
