### ISSUE TITLE
Integration Editor - Dashboard link in breadcrumb and 'cancel' button inconsistent

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#293]
So in the integration editor we've the `dashboard` link in the breadcrumb.  This takes you back to the `Dashboard` page.

Then there's the `Cancel` button, which takes you back to the integration list.  

The behavior is inconsistent.  Since we've the breadcrumb link, do we really need the cancel button?

**Comment by gashcrumb** [comment]
@sjcox-rh @dongniwang FYI had raised this issue about the cancel button...

**Comment by dongniwang** [comment]
I think this is fixed now since we added another layer to the breadcrumb. 

![image](https://user-images.githubusercontent.com/24943812/29142970-8f3cd6d0-7d21-11e7-9a35-5e974dc623eb.png)

And just noticed now it says "Home" instead of "Dashboard" ...

**Comment by akieling** [comment]
@sjcox-rh @dongniwang @gashcrumb 
Is this issue still relevant? What needs to be done?

**Comment by gashcrumb** [comment]
Yeah, I think this isn't relevant now.
