### ISSUE TITLE
Integration Status

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#303]
## Overview
Add the ability to view integration statuses on the Integration List, and Integration Detail pages. Entails the following:
- Add HTML & SCSS to reflect designs & incorporate logic.
- Add appropriate method(s) to components that fetch status of integrations (e.g. Dashboard), or simply display this data, if a call is already made for integrations (e.g. on the Integration List & Detail Pages).

## Relevant Designs

**Integration List**

![integration list](https://cloud.githubusercontent.com/assets/3844502/24758546/b78281b8-1ab0-11e7-86fb-736b535ea9e7.jpg)

![integration list 02](https://cloud.githubusercontent.com/assets/3844502/24758551/b968134e-1ab0-11e7-9740-8d2759ab3173.jpg)

## Reference
- N/A

**Comment by gashcrumb** [comment]
I think this is in place now, not sure this issue is needed, if there's remaining tasks then more specific issues should be opened.
