### ISSUE TITLE
Fix Disabled State for Steps

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#305]
Currently looks like this: #notgood

<img width="1440" alt="screenshot 2017-03-22 16 02 11" src="https://cloud.githubusercontent.com/assets/3844502/24218316/2e76d452-0f19-11e7-9b2a-2c8c8c232ddf.png">

Should look like this:

![add step - first step - 03](https://cloud.githubusercontent.com/assets/3844502/24225759/9d8ebdd6-0f38-11e7-8c76-8d6ce48dda5f.jpg)

**Comment by kahboom** [comment]
Icon state classes not currently working properly.

**Comment by gashcrumb** [comment]
This probably has an impact on this issue -> https://github.com/redhat-ipaas/ipaas-ui/issues/337

**Comment by kahboom** [comment]
@gashcrumb - There shouldn't be an icon in the center at all, so it's just a matter of determining when it should be inactive or incomplete and then updating the added classes so that it's gray instead of blue.

**Comment by gashcrumb** [comment]
Yep, that should be in place, i.e. if `stepKind` and `configuredProperties` on the step are set then it should be blue, otherwise gray, unless the user is looking at that step.

**Comment by gashcrumb** [comment]
oh poo, or at least I thought I had those in place, but now it doesn't look right :-(

**Comment by akieling** [comment]
Is this issue still relevant?

**Comment by gashcrumb** [comment]
Nope...
