### ISSUE TITLE
Add back button to Create integration -> Add details about this integration

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-ui#327]
User can open "Add details about this integration" page anytime by clicking on top left "Edit integration name".
At this point, "way back" can be confusing. 
Cancel destroys his work on integration and other way back like clicking on some part of left "flow panel" 
isn't very obvious.
 
![integration-back](https://cloud.githubusercontent.com/assets/8707241/24396746/9135be70-13a4-11e7-83fe-1cb1cf24fa9e.png)

**Comment by gashcrumb** [comment]
yeah, so you'd click 'next' but the buttons and locations generally need work -> https://github.com/redhat-ipaas/ipaas-ui/issues/310

**Comment by akieling** [comment]
@jludvice This page doesn't exist anymore, right? Can we close this issue?

**Comment by jludvice** [comment]
Hi @akieling, I'd like to take a look but our openshift syndesis-qe instance doesn't work since yesterday.
It keeps returning http 503 on all rest requests...

**Comment by jludvice** [comment]
At least syndesis-staging is working today.
You're right @akieling. Closing issue.
