### ISSUE TITLE
Ability to Duplicate Connections

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#341]
## Overview
Add the ability to duplicate connections in the UI. Entails the following:
- Add HTML & SCSS to reflect designs & incorporate logic.
- Add method(s) called by HTML for toast notifications and actually duplicating the connections in its respective component.
- Add logic to communicate with API to duplicate connection.
- Add toast notifications for action update.

### Relevant Designs

![187999839](https://cloud.githubusercontent.com/assets/3844502/24465921/ed216580-147c-11e7-91c3-91e18effc292.png)

## Reference
- [InVision: Connection Library](https://redhat.invisionapp.com/share/VQ8UZ7PCE#/187999839_Connection_Library)

**Comment by kahboom** [comment]
@sjcox-rh @dongniwang - Are we still wanting to allow users to do this?

**Comment by dongniwang** [comment]
I would say no for now

**Comment by akieling** [comment]
@dongniwang if we are not going to implement this task, shall we delete it?

**Comment by dongniwang** [comment]
We can always close this issue, if this comes up in the future, we can reopen this one or just create a new issues and reference this one. Thanks!

**Comment by akieling** [comment]
@kahboom do you mind if I close this issue? In the future, we then create a new one of reopen this one?

**Comment by kahboom** [comment]
Sure, was thinking along the same lines. Thanks @dongniwang @akieling !
