### ISSUE TITLE
update ng2-bootstrap to v1.6.0

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#349]
As there's some breaking changes since v1.3.3, so the online docs/examples don't match up with our version.

**Comment by gashcrumb** [comment]
It's also been renamed to ngx-bootstrap

**Comment by jimmidyson** [comment]
Yeah same with ngx-restangular btw

**Comment by gashcrumb** [comment]
@jimmidyson ah, thanks for the heads up, that needs to get bumped up too

**Comment by jimmidyson** [comment]
Fixed by #544
