### ISSUE TITLE
Create connection, then view connection fails to show config values

### ISSUE THREAD

**Issue by kcbabo** [syndesisio/syndesis-ui#364]
If I create a connection and then pull up the connection details view, I don't see any config.  I do, however, see configuration for the default connections (presumably because these are pre-baked into the DAO JSON).

**Comment by kahboom** [comment]
Yeah I'm pretty sure this should be visible to the user, but we don't have designs for the detail view. Should we have one? Looping in @dongniwang and @sjcox-rh . Per @sjcox-rh : 

> Ah yes, there isn’t technically a design for it but im assuming it will be very similar to the overview page for a connection. We can definitely create a design for that!

**Comment by kcbabo** [comment]
Just to make sure we're talking about the same thing - this page already exists in the UI.  If you go to Connections and click on a specific connection then it's the resulting page.  I'm just saying that it's not showing any data for connections that I've created.

**Comment by kahboom** [comment]
Yep that's the one! Would be good to have a design to avoid any confusion, even though it will look a lot like the third step when creating a connection (would that suffice?). The configuration should be shown in the detail view as well; if it's not, we need to add it. That page hasn't been touched in a while so I wouldn't be surprised.

**Comment by gashcrumb** [comment]
Which connection is it?  I notice that we're getting HTTP 500 on at least a couple connections.

**Comment by gashcrumb** [comment]
So think this is actually due to a backend error, we need to generally improve how errors like this would be reported to the user other than dumping it to the console log :-)

**Comment by kahboom** [comment]
@gashcrumb - We have an issue open for that #307 (unless you think it's a slightly different issue?).

**Comment by kahboom** [comment]
We can use [PatternFly alerts](http://www.patternfly.org/pattern-library/communication/inline-notifications/) (also known as inline notifications) for this.

**Comment by akieling** [comment]
@kcbabo Is this issue still valid? I can see the connection fields.

**Comment by kcbabo** [comment]
Haven't tried this recently and my minishift install is hosed right now, so if it works for you that's good enough for me. :-)
