### ISSUE TITLE
fix template for generating cucumber.js steps

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-ui#374]
Low priority - just to improve template for generating new cucumber steps.

I opened issue upstream https://github.com/timjroberts/cucumber-js-tsflow/issues/24. Hopefully there will be some answer.
As an alternative we might consider adding https://github.com/johngrimsey/cucumber-snippets-tsflow.

One can specify something in `*.feature` and cucumber will throw following complain into log:
```
     Undefined. Implement with the following snippet:

       @given(/^clean application state$/)                                                                                                                          
       public GivenXXX (callback): void {                                                                                                                           
         // Write code here that turns the phrase above into concrete actions                                                                                       
         callback.pending();                                                                                                                                        
       } 
```
But `callback.pending()` throws runtime error. `cucumber(null, 'pending')` seems to work for us

**Comment by gashcrumb** [comment]
Since the e2e tests got moved off to another repo I guess this isn't applicable
