### ISSUE TITLE
Integration Lists: Delete action scope

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#379]
What should be the scope of delete action performed from UI?
- When we create integration, GitHub repository is initialized for the source code
  - Should we delete the source code? 

- When we create integration, OpenShift resources are generated like DeploymentConfig,   BuildConfig, Service, etc.
  - Should we delete all OpenShift resources?

- Should we have `delete all resources` or `cascade delete` among the actions? 
- Confirm action with tick box to indicate `delete all`? 

@kahboom do we have particular design proposals that include delete actions?
 
[JIRA Issue for Keynote](https://issues.jboss.org/browse/IPAAS-297)

**Comment by kahboom** [comment]
Thanks @dsimansk - I have the same question, also for deleting Connections, such as what kind of implications they should have on existing Integrations that use them. Pinging @jimmidyson to get clarification on this.

As for the `delete all` I'll loop in @sjcox-rh and @dongniwang but I don't think multi-select deleting is a requirement or feature we've discussed. cc @kcbabo as well since we can never get too much clarification this close to summit. ;D

**Comment by kahboom** [comment]
Relates to #189 #192

**Comment by kcbabo** [comment]
I believe we agreed previously that users should not be allowed to delete connections that are in use by integrations.

**Comment by jimmidyson** [comment]
As @kcbabo said, we should not allow delete of connections that are in use.

Deleting integrations should delete all resources, other than source repo,

**Comment by kahboom** [comment]
Thanks for the clarification @kcbabo @jimmidyson .

**Comment by kahboom** [comment]
Do we care about multi-select for deletion?

**Comment by dsimansk** [comment]
I'd like to bump up this thread and spark the discussion once again. There'll be probably some backend issue needed also. This issue seems like a serious requirement for TP1 to enable user to properly clean up used resources on OSO.

Current status:
- only Integration entry is delete from our DB
- OpenShift resources are untouched && GitHub repository is kept

IMHO, deployment resources should be cleaned by default in backend, probably needs to handle properly. On top of that we should decide if source repo removal should be also included, something like checkbox to delete GitHub repository would probably work fine.

Cc @rhuss

**Comment by kcbabo** [comment]
I agree that the resource cleanup needs to happen for TP1.  Including @jimmidyson.

GH cleanup is probably a longer discussion and something we can push if it's too expensive to implement in Sprint 17.  It did get me thinking though - what happens with the current impl when a repository already exists in the user's GH account with a given integration name?

**Comment by jimmidyson** [comment]
Yeah totally agree. Will discuss at planning this afternoon.

**Comment by gashcrumb** [comment]
I think we've figured out what deleting means :-)
