### ISSUE TITLE
Create Integration: Confirm Delete Step Modal Styling

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#392]
Just looks a bit ugly, needs to be improved. Low priority.

<img width="1438" alt="screenshot 2017-04-05 12 08 34" src="https://cloud.githubusercontent.com/assets/3844502/24715238/b78304ac-19f8-11e7-9668-c32a3b454e4d.png">

**Comment by gashcrumb** [comment]
Is this still relevant with all the modal-related refactoring I wonder?

**Comment by akieling** [comment]
This issue is fixed.
