### ISSUE TITLE
Metrics Support

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#394]
## Overview
Add the ability to view metrics in the UI. Entails the following:
- ~~Add HTML & SCSS to reflect designs & incorporate logic.~~ On hold until designs provided, if necessary.
- ~~Add method(s) called by HTML for methods in its new respective component.~~ On hold until implemented in the API.
- Do we need the ability to save/export metrics? Possibly down the line? cc @kcbabo 

### Relevant Designs
N/A

## Reference
- InVision: Design: N/A
- [JIRA Issue: UI](https://issues.jboss.org/browse/IPAAS-300)

**Comment by gashcrumb** [comment]
Let's close this in favor of an upcoming product-wide story.
