### ISSUE TITLE
Multiselect for Integration List

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#424]
## Overview
Add the ability to select multiple integrations in the UI. Entails the following:
- Add HTML & SCSS to reflect designs of multiselect & incorporate logic.
- Add method(s) called by HTML for toast notifications, opening modals, and actions being taken on bulk items.
- Add logic to communicate with API.
- Add modal to confirm action with user.
- Add toast notifications for any respective action update.

What actions should be available for multiselect?

### Relevant Designs
N/A

## Reference
- InVision: Design: N/A
- JIRA Issue: UI: N/A

**Comment by gashcrumb** [comment]
The list widget supports it but the design doesn't seem to, until it does let's just brush this under the rug.
