### ISSUE TITLE
Properly Capture Nested Events in Angular 2

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#454]
## What
At the moment, we are avoiding nested click events due to it's tricky nature and our time constraints. At some point, however, we need to handle nested events in Angular 2 properly.

## Why
Lists of Connections (as cards) or Integrations (as rows) should allow the user to click anywhere on the card or row to get to its respective detail or edit page.

Most pages that use a list of Connections (as cards) or Integrations (as rows) also have a kabob within each respective card or row, which, when clicked, open up a dropdown menu with potential third level events (clickable links).

## When
At the moment, the click action, regardless of where it happens in the card/row, bubbles all the way up to the parent "click anywhere" event. Therefore, users wouldn't be able to click on the kabob without it redirecting you to the detail/edit page. In other words, the nested event isn't being captured.

## Temporary Workaround
As a result, we've had to separate the two primary events (there isn't any apparent issue with the kabob and dropdown as this is a self-contained component): the click action of the containing card/row and the click action of the kabob to initiate a dropdown menu. As a result, we have events all over the cards and rows that will lead you to the respective detail/edit pages (such as one on the name, another one the description), etc. with CSS padding in order to give the illusion that the entire card and row is clickable. That way, we can keep the kabob event separated, and not nested.

## Next Steps
This isn't really sustainable long-term and can build up technical debt. Ideally, we would have a two events, one nested for the kabob, and the parent event that makes the entire card/row clickable. There are ways to handle this properly, which we need to investigate further.

## Reference
- [SO Related Issue](http://stackoverflow.com/questions/15390393/two-nested-click-events-with-angularjs)

cc @gashcrumb

**Comment by gashcrumb** [comment]
I feel like this is a non-issue at this point?
