### ISSUE TITLE
Ability to Filter Connections by Connector

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#456]
Users may want to look for all Connections that use Twitter (for example), especially if they have several (Twitter Mention, Twitter Hashtag, Twitter Message, etc). Most of the time, each service or connector will have several Connections. Let's assume we have 5 for each connector type/service, and 5 Connections using each, using several combinations of those could accumulate lots of data that could be difficult to filter through.

This is also important because even if they did a search, there is no guarantee that they are using the word 'twitter' in the name of the Connection.

## However
Considering that Expert Users will be creating these, it won't be common for them to name it something that doesn't include the name of the connector or service, so this is more of an issue with Integrations. However, we aren't displaying the connector name anywhere in the Connection List (which is fine and makes sense), but we should at least display it in the Connection Detail page.

**Comment by kcbabo** [comment]
Agree.  I thought we would auto-label connections with the connector type.  If we have the ability to search by label, then users could find connections by connector type of any other type of label they applied.

**Comment by kahboom** [comment]
That's a really good point @kcbabo . I didn't know we'd be auto-labeling connections with the connector type, but that can definitely be done rather easily.

**Comment by gashcrumb** [comment]
This feels like it'd be a quick win for TP1
