### ISSUE TITLE
Manage Tags

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#459]
**NOTE**: Low priority atm.

Add the ability to manage tags from a user's perspective. This means we would need a separate design and page that would enable users to view a list of existing tags, be able to edit them, delete them, possibly create new ones, click on one to list anything with that tag (too much? may not be useful?), etc.

cc @kcbabo @sjcox-rh @dongniwang @jimmidyson

**Comment by kahboom** [comment]
@gashcrumb - Never gonna happen because we don't want it to be a part of the UI or because of a timing thing? If the former, then all tag-related things should be closed permanently, I'd guess.

**Comment by dongniwang** [comment]
Can we close all tag related issues for now? We do have **Label** in the roadmap, maybe we can reference the tag stories when we work on the label story? 

@kahboom @gashcrumb

**Comment by kahboom** [comment]
I'll close them for now @dongniwang , we can reference these later on. Thanks!
