### ISSUE TITLE
Create Integrations: Ability to Add Tags

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#460]
## Overview
Add the ability to add Tags in the UI when creating Integrations. At the moment, users should only be able to add Tags, not edit or delete them. They should be able to use more than one tag. This will be possible when they are creating Integrations (and Templates in the future, when we support them). This task entails the following:
- ~Add HTML & SCSS to reflect designs & incorporate logic.~
- Add `TagComponent` if it doesn't exist already; wire up to proper endpoint(s).
- Add method(s) called by HTML for creating Tags in respective component.

## Reference
- [GH: UI: Integrations: Display & Filter by Tags](https://github.com/redhat-ipaas/ipaas-ui/issues/461)
- [GH: REST: Support for Tags](https://github.com/redhat-ipaas/ipaas-rest/issues/305)

**Comment by akieling** [comment]
@kahboom I can work on this one if it's still required. Are there any mockups?

**Comment by kahboom** [comment]
Likely some really old ones, let me dig them up, just a sec.

**Comment by kahboom** [comment]
We have tags for Integrations that are created from Templates (we never built that in) cc @dongniwang @sjcox-rh @rhuss  - Are Templates still going to be a requirement? And should users be able to create/assign tags to Integrations created from Scratch?

From template:
![from template](https://user-images.githubusercontent.com/3844502/29666917-46e198c8-88d2-11e7-8d3a-fcdc7558d3a8.png)

From scratch:
![from scratch](https://user-images.githubusercontent.com/3844502/29666973-79be895e-88d2-11e7-84bd-bceefda4072a.png)

**Comment by kahboom** [comment]
They don't even appear in the Integration List anymore, because of some requirements we had that required some changes. The original Dashboard also featured Popular Templates with tags:

![dashboard v7-update](https://user-images.githubusercontent.com/3844502/29667066-e6c3ad36-88d2-11e7-8f89-52dff28119aa.png)

**Comment by sjcox-rh** [comment]
I think we removed tags completely for the time being until we brought templates back into the product, @kahboom 

Is this now a requirement for TP1? 

@kcbabo

**Comment by kcbabo** [comment]
Agree that we aren't focused on tags for now.  Tags are separable from templates though - I think connectors, connections, integrations, and templates (when they appear) should be tag-enabled.

**Comment by gashcrumb** [comment]
All we really need at this point is to add an editable field to the detail page that displays the tags like on the connection detail page, #904 adds connector IDs as tags to the integration when the user saves the integration.
