### ISSUE TITLE
Integrations: Display & Filter by Tags

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#461]
Display associated Tags for an Integration, and add the ability to filter by them (if we have the time).

## Reference
- [GH: UI: Create Integrations: Ability to Add Tags](https://github.com/redhat-ipaas/ipaas-ui/issues/460)
- [GH: REST: Support for Tags](https://github.com/redhat-ipaas/ipaas-rest/issues/305)

**Comment by gashcrumb** [comment]
Is there backend support for this, i.e. do integration have a 'tags' field, if not we need to raise a relevant issue for the API.

**Comment by zregvart** [comment]
@gashcrumb yup, Connections and Integrations have tags, as do configuredProperties of Connectors and Action.definition.

**Comment by gashcrumb** [comment]
As it turns out the patternfly toolbar already handles filtering by tags, so I think this is all set.
