### ISSUE TITLE
Make breadcrumb/button area background white in editor pages

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#509]
Follow on from https://github.com/redhat-ipaas/datamapper-ui/issues/64 the breadcrumb area toolbar should be white.

**Comment by kahboom** [comment]
Is this just for the data mapper or for all editor pages?

**Comment by akieling** [comment]
Are you sure? It might not look very good.

**Comment by gashcrumb** [comment]
Yeah, this was opened based on feedback from awhile back when we got the data mapper integrated, think the design had a white breadcrumb background, but none of the other pages do.  So maybe this one isn't really applicable now.

**Comment by sjcox-rh** [comment]
@gashcrumb you're right, this no longer applies. It can be closed, thanks!
