### ISSUE TITLE
Integrations: Add Connector Names as Tags Automatically

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#517]
## Overview
We should add the Connector names from each Connection used in an Integration automatically as Tags. Relates to #457, the ability to filter Integrations by Connections (or Connector names). This can either by done in the UI or API, but for now I'm creating this here so I don't forget. :joy:

## Reference
- [GitHub: Ability to Filter Integrations by Connection](#457)

**Comment by gashcrumb** [comment]
Do integrations have a tag field?  Should probably raise relevant issues for the backend to get that added so this could be impmlemented...

**Comment by zregvart** [comment]
@gashcrumb yup they do
