### ISSUE TITLE
Integration List: Status Labels Don't Look Actionable

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#518]
## Overview
In the Integration List, we display the `currentStatus` as a PatternFly label. Naturally, they look like labels and not like actionable elements, like a button. However, we also do not want to add just a button as that is usually used for a single type of action. Changing the status will be possible through the dropdown kebab on the right, but ideally we'd want a single-step action to open up the modal that confirms the user's request to change the status of the Integration. We need to research different design ideas for this and decide on the best possible way to display this.

We can discuss this in this week's UXD meeting or post-Summit. :)

### Relevant Designs

<img width="1440" alt="screenshot 2017-04-24 14 22 56" src="https://cloud.githubusercontent.com/assets/3844502/25353231/8afd21ca-28fc-11e7-8319-7b42e7ad50b8.png">

cc @jimmidyson @gashcrumb @sjcox-rh @dongniwang

**Comment by astefanutti** [comment]
It may be closed given #837.

**Comment by astefanutti** [comment]
#837 has been fixed so this issue becomes irrelevant.
