### ISSUE TITLE
Dashboard: not showing 'In Progress' status

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#531]
`Facebook Photo to Twitter` is `In Progress` status but the label is empty, see the screenshot.

![image](https://cloud.githubusercontent.com/assets/5637792/25520934/1db175e4-2bfe-11e7-9ec9-bbf65c61b984.png)

**Comment by rhuss** [comment]
for my test yesterday, it seems also that on the integration list on the left side, the "Pening" state is not properly reflected (at least it was different as in the integration list page).

**Comment by gashcrumb** [comment]
@rhuss currently the dashboard doesn't show status, only if there's an error or not.
