### ISSUE TITLE
Integration List & Dashboard: Adjust Width of Labels

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#535]
Make them all the width of the widest label (I think this was the 'Delete' label), but not as wide as the 'In Progress' text (not really a label).

### Integration List

<img width="1439" alt="screenshot 2017-04-28 11 31 54" src="https://cloud.githubusercontent.com/assets/3844502/25535782/4d831ff4-2c06-11e7-9171-c5dd52469844.png">

### Dashboard

<img width="1440" alt="screenshot 2017-04-28 11 33 03" src="https://cloud.githubusercontent.com/assets/3844502/25535844/7dcabdc0-2c06-11e7-926d-436f40563064.png">

**Comment by gashcrumb** [comment]
I feel like the lack of response on this means it's a no :-)

**Comment by kahboom** [comment]
Sure
