### ISSUE TITLE
Setup/Settings Page

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-ui#546]
Right now we have a bit of a mess with where projects get save in github.  It get saved under the last user that published the integration.  If 2 different users save the integration, then it will be save in two different git repos.  I think all integrations should get saved under the same github organization regardless of the user. 

We should have a setup or settings page where users configure:
1. The github organization that integration projects get created under
2. The OpenShift namespace that the project get deployed into

At this point we might want to trigger oauth flows to collect offline tokens which the system then uses when working with github/openshift.

**Comment by gashcrumb** [comment]
+1 at the very least the current behavior is undesirable.  Wonder though, this would generally be more of an administrative thing, is more of a background configuration item or does it need each user to set it up, or should we cater for both?

Also does it make sense to allow for overrides on a per-integration basis?  In which case then we might need a settings page for an integration as well possibly?

**Comment by gashcrumb** [comment]
Also, wonder if we want to also be able to work against non-github repositories how would this work?

**Comment by chirino** [comment]
Another thing that we might want to configure in this settings page is oauth client secrets for connectors like Twitter and Salesforce.

**Comment by gashcrumb** [comment]
Seems like that should be a separate thing stored with a connection?  Otherwise this settings page will have a potentially a lot of oauth settings as we add connectors, wouldn't it?

**Comment by chirino** [comment]
This is true.  But I think it's the right area to do it.  Another point to make is we should NOT show connectors to users if the system level oauth setting are configured for it.

**Comment by gashcrumb** [comment]
So thinking about this more we mostly need a page that lists oauth2 endpoints that lets you create a new entry for that list, each entry could then be an open-ended map of key/value pairs basically.  Then it's a matter of mapping these list entries to a connector during the create connection wizard.

**Comment by gashcrumb** [comment]
Ideally we'd want to be able to discover what oauth2 endpoints could potentially need configuring, and then an endpoint to load/save/manage these settings.

**Comment by gashcrumb** [comment]
Also if we know required settings for a given oauth2 endpoint we can then create a form, otherwise fall back on a more generic 'add key/value pairs' interface.

**Comment by gashcrumb** [comment]
> Another point to make is we should NOT show connectors to users if the system level oauth setting are configured for it.

Like the settings?  Or the connection?  I'm not sure I understand.

**Comment by chirino** [comment]
So when we create a new connect we get to pick from a list of connectors.  We should not show connectors that we don't have configured client id/secrets for since we would not be able to do a proper oauth flow for them.

**Comment by gashcrumb** [comment]
That'd be doable, we'd need to have a way of identifying if a connector needs oauth or not and then a way to correlate a connector to it's available setting.  But yeah, that totally makes sense to me.

Kinda starting to wonder if we should have a separate 'Authorizations' nav item?  As really, a user that's starting off with a new install would have to start there, wouldn't they?

**Comment by chirino** [comment]
I think settings nav item makes more sense to me with perhaps a Authorizations tab.  But whatevs.

**Comment by gashcrumb** [comment]
Yeah, agreed.  Though it's like, if you don't have any oauth settings set up, you can't connect anything except http.  So we have to guide the user to get that set up first really.  Could maybe punt 'em over to the oauth settings page I guess, or maybe in-place add the oauth setting from within the create connection wizard, and then we'd continue to show all connectors. on the first page of the wizard.

**Comment by chirino** [comment]
Yeah initial setup flow is an interesting UXD exercise on how to collect all that data keeping in mind that the user needs to go out to Twitter and Salesforce to go create those client id/secrets so it might take a while to get it all setup and we might have to guide then on how to use those external systems.

**Comment by gashcrumb** [comment]
@sjcox-rh @dongniwang thoughts on this one?

**Comment by sjcox-rh** [comment]
Would it be possible to have the user go through the oauth flow within the create a connection flow? As in, when a user creates a Twitter connection for the first time, they would have to go through the oauth flow then (whether via a popup, external page, etc.) and once it's successfully connected to their Twitter account, they can finish setting up the connection. 

Or are we saying all connections that require an oauth flow would be done via a settings page?

**Comment by gashcrumb** [comment]
I think the idea is that the user would go through the oauth flow on the create connection page, but to do that in most cases you need to have a client ID and app token with the target site to start that flow.  So the settings page would be where a system administrator would set up those client IDs/secrets ahead of time so that we don't need to require that stuff in the create connection form.

**Comment by sjcox-rh** [comment]
Got it, thanks for clarifying @gashcrumb!

**Comment by kahboom** [comment]
I think that's why it kind of makes sense to have a separate "Accounts"
section for this type of thing like Zapier does (it's almost like they
don't have a Connections model).

Regards,

*Rachel Yordán*
Senior Software Engineer
Red Hat, Inc. | Middleware
ryordan@redhat.com

**Comment by rhuss** [comment]
Can we please revisit the story here and widen the scope a bit beyond ?

As briefly described in https://github.com/syndesisio/syndesis-project/issues/13 there are several _global configuration options_ which needs to be configured in a separated section in the UI.

This section holds all configuration which are global and independent of concrete connections. The discussion about which configuration should go there initially should go to https://github.com/syndesisio/syndesis-project/issues/13.

wrt the UI I think we should start first to think about from where to branch off this UI section. I suggest adding this to the leftmost column as an extra point. The content of the section obviously dependent on the possible configuration options, but it can already be said that there will be a configuration section per connector (twitter, salesforce, ...) which is used during the creation of a connection. The OAuth dance itself, however, would happen during the creation of the connection. But @chirino said the client id and other global app secrets should go there.

**Comment by kahboom** [comment]
Do we need designs here @sjcox-rh @dongniwang ? @rhuss I'm assuming this isn't a priority for this sprint since the epic isn't assigned to one.

**Comment by rhuss** [comment]
@gashcrumb as we now have merged the PR #629 , can we close this issue ? Or is there still UI work to be done here ?

**Comment by gashcrumb** [comment]
@rhuss no, there's still work to complete this to do

**Comment by gashcrumb** [comment]
@rhuss so on this one I still have to get the form in the expansion part of the list and wire up the buttons, as well as then wire up the view to the backend.  I'll maybe try and remember to include what's remaining on future PRs if that helps.

**Comment by rhuss** [comment]
That's fine for me. If there is something I can test early, let me know.

**Comment by jludvice** [comment]
Hi @gashcrumb, 
would it be possible to use angular components instead of `<div><div><div><div><div>` element tree ?
It is really painful to write readable css selectors, especially if I have to some 3rd level nested element which contains string XY in body.

Wouldn't be components be better also from reusability point of view?
![settings.png](https://images.zenhubusercontent.com/5939117e51aa2c305780da73/0a7d47ba-f4d4-46ad-9f3e-d1fca5f9034b)

It would be awesome if I can type selector like this:
```ts
$('oauth-entry[name="Facebook"]')
```

**Comment by gashcrumb** [comment]
@jludvice I can work towards that, for sure.

**Comment by gashcrumb** [comment]
@jludvice one thing though, am using patternfly-ng + a patternfly list for this view now which does impose some restrictions as to the hierarchy of elements, otherwise the styles don't apply correctly.  For example I gave it a go with the main content area in each list item and it breaks the formatting.  But we could certainly go through and add specific classes/IDs to whatever elements you need, just let me know which ones...

**Comment by jludvice** [comment]
Just created issue #663 to discuss css selectors and IDs in for E2E in general.

@gashcrumb the `Register` button behavior seems suspicious.
It's visible when the entry is collapsed  - `Salesforce` entry in screenshot
but it's hidden when entry is expanded - `Twitter` entry in screenshot

![settings-forms.png](https://images.zenhubusercontent.com/5939117e51aa2c305780da73/09680183-12af-4e13-91b4-da28e3b20f83)

Shouldn't it be visible allways?

**Comment by gashcrumb** [comment]
@jludvice it's like that in the design -> https://github.com/syndesisio/syndesis-ux/blob/master/designs/global-settings-page/global_settings_page_overview.md

And really, once the form is open, the 'Register' button doesn't need to be there, does it?

I did find the 'Remove' button odd in general when implementing, also I kept the form after the user enters in the credentials and saves it rather than writing up another view without the form, but this is in a state where it's ready for use.
