### ISSUE TITLE
Integrations List: Kebab menu is displayed empty for Deleted state integration

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#549]
Picture worth a 1000 words :) There're no actions listed for `Deleted` state integration.

![screen shot 2017-05-18 at 13 43 00](https://cloud.githubusercontent.com/assets/5637792/26200742/ef43c6da-3bcf-11e7-8e02-35f4aea5a1ae.png)

**Comment by gashcrumb** [comment]
Probably shouldn't show a menu at all if there's no actions for a given state.  Not sure if 'deleted' as a state will be there going forward.

**Comment by dsimansk** [comment]
You wouldn't guess that I've had a delicious Kebab for lunch today (for real :)). Thanks for quick fixes 👍

**Comment by kahboom** [comment]
lol

**Comment by dsimansk** [comment]
Verified commit b20d068 implements correct behaviour for `Deleted` state.
