### ISSUE TITLE
Connections List: Kebab menu isn't displayed, but navigates directly to details

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#550]
After clicking on Kebab menu on any listed Connections, the Kebab menu is not displayed. But the page navigates directly to Connection detail page.

**Comment by dsimansk** [comment]
Verified commit 09150e0. Kebab menu is diplayed properly with action `{Delete, View}`. 

@gashcrumb one other thought came to my mind. Wouldn't it be better to have `{Delete, View, Edit}` in the menu?

**Comment by gashcrumb** [comment]
Yeah, 'editing' was hacked in quickly though and I think might take a bit of work to support linking to it directly.  Can you raise a new issue for adding 'Edit' into that menu so we can close this one?

**Comment by dsimansk** [comment]
Closing this one and opened https://github.com/syndesisio/syndesis-ui/issues/613 for edit action tracking.
