### ISSUE TITLE
DataMapper UI stuck if there is problem in metadata

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-ui#562]
I'm unable to load data mapper ui on syndesis-qe instance.

Steps to reproduce:
* create integration
* from twitter / mention
* to salesforce / upsert
* add data mapper step

![screenshot_20170529_171253](https://cloud.githubusercontent.com/assets/8707241/26554821/76f8b804-4492-11e7-8cbb-a303aadd4c85.png)

I see only this log entry in data mapper pod:
```
2017-05-29 15:12:07.650  WARN 1 --- [ XNIO-3 task-32] c.m.a.j.i.v2.ClassInspectionService      : VarArg, Bridge, Synthetic or Default method compareTo detected
```

**Comment by jludvice** [comment]
So far I found one difference - when setting up salesforce / upsert on ipaas-staging, I have to fill also this form
![screenshot_20170529_171927](https://cloud.githubusercontent.com/assets/8707241/26554938/25f568d4-4493-11e7-9e29-eeb4140a5425.png)
which is not present in syndesis-qe 
CC @dsimansk

**Comment by jludvice** [comment]
Hi @gashcrumb, do you have idea what might go wrong?

**Comment by gashcrumb** [comment]
Not entirely sure, kinda seems like a class not found error possibly?  If you look in the network tab and look at the actual response back from the mapping backend that usually provides a little more information.

**Comment by jludvice** [comment]
Ok, next try, I tried to use one existing integration and after clicking on "Data Mapper" step there was no request sent to backend, just this error in browser console:
```
vendor.1ccaf9c….bundle.js:148 ERROR TypeError: Cannot read property 'kind' of undefined
    at l.createDocumentDefinition (0.ed8ca6e….chunk.js:1)
    at l.initialize (0.ed8ca6e….chunk.js:1)
    at 0.ed8ca6e….chunk.js:1
    at t.invokeTask (polyfills.7396005….bundle.js:36)
    at Object.onInvokeTask (vendor.1ccaf9c….bundle.js:316)
    at t.invokeTask (polyfills.7396005….bundle.js:36)
    at n.runTask (polyfills.7396005….bundle.js:36)
    at invoke (polyfills.7396005….bundle.js:36)
    at e (polyfills.7396005….bundle.js:15)
﻿```

**Comment by jludvice** [comment]
Another try, create new integration from `twitter/mention` to `salesforce/upsert` and add datamapper step

Related http requests (in order of appearence):

request https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/api/v1/integration-support/generate/pom.xml
response [pom.xml.txt](https://github.com/syndesisio/syndesis-ui/files/1041333/pom.xml.txt)


request https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/v2/atlas/java/mavenclasspath
response
```json
{
    "MavenClasspathResponse": {
        "classpath": "",
        "executionTime": 0,
        "jsonType": "com.mediadriver.atlas.java.v2.MavenClasspathResponse"
    }
}
```

request https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/v2/atlas/java/class
response: [class-1.txt](https://github.com/syndesisio/syndesis-ui/files/1041329/class-1.txt)

request: https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/v2/atlas/java/class
response: [class-2.txt](https://github.com/syndesisio/syndesis-ui/files/1041332/class-2.txt)


One more thing - while I'm watching the `Loading source/target documents.` spinner,
my chrome constantly consumes more and more RAM and ~6% CPU time.
It seems like there is some never-ending computation going on.

**Comment by gashcrumb** [comment]
I suspect the second response is probably what causes the data mapper UI component to not load, in general I think it's a condition that's not catered for very well yet.

**Comment by jludvice** [comment]
this issue is still present on syndesis-qe instance

**Comment by jludvice** [comment]
@gashcrumb datamapper ui started to load when I updated "ipaas snapshot" with more recent content 
![snapshot](https://user-images.githubusercontent.com/8707241/27529545-3f8f7ea6-5a55-11e7-8146-91b7bd5c864d.png)

but I still consider this an issue -> datamapper should report "I can't load because component XY has broken metadata..." not hang on rotating spinner

**Comment by gashcrumb** [comment]
@jbakermd wonder, I think you've improved the error handling lately in the data mapper component for this kind of behavior, am I right there?

**Comment by jbakermd** [comment]
Error handling is improved in the latest version that'll be integrated soon (#602). When I was working on the integration I saw a similar example of the data mapper load screen hanging forever. After integrating the latest version these errors were shown on the screen with enough detail for the user to discern the problem..

The error I encountered was irrelevant to this discussion probably. It was an error that one of our test classes (salesforce contact) did not exist - which was caused by my local version of the services not having that particular test class from the summit demo in our classpath.

**Comment by jbakermd** [comment]
Note that @jludvice's earlier comment about this error in the console:

`
vendor.1ccaf9c….bundle.js:148 ERROR TypeError: Cannot read property 'kind' of undefined
    at l.createDocumentDefinition (0.ed8ca6e….chunk.js:1)
    at l.initialize (0.ed8ca6e….chunk.js:1)
`

That's most likely this line here: 

https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/edit-page/step-configure/data-mapper-host.component.ts#L112

`switch (dataShape.kind) {`

The type of dataShape in this instance is DataShape, which appears to be used within syndesis to pass source/target metadata to the data mapper's initialization routine. 

Sounds like in that specific run, the source/target metadata was null. 

Perhaps this will help with that particular error seen a few months back.

**Comment by gashcrumb** [comment]
Good point.  Not sure which existing integration that was, but some of the ones in the database are stale and may not have all of the correct attributes.  Definitely needs to be an error that's handled properly by the controller I have there that initializes the data mapper.

**Comment by jludvice** [comment]
Do we plan to fix this issue any time soon ? 
Screen recording of timer >> http integration where datamapper freezes on loading spinner

https://youtu.be/PgT-LNSe9ek

**Comment by gashcrumb** [comment]
Yeah, neither timer or http even have types to map, so the plan is not to show the data mapper if it's not applicable to the integration.

**Comment by gashcrumb** [comment]
This relates to https://github.com/syndesisio/syndesis-ux/issues/25 BTW
