### ISSUE TITLE
Clarify and expand text in the UI so the citizen integrator needs minimal additional doc

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis-ui#568]
I went through the iPaaS UI and wrote suggestions for clarifying and expanding the text and thus making it easier for citizen integrators to do their thing. My suggestions are here:

 https://url.corp.redhat.com/ipaas-ui-audit 

This is a google document and I think I have shared it with all interested parties.

**Comment by gashcrumb** [comment]
I think this document really needs to branch out into multiple individual issues, i.e. I'd consider this issue to be an epic, @jimmidyson WDYT?

**Comment by dongniwang** [comment]
I think we can probably start taking a look at the suggestions in sprint 16 and make updates as needed along with https://github.com/syndesisio/syndesis-ux/issues/31.

cc: @sjcox-rh

**Comment by gashcrumb** [comment]
Yeah, I meant to recommend maybe that we get this kind of feedback right at the design phase for starters, as that's what I'm going by when implementing a page, plus I imagine if we have the correct text when designing a page it'd be helpful as well.

**Comment by TovaCohen** [comment]
I expect that many of the suggestions I made at the beginning of June no longer apply. 
Can this be in Sprint 16 with the goal of re-doing the audit as soon as I return from PTO - August 21? And then reviewing the audit and implementing changes based on the review?
I agree that getting the text right in the design phase is the best approach. Starting August 21, I will do my best to comment during the design phase.

**Comment by gashcrumb** [comment]
Cleaning up, think this is out of date.
