### ISSUE TITLE
Implement Filter Step UI

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#569]
Implement UI for the "Filter Step"

Filter user story: https://issues.jboss.org/browse/IPAAS-320
Initial Design: https://redhat.invisionapp.com/share/KNBZYX1W3

### Feedback

* @kcbabo 

> I really like the layout of the filter step.  Probably need to brainstorm a bit with engineering on the best type of control to use for "Object Name".  I think a default of message body makes sense.  I could also see a case for what Stan mentioned, where the user starts typing in a field name and it auto-completes.  This could also be a message header or (less likely) an exchange property, so we'll need to have some concept of what namespace the user is operating in.
> 
> I like the dropdown control for operators used with the expressions.  This feels like a really good basic expression builder for filters.  I like the idea of a separate tab here for the "Custom Editor" case which allows the user to just go crazy with the expression language of their choice.

* @rhuss

> * I would maybe add some sort of "Object Type" (header, property, body) before the "Object Name" and name "Object Name" depending on the chosen type. E.g. when "Header" is selected a type the second drop box should container all possible Header keys. Either with a textfield with autocompletion on possible values or a dropdown.
> 
> * For the value field I wouldn't model them like tags since tags are for grouping stuff (e.g. when multiple objects carry the same tag), but here it is more about individual values unique for a filter statement which will not be reused across filters. Also, only a single value makes sense for this field, so a plain textfield is sufficient imo. The tag like UI could make sense for defining the filter keys, though. (e.g as an alternative for the combo box approach header or property key)
> 
> * I would not add an "and" / "or" selection at the line level, because then we have to deal with precedence at this level when more than two such rows are added. For a first shot I would always assume a logical "AND". If we want to support logical "OR", too, then we have two options:
> 
>   - Add an extra level in the filter definition, which means you have a "Filter Step" which contains one or more "Filter Rules" which are combined with logical "OR". Each filter rule would consist of "Filter Statements" (these are the current lines in the UX design) which are combined with logical "AND". In the UX I could imagine to have a "Add Filter Rule" button for defining the "Rule" (maybe in a modal dialog ?), and then a list of those "Filter Rules" (with edit and delete action on each rule line). Classical example for managing a list of elements.
>   - Alternatively if the whole flow would allow for parallel steps (i.e. a 'fork'), one could put two filter steps in parallel to realize a logical OR (where in each filter step all statements are combined with AND). I.e. the "OR" logical would happen outside the filter step (whereas in the former suggestion it would be included in the filter step).

**Comment by rhuss** [comment]
Some additional  UI related ideas has been added to the design proposal in [syndesis-project](https://github.com/rhuss/syndesis-project/blob/a65fcb8ac566f073ac496c36e69dc713544ca37d/design-proposals/002-filter-data.md#ui)

**Comment by kahboom** [comment]
Closing and opening more specific issues related to the basic filter.
