### ISSUE TITLE
Connection drop-down truncated by containing element

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#574]
Might just need to configure the dropdown to attach to the body instead.

![screencapture-localhost-4200-connections-1496756513715](https://cloud.githubusercontent.com/assets/351660/26832123/6b5cfdba-4a9c-11e7-9207-b1e899020e12.png)

**Comment by jimmidyson** [comment]
Why is the dropdown so wide anyway?
