### ISSUE TITLE
Can't delete 'In Progress' integration

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-ui#578]
When Syndesis first boots up there is an integration that is 'In Progress'.  Since it's misconfigured, it's deployment would never complete.  How can I delete it?  The kabob menu does not show the delete option.

**Comment by gashcrumb** [comment]
Maybe it's worth having a flag for the rest API for making those pretend integrations show up or not.

Should 'in-progress' integrations be delete-able?  What would that mean for the backend etc?

**Comment by chirino** [comment]
The backend needs to be able to property delete an integration regardless what the current deployment state of the integration is.  We can't garantee that a user does not create a similar integration (one that stays 'In Progress').  So I think the delete button should always be shown.  The deactivate button should also be shown if a User does not want to delete the integration but stop the system from trying to bring it online since it's not going to work.

**Comment by jludvice** [comment]
You can delete the integration from dashboard / top 5 integrations if you're lucky enough @chirino  ;)
https://github.com/syndesisio/syndesis-ui/issues/579

**Comment by rhuss** [comment]
Also related to https://github.com/syndesisio/syndesis-project/issues/22
