### ISSUE TITLE
No focus on textfield when stylus is pushed

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#580]
When the stylus in the integration name field is pushed then the text fields appears on the _right_ panel (I'd expected it to be left from the stylus), which was confusing.

![screen shot 2017-06-26 at 12 53 35](https://user-images.githubusercontent.com/99080/27536219-8640de76-5a6e-11e7-8bfd-650d0e50e81b.png)

![screen shot 2017-06-26 at 12 53 43](https://user-images.githubusercontent.com/99080/27536227-904bc62e-5a6e-11e7-90d3-15356c6172a7.png)

But then there is also no focus in the text field so one needs an extra click in the field to start with.

Also, there is no way to continue with adding connections and other steps. The only options are the buttons in the top "Cancel" "Save as Draft" and "Publish" which all will get you away from the integration form.

**Comment by rhuss** [comment]
Also: The "Publish" button is only on the integration edit page. If you merely edit the name and then add connection, you don't see any publish button until you go back to the "Edit name" page by chosing the stylus. 

I think we should seriously reconsider the flow for creating / editing intergation wrt UX. I.e. I think a publish button should be always present but greyed out when not possible.

**Comment by astefanutti** [comment]
Related to #661.

**Comment by rhuss** [comment]
Knew that I already moaned about it ;-P

**Comment by astefanutti** [comment]
😄 I agree it feels counter intuitive. Let's wait a bit for UXD feedback and see what we can do about it.

**Comment by gashcrumb** [comment]
This stuff should be sorted actually...
