### ISSUE TITLE
Connection verification sends empty fields as string

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#583]
E.g. when validating a Salesforce connection which uses a _Refresh Token_ but no user / password combination, then user and password are not existent in the keys. When now validating an existing connection which was created for a refreshToken, then the UI posts a user and password with an empty string leading to an error (since it is validated that either refresh token or user/password is send but not both). 

The UI must not post back empty strings when the values were empty before.

**Comment by zregvart** [comment]
Or we can make the verification code in Camel Salesforce component a bit smarter about empty strings and consider them null?

**Comment by rhuss** [comment]
Yes, probaly empty user and passwords are not allowed anyway. But still, I think its more of a general problem to send originally non existing values back as empty strings.
