### ISSUE TITLE
When creating connection only part of field help messages are visible

### ISSUE THREAD

**Issue by jknetl** [syndesisio/syndesis-ui#585]
When creating connection, the help message for each field is shown directly in the field, which helps a lot. However when the description (the help message) of the field is long, only first part is displayed and _there is no way how to display next part_.

For example, when creating new salesforce connection you will see something like this:

![salesforce-connection](https://user-images.githubusercontent.com/5871202/27675856-dfef797a-5cab-11e7-82b7-2b9526d49c89.png)

For example, when I am not sure what should I fill for refresh token I see only part of message:

> Refresh token already obtained in the refresh token OAuth flow. One needs to setup a web application and co

But whole message is:

> Refresh token already obtained in the refresh token OAuth flow. One needs to setup a web application and configure a callback URL to receive the refresh token or configure using the builtin callback at https://login.salesforce.com/services/oauth2/success or https://test.salesforce.com/services/oauth2/success and then retrive the refresh_token from the URL at the end of the flow. Note that in development organizations Salesforce allows hosting the callback web application at localhost.

Since there is no tooltip nor animation of the text which would display the other parts. There is no way how to display whole help message.

**Comment by gashcrumb** [comment]
Yeah, that's way too much info to use as placeholder text, definitely a `?` with a tooltip would be a better solution at least at first.

**Comment by gashcrumb** [comment]
In fact really the issue here is that this isn't placeholder text, it's documentation, which definitely should be displayed differently.

**Comment by gashcrumb** [comment]
So quick test, really we should have been using `hint` for the description instead of `placeholder` but this seems like way too much information:

![download 1](https://user-images.githubusercontent.com/351660/28332162-bcd509ee-6bc1-11e7-8ec6-04d3f6025fec.png)

**Comment by jimmidyson** [comment]
Hmm yeah how about we make the hint text expandable by the user? Perhaps a placeholder would work in conjunction with hint to show less info but enough for those users familiar with syndesis (eventually)?

**Comment by gashcrumb** [comment]
Yeah, I can see if I can maybe make it truncated by default with a ... or 'more' link to show the rest of the text.

**Comment by gashcrumb** [comment]
Hmm, so the `hint` field is currently sanitized, so can't do much at the moment.  Opened [this issue](https://github.com/udos86/ng2-dynamic-forms/issues/444) to see if maybe we could get this.
