### ISSUE TITLE
Is salesforce username considered as a secret?

### ISSUE THREAD

**Issue by jknetl** [syndesisio/syndesis-ui#587]
When you are configuring a salesforce connection, the username is displayed as secret (you don't see entered data). I prefer to see plaintext where possible since it is less likely to make a mistake because you see entered data and you can immediately see the mistake.

**Comment by dsimansk** [comment]
This was fixed via https://github.com/syndesisio/connectors/pull/55/commits/14c852a30bbb79ad65114fb3bdbf3026555e1fae
