### ISSUE TITLE
Some folders in datamapper screen not visible after search

### ISSUE THREAD

**Issue by jknetl** [syndesisio/syndesis-ui#588]
After performing a search in datamapper and then cancelling the search. Folders which has not been opened are not visible.

It can be easily reproduced as follsows:

1. create twitter mention to salesforce upsert contact integration
2. add data mapper step
3. in twitter panel search for "name"
    * you will see matching items (some of them in "User" folder)
4. cancel the search (either by deleting text or clicking the "x" button on the right)

After these steps the fields are not filtered by search value. However only fields within the root and User folder are shown. Other folders are not visible. The only way how to see these folders again is to navigate to another step in the integration and then return to datamapper step.

In case you open some folders before performing the search, these folders will be also visible after cancelling the search.

**Comment by gashcrumb** [comment]
Issues for the data mapper page should be raised against the syndesis-datamapper-ui repo, have created an issue there for this one and linked it.

**Comment by jbakermd** [comment]
This issue has been fixed in our next-gen data mapper, which is in this repo now: https://github.com/atlasmap/atlasmap-ui

Note that the next-gen data mapper is not yet integrated with the larger Syndesis project.

**Comment by gashcrumb** [comment]
Cool, let's leave this one open and I'll create an issue for integrating the updated data mapper component, thanks!

**Comment by jbakermd** [comment]
Sounds good.

**Comment by gashcrumb** [comment]
Should probably continue the discussion in atlasmap/atlasmap-ui#32
