### ISSUE TITLE
Add support for inline documentation

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#589]
Using something like TypeDoc or JSDoc, we should really support inlining documentation while writing code.

**Comment by jludvice** [comment]
Hi @kahboom, what do you think about this? https://github.com/syndesisio/syndesis-project/issues/47
Would it fulfill your expectations?

**Comment by gashcrumb** [comment]
I think the intent here is for developer documentation for the source, not user documentation, right @kahboom?

**Comment by kahboom** [comment]
Yep that's correct @gashcrumb .  I've created a 'dev process' label, as sometimes this isn't very clear. My apologies @jludvice but thank you. :)

**Comment by kahboom** [comment]
Closing, duplicate of #131.
