### ISSUE TITLE
Consider using prettier for code formatting

### ISSUE THREAD

**Issue by jimmidyson** [syndesisio/syndesis-ui#591]
With recent versions, [prettier](https://github.com/prettier/prettier) supports typescript. It's a great, opinionated tool to enforce code conventions - consistency ftw.

**Comment by gashcrumb** [comment]
+1 we should settle on something to minimize the amount of changes per PR.  Right now I just rely on vscode doing the reformatting, but I'm sure I can get it to use whatever we decide on.

**Comment by gashcrumb** [comment]
Looks like we might want to use this too if we go this route -> https://www.npmjs.com/package/tslint-config-prettier

as there's some conflicting default rules between tslint and prettier.  But I do like how prettier formats some of our annoyingly long lines of code :-)

**Comment by gashcrumb** [comment]
This should be all set.
