### ISSUE TITLE
Uniqueness of Connection name / how to distinguish between them?

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-ui#594]
How can user distinguish between multiple connections of the same name?

![screenshot_20170704_140031](https://user-images.githubusercontent.com/8707241/27829303-44003cec-60c1-11e7-9730-098d75506881.png)

**Comment by rhuss** [comment]
Connections must be unique and I don't think this is a big restriction.

**Comment by gashcrumb** [comment]
We will probably need to enforce this when the user is entering a connection name, currently that's not being done.

**Comment by jludvice** [comment]
The enforcing should be at the api/rest level, right ?

**Comment by gashcrumb** [comment]
Probably but we could also stand to enforce it in the UI as well, I think we should have the list of connections cached to check against at least.

**Comment by akieling** [comment]
The user experience could be similar to the creation of a new e-mail address. When the Connection Name field loses focus, we check if the name is already taken and show a message. Do we have all connections on the client already? Are we validating the connection name on the server and is it unique in the database?

**Comment by gashcrumb** [comment]
You may have to inject the connection store (if it isn't already) and call loadAll() to get the list of connections, probably worth doing as part of loading the page.  

I don't think the name is validated server-side currently or a unique field in the DB either.

**Comment by jludvice** [comment]
Would it make sense to do request for server side validation rather than calling `loadAll` on client?

It should be validated later on server anyway, right?

**Comment by jimmidyson** [comment]
Validation in this case would be a simple GET with connection name, no? 404 means it's free...

**Comment by gashcrumb** [comment]
Yep that works too :-)

**Comment by akieling** [comment]
Do we have an endpoint to get a connection by name?

**Comment by gashcrumb** [comment]
hmm, I think it's by ID which is unique as far as I can see...  So we may
need support for that in the API if it's not there.

On Mon, Jul 31, 2017 at 9:52 AM, Alexandre Kieling <notifications@github.com

**Comment by akieling** [comment]
We can filter connections by name so there is a way...

**Comment by akieling** [comment]
@rhuss we need to add support for connection query by name in the API

**Comment by rhuss** [comment]
agreed. please open an issue in syndesis-rest for adding this to the rest API.

**Comment by akieling** [comment]
I created issue [475](https://github.com/syndesisio/syndesis-rest/issues/475) in syndesis-rest. This issue depends on it.
