### ISSUE TITLE
Data Mapper Integration for next gen Data Mapper UI.

### ISSUE THREAD

**Issue by jbakermd** [syndesisio/syndesis-ui#602]
Initial data mapper UI integration is done on this fork:

https://github.com/jbakermd/syndesis-ui

There are a couple of issues left to resolve, I'll open new tickets for these:

1. JSON/XML/Mapping services from the data mapper services project need to be provided on staging (or locally). This is issue #603.

2. Multi-source support integration needs to be added. This is issue #604.

3. XML source/target document inspection integration needs to be added. This is issue #605.

4. JSON source/target document inspection integration needs to be added. This is issue #606.

I am going to hold off on a pull-request for the changes on my fork until we have the new services available for developers.

**Comment by jbakermd** [comment]
Note that the integration work is available here: https://github.com/jbakermd/syndesis-ui

**Comment by jbakermd** [comment]
Please assign this ticket to me, as I'll be the one keeping up with it.

**Comment by gashcrumb** [comment]
@dsimansk FYI once this is closed (or maybe marked for QA) then the data mapper should be ready for testing again.

**Comment by dsimansk** [comment]
@gashcrumb thanks, I'll keep an eye on it.

**Comment by gashcrumb** [comment]
@jbakermd did you have any other changes to push for this issue now that the backend services are in place?

**Comment by jbakermd** [comment]
Yes, I'll do a PR from https://github.com/jbakermd/syndesis-ui in a moment, let me merge recent changes from this repo there first.

**Comment by jbakermd** [comment]
@gashcrumb  here's the PR: https://github.com/syndesisio/syndesis-ui/pull/608

**Comment by gashcrumb** [comment]
Awesome, thanks!  Looking at it now...

**Comment by jbakermd** [comment]
This issue is now closed with the following pull request:

https://github.com/syndesisio/syndesis-ui/pull/608

Other referenced issues will be used to keep track of their specific subject matter.

**Comment by gashcrumb** [comment]
@dsimansk There's one follow-on item I think before the data mapper will fully work on staging, you'll probably want to watch #609 too.
