### ISSUE TITLE
New Data Mapper Services need to be available for Developers.

### ISSUE THREAD

**Issue by jbakermd** [syndesisio/syndesis-ui#603]
The next-gen Data Mapper UI is being integrated back into the Syndesis UI. Several features in the Data Mapper UI require three new services from the data mapper services project:

1. Mapping Service - this provides data mapper validation rules and field actions configuration.

2. XML inspection service - similar to the pre-existing Java inspection service, but for XML.

3. JSON inspection service - similar to Java inspection service, but for JSON. 

These services are in this project:

https://github.com/atlasmap/atlasmap

Running the "atlas-itests" project from the atlasmap project will stand up a local instance of these services and the Java inspection service.

Note that some discussion on standing these services up is here: 

https://github.com/atlasmap/atlasmap-ui/issues/2

**Comment by jbakermd** [comment]
@mattrpav @chirino FYI.

**Comment by rhuss** [comment]
I'm going to start to move our openshift templates and the staging environent to atlasmap later todau.

**Comment by gashcrumb** [comment]
Awesome, thanks @rhuss.  I went ahead and assigned you and put this in progress

**Comment by jbakermd** [comment]
Thjs issue is being tracked on the atlasmap services side here: https://github.com/atlasmap/atlasmap/issues/13

**Comment by rhuss** [comment]
@gashcrumb Just updated staging with the latest atlasmap image. The OpenShift templates has been updated, too.

**Comment by gashcrumb** [comment]
Cool, let's close this one...
