### ISSUE TITLE
Data Mapper JSON Inspection Integration.

### ISSUE THREAD

**Issue by jbakermd** [syndesisio/syndesis-ui#606]
The Data Mapper UI and Services now support JSON inspection. This needs to be integrated into the Syndesis UI. 

Example code showing how to add a JSON documents to the Data Mapper UI config:

https://github.com/atlasmap/atlasmap-ui/blob/master/src/app/lib/syndesis-data-mapper/components/data.mapper.example.host.component.ts#L76

Example mock document creation methods:

https://github.com/atlasmap/atlasmap-ui/blob/master/src/app/lib/syndesis-data-mapper/services/document.management.service.ts#L524

**Comment by gashcrumb** [comment]
I think this is all set.
