### ISSUE TITLE
CI build broken

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#607]
Currently the CI build is broken building the docker image:

```
latest: digest: sha256:993a949a84f7e2eca6d35aa99aa3e99862cf59c354fe6acb3a729e1a3d51e518 size: 1783
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.security.selinux'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.security.selinux'
error: The token provided is invalid or expired.

Exited with code 1
```

@rhuss wonder, was there a user change for these images maybe?

**Comment by jimmidyson** [comment]
I think this is a problem with `oc import-image`

**Comment by gashcrumb** [comment]
Can't tell, I might go through and add some output statements to that script so it's a little more clear which command is failing.

**Comment by jimmidyson** [comment]
For some reason the deployer SA had been deleted from syndesis-staging... I've updated now and hope that all should work again.

**Comment by jimmidyson** [comment]
Yeah - all fixed (see https://circleci.com/gh/syndesisio/syndesis-ui/937)

**Comment by gashcrumb** [comment]
@jimmidyson awesome, thanks!
