### ISSUE TITLE
Need to update staging config.json

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#609]
With the data mapper update there's a set of replacement URLs needed in the `config.json`:

```json
    "baseJavaInspectionServiceUrl": "http://localhost:8585/v2/atlas/java/",
    "baseXMLInspectionServiceUrl": "http://localhost:8585/v2/atlas/xml/",
    "baseJSONInspectionServiceUrl": "http://localhost:8585/v2/atlas/json/",
    "baseMappingServiceUrl": "http://localhost:8585/v2/atlas/"
```

under the `datamapper` attribute.  Example config is updated, can't recall though where this comes from when the UI is deployed, apparently it's magic.  @jimmidyson?

**Comment by dsimansk** [comment]
@gashcrumb afaik it's stored in ConfigMap, you can find in [templates](https://github.com/syndesisio/syndesis-openshift-templates/blob/master/syndesis.yml#L2289).

**Comment by dsimansk** [comment]
@gashcrumb I've updated syndesis-staging ConfigMap with new URLs. And created a PR to templates repo that references this issue.

**Comment by jimmidyson** [comment]
@dsimansk Thanks!
