### ISSUE TITLE
Filter Step UI: Advanced Filter

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#615]
Separating this out, as we need to use a proper text editor instead of just a text area field.

**Comment by gashcrumb** [comment]
So I renamed the old filter to "Advanced Filter".  The remaining work is for this one is to change the text area to a proper text editor, which will mean adding a custom UI for this step type much like the basic filter or data mapper.

**Comment by kahboom** [comment]
Thanks @gashcrumb . Let's create a separate issue for the code editor.
