### ISSUE TITLE
Twitter Search: misaligned checkbox

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#619]
Checkbox seem to be a bit lost on its way to form fields.

![screen shot 2017-07-19 at 11 05 31](https://user-images.githubusercontent.com/5637792/28359418-6a998a54-6c72-11e7-8a63-13280a9afe00.png)

**Comment by gashcrumb** [comment]
Wonder if I mucked that up yesterday, will look into it today.

**Comment by gashcrumb** [comment]
@KurtStam is the twitter search stuff available in staging?  If I pick the twitter connection on staging the search action doesn't appear to have any properties.

**Comment by KurtStam** [comment]
@gashcrumb hmm it should since it's merged... let me check

**Comment by gashcrumb** [comment]
@KurtStam also tried creating a new twitter connection just in case, but same empty properties attribute.  Thanks for checking!

**Comment by KurtStam** [comment]
Seems to work ok on mini shift:

<img width="1352" alt="screen shot 2017-07-19 at 12 24 44 pm" src="https://user-images.githubusercontent.com/35576/28378274-a633696c-6c7d-11e7-9c72-20072d38d9b4.png">

Maybe we need to push to staging.

**Comment by rhuss** [comment]
Let me check the version on staging ....

**Comment by gashcrumb** [comment]
@rhuss see it now, thanks!
