### ISSUE TITLE
Datamapper Step does not show up

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#621]
When adding a datamapper step, then nothing changes on the main screen (still shows "Add to integration").

In the console it can be seen that the mapping for `io.syndesis.connector.salesforce.Contact` cannot be found, which is possibly due to that the classpath request returns an empty classpath (as already mentioned in https://github.com/atlasmap/atlasmap/issues/28

However I wonder why atlasmap returns a 200 as HTTP return code and not a 404 ?

**Comment by gashcrumb** [comment]
There's definitely some issues that I'm seeing as well while testing this morning.  For the 'asdffdsa' integration the start connection is missing it's outputDataShape, while the end connection doesn't have an inputDataShape:

step 0 in the integration:

```
"inputDataShape": {
          "kind": "java",
          "type": "io.syndesis.connector.salesforce.Contact"
        },
        "outputDataShape": {
          "kind": "none"
        },
```

last step in the integration:

```
 "inputDataShape": {
          "kind": "none"
        },
        "outputDataShape": {
          "kind": "java",
          "type": "twitter4j.Status"
        },
```

I'd expect these to be the other way around, i.e. the first step should have an OutputDataShape and vice versa for the last connection.  Most likely then what could be happening for this one is our wrapper doesn't even bother to initialize the data mapper as it doesn't have type information.

I'll have to check some of the other ones.

**Comment by gashcrumb** [comment]
Yeah, for the twitter to salesforce example there's a new error that we're apparently hitting that isn't logged very well to the javascript console.  Will look into it further.

**Comment by gashcrumb** [comment]
With the `Twitter to Salesforce Example` integration it looks like maybe there's some difference in the expected mapping file format.  We pass along this mapping document:

```json
{
  "AtlasMapping": {
    "jsonType": "com.mediadriver.atlas.v2.AtlasMapping",
    "properties": {
      "property": [
        
      ]
    },
    "fieldMappings": {
      "fieldMapping": [
        {
          "jsonType": "com.mediadriver.atlas.v2.SeparateFieldMapping",
          "inputField": {
            "jsonType": "com.mediadriver.atlas.v2.MappedField",
            "field": {
              "jsonType": "com.mediadriver.atlas.java.v2.JavaField",
              "name": "Name",
              "path": "User.name",
              "type": "STRING",
              "getMethod": "getName"
            },
            "fieldActions": {
              "fieldAction": [
                
              ]
            }
          },
          "outputFields": {
            "mappedField": [
              {
                "jsonType": "com.mediadriver.atlas.v2.MappedField",
                "field": {
                  "jsonType": "com.mediadriver.atlas.java.v2.JavaField",
                  "name": "FirstName",
                  "path": "FirstName",
                  "type": "STRING",
                  "setMethod": "setFirstName"
                },
                "fieldActions": {
                  "fieldAction": [
                    {
                      "jsonType": "com.mediadriver.atlas.v2.MapAction",
                      "index": 0
                    }
                  ]
                }
              },
              {
                "jsonType": "com.mediadriver.atlas.v2.MappedField",
                "field": {
                  "jsonType": "com.mediadriver.atlas.java.v2.JavaField",
                  "name": "LastName",
                  "path": "LastName",
                  "type": "STRING",
                  "setMethod": "setLastName"
                },
                "fieldActions": {
                  "fieldAction": [
                    {
                      "jsonType": "com.mediadriver.atlas.v2.MapAction",
                      "index": 1
                    }
                  ]
                }
              }
            ]
          }
        },
        {
          "jsonType": "com.mediadriver.atlas.v2.MapFieldMapping",
          "inputField": {
            "jsonType": "com.mediadriver.atlas.v2.MappedField",
            "field": {
              "jsonType": "com.mediadriver.atlas.java.v2.JavaField",
              "name": "Text",
              "path": "Text",
              "type": "STRING",
              "getMethod": "getText"
            },
            "fieldActions": {
              "fieldAction": [
                
              ]
            }
          },
          "outputField": {
            "jsonType": "com.mediadriver.atlas.v2.MappedField",
            "field": {
              "jsonType": "com.mediadriver.atlas.java.v2.JavaField",
              "name": "Description",
              "path": "description",
              "type": "STRING",
              "setMethod": "setDescription"
            },
            "fieldActions": {
              "fieldAction": [
                
              ]
            }
          }
        },
        {
          "jsonType": "com.mediadriver.atlas.v2.MapFieldMapping",
          "inputField": {
            "jsonType": "com.mediadriver.atlas.v2.MappedField",
            "field": {
              "jsonType": "com.mediadriver.atlas.java.v2.JavaField",
              "name": "ScreenName",
              "path": "User.screenName",
              "type": "STRING",
              "getMethod": "getScreenName"
            },
            "fieldActions": {
              "fieldAction": [
                
              ]
            }
          },
          "outputField": {
            "jsonType": "com.mediadriver.atlas.v2.MappedField",
            "field": {
              "jsonType": "com.mediadriver.atlas.java.v2.JavaField",
              "name": "Title",
              "path": "Title",
              "type": "STRING",
              "setMethod": "setTitle"
            },
            "fieldActions": {
              "fieldAction": [
                
              ]
            }
          }
        }
      ]
    },
    "name": "twitterStatusToSalesforceContact",
    "sourceUri": "atlas:java?className=twitter4j.Status",
    "targetUri": "atlas:java?className=io.syndesis.connector.salesforce.Contact"
  }
}
```

but the code is expecting a `dataSource` attribute which doesn't appear to be in the above

```typescript
    public static deserializeDocs(json: any, mappingDefinition: MappingDefinition): DocumentDefinition[] {
        var docs: DocumentDefinition[] = [];
        for (let docRef of json.AtlasMapping.dataSource) {    // <<<<<<<<<<<<< NPE
```

@jbakermd does that seem accurate?  Seems like this might need to be updated in the integration.

**Comment by gashcrumb** [comment]
Even creating a new integration and adding a mapping step yields the same apparently behavior, so maybe there's a couple bugs here.

**Comment by jbakermd** [comment]
The mapping that's stored is out of date due to format changes in the mapping format JSON. The "dataSource" collection of data source information was added recently (within the last month).  

The mapping that's stored for this integration in the Syndesis DB is stale and needs to be removed to start over. 

If the issue persists after DB removal then we're probably having problems with developers on different versions of the data mapper UI working with the shared integration. 

Someone currently running the summit demo era datamapper UI will be writing that older mapping format to the DB and expecting that older mapping format from the DB. Meanwhile, developers on the latest datamapper UI integration will be seeing errors like this when that older version of the mapping comes from Syndesis. 

Does this make sense?

**Comment by jbakermd** [comment]
@gashcrumb oh, interesting point about creating a new integration yielding the same behavior. Can we do a call about this on bluejeans in a few hours, say 12p central?

**Comment by jbakermd** [comment]
@rhuss  regarding the 200 status response vs 404 status response from the service when a document isn't found. The 404 in this case would mean the service itself isn't found. The 200 response indicates the service is doing ok, but the response itself contains a json formatted error informing the UI that inspection failed for the provided reason (class not found, etc).

**Comment by gashcrumb** [comment]
Found the real culprit.  Definitely handling older mapping documents is an issue that will need attention, should be opened as a new issue.

**Comment by jimmidyson** [comment]
If there's an error we really shouldn't be returning a 200. Recommend we pick a more appropriate status code as this aids consumer's error handling logic.
