### ISSUE TITLE
Change HTTP server to nginx instead of caddy

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#622]
As it can be productised easier. See https://issues.jboss.org/browse/ENTESB-6991 for details.

**Comment by jimmidyson** [comment]
:sob:

**Comment by rhuss** [comment]
sorry, poor jimmi. I really love it. 

do you want to keep caddy in the community image ? We need to think about to split community  vs. product anyway for the other base images, too.

**Comment by jimmidyson** [comment]
I'm not attached to it at all so if it makes productisation easier then :+1:

**Comment by kahboom** [comment]
nginx is awesome @jimmidyson !

**Comment by rhuss** [comment]
@jimmidyson could you pick up this one please ? We need this for running on OSO (which does not allow Docker VOLUMEs)

Shouldn't be hard, except maybe to chose which base image. If we already could use the productised nginx image from Red Hat, that would be the optimal one. Otherwise the 'official' nginx image is probably the choice to go.

**Comment by rhuss** [comment]
@jimmidyson Any news on this? Would love to continue to get our OSO Pro account running (and this is the last open issue). Alternatively, we could change the base caddy image to not use volumes.

**Comment by jimmidyson** [comment]
Well sort this tomorrow
