### ISSUE TITLE
Filter UI gotchas

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#623]
I stumbled upon the following things in the filter UI while testing:

* "Browse" button for the set of available fields doesnt' work. @iocanel I guess the backend service for this is still missing or unclear how to get these fields. If we would get the metadata of the object back from syndesis-rest (as we need it for the datamapper as well, see https://github.com/atlasmap/atlasmap/issues/28), then we could reuse this information here. In the worstcase we could call the atlasmap like we do for the datamapper step to initialize the screen.
* If moving away from the filter form and coming back in another integration (without saving) its still populated with data
* Why are there five row initially ?
* Saving doesn't seem to work. I.e. when looking in the network tab, the form values are not included in the integration to save.

Could be that some of the issues are vanishing while we update the backend, I will keep this issue up to date.

**Comment by dsimansk** [comment]
I got one minor (uber nitpicking) issue. Considering upstream project, shouldn't we avoid examples like `e.g. Red Hat`.

**Comment by jimmidyson** [comment]
@dsimansk Totally agree.

**Comment by kahboom** [comment]
@rhuss - Some responses:

[Here](https://redhat.invisionapp.com/share/VQ8UZ7PCE#/243360307_IPaaS_Integration_Filter_6-26-pdf_5) is the design for reference.

- Yes, the Browse button isn't working. This is not a common element in any framework so am trying to find a way to get it to work with ng2-dynamic-forms, as it's not really a tooltip, but more like a dropdown menu. I guess I can style it to look this way, but it will be a bit more challenging with that framework.
- Should the form clear on exit? Or be saved automatically as a draft? I can't remember what we had decided for this.
- How many rows would you like? The design shows two I think, so I can change it to that.
- Sorry, this is part of what's missing, the API needs to be wired up now. As in, in the next hour or so.
- @dsimansk - Agree regarding the placeholder, but what should it say? Blank looks a little, well, blank.. maybe @sjcox-rh and @dongniwang can chime in here.

**Comment by rhuss** [comment]
> How many rows would you like? The design shows two I think, so I can change it to that.

tbh, I would start with one (as this is one of the most common use case I guess)

**Comment by iocanel** [comment]
@rhuss @kahboom: We need to get https://github.com/syndesisio/syndesis-rest/pull/443 for it to work. BTW what is the exact URL that its using?

**Comment by gashcrumb** [comment]
Yeah, so ideally the popover opened by that browse button would re-use the field selector from the data mapper component, but it might be better to save that for a second pass for implementation.

Typeahead for starters would be nice if we have the type info available.

>Should the form clear on exit? Or be saved automatically as a draft? I can't remember what we had decided for this.

When 'next' is clicked the form *needs* to update the integration with it's state which should happen [here](https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/edit-page/step-configure/step-configure.component.ts#L84-L94).  Eventually this service will probably post the update to the backend but for now it's in-memory like usual.

> @dsimansk - Agree regarding the placeholder, but what should it say? Blank looks a little, well, blank.. maybe @sjcox-rh and @dongniwang can chime in here.

How about just *Keywords here...* we can refine it later.

**Comment by dongniwang** [comment]
- Click "Next" - should save the data users entered 
- Click "anywhere else" other than Next should just display a message saying that all data users entered will not be saved...

Agreed that _Keywords_ is good for now.

**Comment by kahboom** [comment]
Closing and opened more specific issues, as some of these have been resolved. #654 #631 #630 #637
