### ISSUE TITLE
Advanced Filter Step: Code Editor

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#635]
Use Angular 2+ implementations of Code Mirror or ACE, browser-based code editors.

### Relevant Issues
- Filter Step UI: Advanced Filter #615

**Comment by dsimansk** [comment]
Hi, @davsclaus! Just out of my curiosity, I've been wondering if we could leverage some prefabricated code completion sources from you Camel IDEA plugin and leverage it for Advanced Filter step editor?

**Comment by gashcrumb** [comment]
Let's take this off of the table for now until PM decide this is a requirement :-)
