### ISSUE TITLE
Basic Filter Step: Load Options & Sub-Options

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#637]
Load filter options and sub-options.

![243360307](https://user-images.githubusercontent.com/3844502/28503431-a3a23764-6fd4-11e7-9756-2af8b74c62a6.jpg)

Ideally using something like the data mapper component and abstracting it for re-use (may or may not be possible).

### Resources
- [Design](https://redhat.invisionapp.com/share/VQ8UZ7PCE#/243360307_IPaaS_Integration_Filter_6-26-pdf_5)
- [Filter Step GH Issue](https://github.com/syndesisio/syndesis-ui/issues/569)

**Comment by kahboom** [comment]
Can add some dummy data for now, but since the data structure is quite complex, with deeply nested arrays and objects, it could be more effort and time than we should exert. I've opened up an issue in the REST repo to resolve the issue with the endpoint URL structure.

**Comment by rhuss** [comment]
@kahboom would be awesome if you connect all filter relates issue to the epic. Just use the section on the right column of an issue. thanks ;-) !

**Comment by kahboom** [comment]
Thanks @rhuss , good call, will do that 👍

**Comment by kahboom** [comment]
You beat me to it! To most anyway :)

**Comment by rhuss** [comment]
I fixed the REST API and the connection to it to obtain the possible options which should be used to populate the dropdownfields as shown above. You can see the format in the console when selecting "BasicFilter":

![image](https://user-images.githubusercontent.com/99080/29130487-43ba12d2-7d2a-11e7-9a59-034533098681.png)

I don't know how hard this is to implement, but having this for Friday would be awesome (and know I continue to dream on ;-) // @gashcrumb
