### ISSUE TITLE
Exception on staging on latest version for integration details page

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#638]
Happens when going into to the integration detail page:

![image](https://user-images.githubusercontent.com/99080/28531228-750f9028-7096-11e7-9966-894732afb477.png)

**Comment by gashcrumb** [comment]
Ah, this is due to the patternfly update.  Looks like the API changed for the vertical menu, will look into it today.

**Comment by rhuss** [comment]
@gashcrumb Should we leave this issue open until fixed on the patternfly side ?

**Comment by gashcrumb** [comment]
Yeah, linked PR is just a temp fix.

**Comment by gashcrumb** [comment]
Upstream issue -> https://github.com/patternfly/patternfly/issues/691
