### ISSUE TITLE
Improve object-property-filter to work with multiple filters

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#643]
Given that patternfly-ng's toolbar implementation supports multiple filters applied to the list we should update this pipe to work with multiple filters rather than just one.  

Could also allow the pipe to still work with one filter just so we don't have to change all our current views.

**Comment by gashcrumb** [comment]
@astefanutti ditto wit this one, do you think this is still relevant with all your refactoring work?

**Comment by astefanutti** [comment]
I think we may close this one and concentrate on #649 at some point. I've done the multi-filtering thing programmatically as it was simpler anyway.

**Comment by gashcrumb** [comment]
ok, cool
