### ISSUE TITLE
Improve object-property-filter and object-property-sort to work with native patternfly-ng configuration

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#644]
It'd be really nice if we could use a patternfly-ng toolbar and share the config for filtering and sorting with our own pipes to minimize the amount of code needed in the page component to manage all of these parts.  Right now you need a couple glue functions (will link an example once my PR merges)

**Comment by gashcrumb** [comment]
@astefanutti do you think this issue is still valid?

**Comment by astefanutti** [comment]
I think we may close this one and concentrate on #649 at some point. I don't feel much urge for it ATM.

**Comment by gashcrumb** [comment]
K
