### ISSUE TITLE
Use patternfly-ng toast notification component

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#648]
Think we use a different one and have had to customize it's look, probably worth switching over to the patternfly-ng one

**Comment by kahboom** [comment]
Related to #242 and #375

**Comment by astefanutti** [comment]
The [toast notification component](https://github.com/patternfly/patternfly-ng/tree/8027b6f409ab6456b0a7d2ecde4aa0211897e709/src/app/notification) looks in good shape so let me have a look at that issue.
