### ISSUE TITLE
Basic Filter: Changes persisted in-memory prior to saving

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#654]
Important bug related to persistence in the API vs in-memory store, as pointed out in issue #623.

How to reproduce:
1. Make changes to an integration's basic filter rule.
2. Do not save changes to the integration.
3. Begin to create a new integration and add the basic filter as a step.
4. Fields will be pre-populated (or rule rows appended will appear as well) with values from the prior integration's basic filter step.

This is a brand new integration, attempting to add a basic filter step, without ever having saved:

<img width="1206" alt="screenshot 2017-07-25 10 43 00" src="https://user-images.githubusercontent.com/3844502/28577914-19bbbe1e-7126-11e7-9ed4-a065b9270929.png">

**Comment by gashcrumb** [comment]
Fixing this as part of fixing https://github.com/syndesisio/syndesis-ui/issues/631
