### ISSUE TITLE
Integration Editor: too wide resolution not properly scaling

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#658]
Recently I have noticed that Connection are stretched too wide and the last one is not visible fully.

<img width="963" alt="screen shot 2017-07-26 at 09 16 10" src="https://user-images.githubusercontent.com/5637792/28609011-1bf3beda-71e3-11e7-8e72-92c4afc15898.png">

**Comment by jimmidyson** [comment]
There are quite a few issues at different screen resolutions across the app. I would love to see screenshots at various resolutions (and supported browsers perhaps?) taken during e2e tests perhaps that can be manually reviewed?

**Comment by rhuss** [comment]
@jimmidyson this particular issue is independent of the screen size. The scrollbar remains regardless of the screen width.

**Comment by jimmidyson** [comment]
Yeah in this case, but it would still be picked up easier by screen grabs in CI, plus checking for regressions.

**Comment by gashcrumb** [comment]
It's due to the workaround in place currently for https://github.com/syndesisio/syndesis-ui/issues/638
