### ISSUE TITLE
"Create Integration" layout is distorted

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#659]
![image](https://user-images.githubusercontent.com/99080/28611293-9af96f92-71eb-11e7-9e59-85c24909b2e0.png)

One has to always scroll to the right, regardless of the window size. Also the left column seems to be clipped of.

**Comment by gashcrumb** [comment]
This is a side-effect of the workaround I put in to avoid the NPE thanks to the main navigation, let me follow up on that issue with the patternfly folks.

**Comment by gashcrumb** [comment]
This duplicates #658
