### ISSUE TITLE
UX for entering integration name is irritating

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#661]
When creating a new integration on sees a screen like this:

![image](https://user-images.githubusercontent.com/99080/28613047-85f790b4-71f1-11e7-9280-595e4eb11fa4.png)

However, when pushing the stylo, it is _not the supposed textfield_ which can be edited but a complete new form appears on the right hand side:

![image](https://user-images.githubusercontent.com/99080/28613085-a3018d04-71f1-11e7-83e6-303665b838be.png)

IMO this is counter intuitive and contrary to my user experience with other UIs where I would have expected that the cursive text represents a text input field (as we have in other places, too), which gets enabled by pushing the stylo button. 

Also, as the name is marked as mandatory, I wonder why don't we ask for the name in the very beginning (I remember we already had some discussion around this pre-summit)

When I now save the integration, I get back to the overview page. The integration now has everything to get published. However, when I go back to the details page, there is no "Publish" button:

![image](https://user-images.githubusercontent.com/99080/28613308-5a5618f8-71f2-11e7-9931-b64b3b8f504f.png)

(note also the strange behavior of the bubble menu when scrolling to the left, but thats another issue, possibly related to #659 ).

I have to press the stylo again to make the "Publish" button appear:

![image](https://user-images.githubusercontent.com/99080/28613365-80f1a220-71f2-11e7-8ffe-628a07096d4a.png)

Also, when pressing the stylo, the text field changes back to _Enter integration name_ instead of showing the already saved integration name:

![image](https://user-images.githubusercontent.com/99080/28613430-a287007e-71f2-11e7-8425-4452320928e3.png)

As said, for me the UX is irritating here, but I could be wrong of course, too. @syndesisio/design-ux @kcbabo wdyt about the current behaviour ? Should it be improved ? Or is this totally ok like this ?

**Comment by gashcrumb** [comment]
I feel like when we have a detail page this particular page can go away
completely, as I'd just make the name and description possibly editable
from the detail page and make the name at the top left in the editor back
into a editable text field.

**Comment by kahboom** [comment]
I hate this as well, agree w/ @rhuss . But like @gashcrumb says maybe the detail page will resolve this? Maybe we'll still need a way for them to see the name of the integration and that they can edit it at all times. The thing is that we also want to generate them automatically if the user doesn't fill anything out, so not sure why it's still a required field. At one point we decided it would be optional, but maybe someone can remind me why we changed our minds?

**Comment by dongniwang** [comment]
Yes, I think some of the behaviors we have right now are summit related decisions. Happy to revisit this to make it a better user experience. 

@rhuss Do you think if this is a UX issue (not just a ui bug) then maybe we could create the issue in the UX repo to address the need? We do have a label "UX needed" for non sprint requirements. That way, this gets in the UX work queue (and we have a backlog milestone as well). 

@gashcrumb Agreed that the detail page may help. @kahboom I think we go back and forth on when to ask for integration name, and I do also remember the decision about generating integration name automatically. We just need to document the design decisions. 

cc: @sjcox-rh

**Comment by gashcrumb** [comment]
Issue moved to [syndesisio/syndesis-ux #24](https://github.com/syndesisio/syndesis-ux/issues/24) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gashcrumb** [comment]
Going to implement the behavior mentioned in syndesisio/syndesis-ux#24
