### ISSUE TITLE
Duplicate integrations when editing

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#662]
When editing an integration it draft state it gets duplicated:

![image](https://user-images.githubusercontent.com/99080/28613737-87083ec0-71f3-11e7-952d-88ec18b4e447.png)

Could be a backend issue, too, though.

**Comment by gashcrumb** [comment]
Does this happen when you save it or even if you cancel out of the editor.
So far I've noticed these duplicates occur when saving, so I kinda think
this is a backend issue.

**Comment by kahboom** [comment]
Yep that's what I noticed as well, but will try again in a bit to confirm.

**Comment by zregvart** [comment]
I've created a PR that will probably fix this on the backend syndesisio/syndesis-rest#461

**Comment by zregvart** [comment]
This was auto-closed, but if you see this again please reopen.

**Comment by rhuss** [comment]
looks good for me on minishift.
