### ISSUE TITLE
Discuss guidelines for css selectors in ui

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-ui#663]
Hi @gashcrumb  @kahboom  (CC @dsimansk  @lvydra )

We have several places in syndesis-ui where it's tricky to write proper selectors in e2e tests.
Mostly because it's deep tree of nested `div` elements and we have to select elements based on text content of some nested `h2` or `p` element.

## List items (connection list, integration step...)

It's little bit easier on connections list page.
Here the elements have `title` and we could write something like `$('div[title="Some Twitter Connection"]')`
There was brief discussion in comments of https://github.com/syndesisio/syndesis-ui/issues/546

So far our preferred solution would be to have angular component for collection items.
Would it be benefitial also for you @kahboom @gashcrumb  to create angular components for collection items like this?

* `integration` where I could write CSS selector `$('integration[title="My awesome integration"]')
* `integration-step` where I could write `$('integration-step[title="Data Mapper"]')

In cases where we don't wont (or can't do right now) introduce angular componnet,
the approach with nested div elements -> can we at least 
* add the `title` or similar to be able to lookup given item from list
* add meaningful css class to filter out proper element I want to click on
Examples of selectors
* for integration in integrations list: `$('div.integration[title="My sample integration"])`
* for integration step `$('div.integration-step[title="Data Mapper"]')`

One option which might be easy to use for us is to use IDs on elements.
I didn't focus in this option because I thought it would be more complicated for you to always come up with unique id for list items.

## Forms (create connection / access tokens...)
We didn't have any issues with automated form filling afaik.
The selector used to lookup input fields looks like this: `$('input[name="accessToken"]')` and it looks pretty straightforward. Do you agree?

**Comment by kahboom** [comment]
This has definitely always been my preference and probably the "right" way to test Angular stuff. Some things are generated automatically from libraries, nested within component titles, and it might be more difficult to target those. The same problem happens with CSS, but there are ways to work around this we can look into.

**Comment by gashcrumb** [comment]
>So far our preferred solution would be to have angular component for collection items.
Would it be benefitial also for you @kahboom @gashcrumb to create angular components for collection items like this?

This may not be realistic due to the way elements need to be laid out in patternfly, that being said there's no reason we can't add element IDs where needed.

**Comment by gashcrumb** [comment]
So also the thing is when producing these views I'm not going to know exactly what's required for testing, or I may not consider a view to be finished.  It may be necessary to raise specific issues on pages as this becomes a problem to add the IDs where needed.

**Comment by jludvice** [comment]
@gashcrumb  @kahboom @lvydra  we can probably close this issue since #717 is merged.

Generally we were having issues with selecting the right item from the list,
and here is sample of what looks reasonable for e2e tests -> here we want to open integration named `Facebook Photo to Twitter`
selecting integration like this `$('div.integration[title="Facebook Photo to Twitter"]')` is possible since #717 
![selectors](https://user-images.githubusercontent.com/8707241/28912491-c0f48de0-7834-11e7-9532-55cb9f7d99fd.png)
