### ISSUE TITLE
Connection view/detail loading weirdness

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#668]
There's some loading problems currently when you switch between viewing different connections and editing them.  The general way to reproduce this is to go into one connection from the connection list, then go back to the list and then go into another connection.  Or go directly to the edit screen, sometimes there's a mismatch between the form for a connection and the connection object.

![jul 26 2017 11-43 am](https://user-images.githubusercontent.com/351660/28630440-42ec4786-71f8-11e7-8b28-dae70cb426c8.gif)

**Comment by gashcrumb** [comment]
Could be doing this refactor coud help here -> https://github.com/syndesisio/syndesis-ui/issues/652

**Comment by gashcrumb** [comment]
Sorry @astefanutti the fix for this actually broke the form in edit mode and in the create connection wizard.  I think switching the formGroup accessor to a function renders the form read-only (which is a weird side-effect but...) which as I recall is why the get accessor function is being used on the controller.  I've reverted that PR for now so those pages should work again, this issue though will need a second look.

**Comment by astefanutti** [comment]
@gashcrumb no worries, should have been more careful. I'll have that second look at it ASAP.

**Comment by gashcrumb** [comment]
@astefanutti no worries, it's more my hacky implementation to thank than anything.

I wonder if working towards this might be worthwhile -> https://github.com/syndesisio/syndesis-ui/issues/652 as I really made that connection view controller a bit complicated :-)

**Comment by astefanutti** [comment]
@gashcrumb yes I'm planning to tacle #652, yet still think it's worth a short term fix.
