### ISSUE TITLE
Side menu not collapsing when creating a new integration

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ui#669]
When the create an integration flow starts, the side menu should collapse. Collapsing the side menu allows users to focus on the main task. 

Wondering if this is a bug? 

![image](https://user-images.githubusercontent.com/24943812/28638201-1d7f21de-7212-11e7-98cb-a84bf07edbae.png)

cc: @sjcox-rh

**Comment by gashcrumb** [comment]
Yes, it's a known issue, I hit this upgrading patternfly -> https://github.com/syndesisio/syndesis-ui/issues/638

Actually if you know any of those folks I'd love it if they could take a look at  -> https://github.com/patternfly/patternfly/issues/691
