### ISSUE TITLE
Drill down to connection page from an integration definition page

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#673]
When looking at an existing integration, only the connector type (via icon) and the action chosen can be seen, real connection behind it is seen only via tooltip.

A cross link to the connection detail page would be awesome so that the configuration of this connection could be examined.

would this make sense from a ux perspective, too ?

**Comment by gashcrumb** [comment]
I think it'd make sense from the integration detail page once we have one.  Not sure where the link would go if we're in the editor.

Also I'd definitely hold off on this one until we're regularly synchronizing state with the backend, as currently all your edits would be lost.

**Comment by gashcrumb** [comment]
@syndesisio/design-ux FYI...

**Comment by dongniwang** [comment]
Are you talking about this?
![image](https://user-images.githubusercontent.com/24943812/28677830-b79a5072-72bc-11e7-843a-1ee3af2f6d00.png)

From the design, it's only showing the Connection Title, not the action. See InVision file below: https://redhat.invisionapp.com/share/VQ8UZ7PCE#/224783021_IPaaS_CreateIntegration_MultiStep-pdf_2

Which one is more valuable, or should we actually show both? Also, the icons are supposed to tell users what kind of connection they are using. 

> A cross link to the connection detail page would be awesome so that the configuration of this connection could be examined.

What do you mean by this? Add a link to the circle icon so when users click on the icon, they get to the connection details page?

**Comment by sjcox-rh** [comment]
yeah I agree with @gashcrumb  and think the connection details would be valuable within the integration details page rather than within the integration flow. Clicking on a link to view connection details would interrupt the workflow of creating an integration, I think. @rhuss

**Comment by rhuss** [comment]
I'm totally fine with drilling down from an integration to a connection from the details page

The only thing I found a bit hidden is the _name of the connection_ as it is only shown in a tooltip when hovering over the (twitter) icon.

**Comment by gashcrumb** [comment]
Yeah, I think the reason why the connection name wound up in a tooltip is due to the length of the action name + the connection name.  For example `Salesforce Create/Update Contact` is a bit lengthy for the available space in the scope of the design.  And actually, it' a user-created connection name, so it could be a string like 'Our Marketing Department Salesforce - Create/Update Contact' which will never fit in that area properly.

**Comment by dongniwang** [comment]
So maybe the tooltip should also appear when hovering over the title (the gray bar where now shows the action)?

**Comment by gashcrumb** [comment]
Now that we have the integration detail page I think it makes sense to link from connections in the diagram of the integration to the connection detail page.
