### ISSUE TITLE
[Datamapper]Error message appears in double for Conversion between source and target is not supported

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#678]
I created a single mapping but I have 2 error messages

![image](https://user-images.githubusercontent.com/1105127/28672280-9ca65284-72df-11e7-97fb-6ee2981812f3.png)

**Comment by akieling** [comment]
This issue is caused by a bug in atlasmap and is being tracked in https://github.com/atlasmap/atlasmap/issues/127

**Comment by gashcrumb** [comment]
I think this is being tracked in https://github.com/atlasmap/atlasmap-ui/issues/112
