### ISSUE TITLE
[Datamapper]Error message for conversion are stacking up

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#679]
If I click several times between the same elements in the lists (and so just wanting to highlight the same mapping and if it is invalid, the error message is stacking up:

![image](https://user-images.githubusercontent.com/1105127/28672501-31c86a1e-72e0-11e7-83fb-39a611c66f4f.png)

**Comment by apupier** [comment]
root issue might be that the mappings between the same elements are duplicated:

![image](https://user-images.githubusercontent.com/1105127/28672596-73773490-72e0-11e7-8eda-1f08831d95b7.png)

**Comment by akieling** [comment]
Fixed by atlasmap/atlasmap-ui#80

**Comment by gashcrumb** [comment]
@akieling Wonder, should these maybe stay open until we get a PR that updates the [commit SHA](https://github.com/syndesisio/syndesis-ui/blob/master/package.json#L51)?

**Comment by akieling** [comment]
@gashcrumb You are right. I'll reopen it and send a PR updating the dependency.
