### ISSUE TITLE
[Datamapper]Some top level elements are duplicated (Status/Contact)

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#680]
see screenshot, both Status and both Contact are containing the same information

![image](https://user-images.githubusercontent.com/1105127/28672980-81baeaa0-72e1-11e7-81fa-8a3a48964b2f.png)

**Comment by gashcrumb** [comment]
Hoping this PR sorts this kind of thing -> https://github.com/syndesisio/syndesis-ui/pull/686

**Comment by gashcrumb** [comment]
Yep, that definitely does it, BTW this was already opened here -> https://github.com/atlasmap/atlasmap-ui/issues/41

**Comment by gashcrumb** [comment]
Let's track the issue in the data mapper UI repo since it's there already.
