### ISSUE TITLE
[Datamapper]UI glitch: 2 fields of "Create Property" dialog are cropped

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#681]
they don't have the left line:

![image](https://user-images.githubusercontent.com/1105127/28673027-ab53ad02-72e1-11e7-89b9-649ca2366eda.png)

it appears when we put the cursor inside:
![image](https://user-images.githubusercontent.com/1105127/28673034-b2c63e9c-72e1-11e7-9605-9150aea48eb9.png)

tested on Chrome

**Comment by akieling** [comment]
This issue isn't happening anymore.
