### ISSUE TITLE
[Datamapper] Adding property with existing name seems allowed but nothing happens

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#682]
- create property with Name "mydata", click on Save
- try to create another property "mydata",
--> Save is still enabled
--> when clicking Save, nothing happens

it is also the case when using a different case, for instance "myData"

**Comment by akieling** [comment]
@rhuss do you know the validation rules we need to run when adding properties in the data mapper?

**Comment by rhuss** [comment]
@akieling sorry, no idea. But @igarashitm is on it I guess ...

**Comment by gashcrumb** [comment]
This issue was moved to atlasmap/atlasmap-ui#127
