### ISSUE TITLE
[Datamapper]Error never cleared "The field 'Contributors' cannot be selected, Repeated fields are not valid for this mapping."

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#683]
Don't know why I get this error (I just selected the "contributors" field of Twitter demo)  but I deleted all mappings and the error is still displayed:

![image](https://user-images.githubusercontent.com/1105127/28673603-33f11612-72e3-11e7-9aac-75ccd51064b2.png)

**Comment by apupier** [comment]
@akieling no, it was a month ago and i don't have a Syndesis instance available

**Comment by akieling** [comment]
Cannot reproduce it.
