### ISSUE TITLE
Need to scroll to the right to see "next" button

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#687]
![image](https://user-images.githubusercontent.com/1105127/28677432-c5983866-72ed-11e7-8a63-e672c4cb6653.png)

![image](https://user-images.githubusercontent.com/1105127/28677449-c991c1ee-72ed-11e7-8e48-bec76643a9a1.png)

**Comment by gashcrumb** [comment]
Yep, this is a known issue -> https://github.com/syndesisio/syndesis-ui/issues/658 just waiting for a patternfly release...

**Comment by apupier** [comment]
sorry for the duplicate
