### ISSUE TITLE
[Datamapper]Refresh of display of "lines" representing mapping not done when changing some options

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#692]
- "show lines"
- map two fields

![image](https://user-images.githubusercontent.com/1105127/28678264-3a01e934-72f0-11e7-9541-ba3ab7bb4609.png)

- uncheck "show mapped fields"
![image](https://user-images.githubusercontent.com/1105127/28678284-48ba9bec-72f0-11e7-82c5-63abe738dbba.png)

line is still displayed

workaround: the line disappears when scrolling in sources or data

**Comment by gashcrumb** [comment]
@igarashitm wonder, does this still happen, do you know?

**Comment by igarashitm** [comment]
I just tried atlasmap-ui locally and didn't see it, the line disappeared immediately.

**Comment by gashcrumb** [comment]
Cool, let's close this then, Jason must have already fixed it.
