### ISSUE TITLE
Disallow navigating out of a flow of pages

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#696]
To avoid getting into a state as indicated by https://github.com/syndesisio/syndesis-ui/issues/691 we should try and prevent the user from being able to navigate out of a flow of wizard pages in the editor.  For example, you can currently do the following:

1) Add a 'log' step
1)  Delete the 'start' connection
1)  Click on the 'log' step in the flow view

Now you're looking at the configuration for the log step but there's no start connection because the user deleted it.  Ideally if the user deletes the start or end connection, he'd have to go through the flow of pages to add a new connection and not be able to edit other steps/connections.

One thing to watch out for is ensuring that the flow view can still be navigated *after* a step or connection has been configured, i.e. I set up a log step, then decide to look at the config for the start connection, I should still in this case be able to click on the log step and look at the configuration for that.

Perhaps the trash icons shouldn't be available for steps/connections except on the 'save-or-add-step' page?  @syndesisio/design-ux WDYT?

**Comment by sjcox-rh** [comment]
Stan, this all sounds good. When you are configuring a step of connection, clicking through the integration visualization panel should be disabled until configuration is done for each step/connection.

Also, I like the idea of only showing the trash icons on the add page.

**Comment by gashcrumb** [comment]
@sjcox-rh great, thanks!

**Comment by gashcrumb** [comment]
Introducing a cancel button that gets you back to the save-or-add-step page might be necessary once this is implemented, will look at how feasible that is.

**Comment by gashcrumb** [comment]
So the linked PR ensures the user can't click out of a flow of pages if the step/connection hasn't been completed.  I also hide the trash icons when the user is in a step or connection.  When a step or connection has been previously completed the user can still use the visualization to navigate through the integration.
