### ISSUE TITLE
Editing integration: No '+' anymore when step was selected

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#702]
When going to the 'Edit integration' screen, it starts with:

![image](https://user-images.githubusercontent.com/99080/28770785-b91c9c80-75e0-11e7-8847-0bf0f955f43b.png)

So you can add steps here via the '+' icon. However, when you select to edit an already existing step, the display changes to:

![image](https://user-images.githubusercontent.com/99080/28770811-d6583b74-75e0-11e7-90ed-c989a538bb7d.png)

When finished with the edit, there is no way back to add a new step. The only path is to go back to the Dashboard / Integration listing, and select the integration again.

From an UX perspective, this is not optimal and confusing.

**Comment by gashcrumb** [comment]
Scroll the view to the right a bit, the next button is off of the screen at the moment

**Comment by gashcrumb** [comment]
Really it's due to the workaround for https://github.com/syndesisio/syndesis-ui/issues/638 have to check if the patternfly update was published today...

**Comment by rhuss** [comment]
Ah, ok. Sorry for the noise ...
