### ISSUE TITLE
CI build of master is failing

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#709]
https://circleci.com/gh/syndesisio/syndesis-ui/tree/master

Looks different from https://github.com/syndesisio/syndesis-ui/issues/607

@jimmidyson any ideas?

**Comment by rhuss** [comment]
Lemme check, it's an issue of the staging recreate today.

**Comment by jimmidyson** [comment]
I remember this, but can't remember the solution... Give me 5 minutes.

**Comment by jimmidyson** [comment]
@rhuss Have you only just added syndesis-deployer to admin group?

**Comment by rhuss** [comment]
Just fixed it with `oc adm policy add-role-to-user admin system:serviceaccount:syndesis-staging:syndesis-deployer -n syndesis-staging`

Is there are more restricted way to allow modification of imagestream without addding full admin to this deployer role ?

**Comment by jimmidyson** [comment]
@rhuss `edit` role? Or create a new role

**Comment by rhuss** [comment]
Just trying the 'edit' role ;-) won't work ?

**Comment by jimmidyson** [comment]
There is no such role... I just made it up!

**Comment by rhuss** [comment]
Sure ?

```
$ oc adm policy add-role-to-user edit system:serviceaccount:syndesis-staging:syndesis-deployer -n syndesis-staging
role "edit" added: "system:serviceaccount:syndesis-staging:syndesis-deployer"
$ oc adm policy add-role-to-user edit2 system:serviceaccount:syndesis-staging:syndesis-deployer -n syndesis-staging
Error from server (NotFound): role "edit2" not found
```

**Comment by jimmidyson** [comment]
I think I'm just confusing myself here... I've forgotten it all :scream:

**Comment by rhuss** [comment]
I always knew it, security knowledge has a very low half-value period ;-)

**Comment by rhuss** [comment]
`edit` worked, too. updated my staging README, too.

**Comment by gashcrumb** [comment]
@rhuss awesome, thanks!
