### ISSUE TITLE
Use precomputed java inspection when available.

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-ui#712]
Once the following PRs get merged: 
https://github.com/syndesisio/syndesis-rest/pull/481
https://github.com/syndesisio/syndesis-openshift-templates/pull/65

the syndesis rest api will support get precomputed java inspection at the following API endpoint:
`GET /mapper/v1/java-inspections/{connector_id}/{java_class_name}.json`

404 will be returned if a precomputed inspection is not available. 

The UI should feed these precomputed inspection into the datamapper when available.

**Comment by chirino** [comment]
See: https://github.com/atlasmap/atlasmap-ui/issues/51 for info on how to pass the precomuted inspection into the datamapper.

**Comment by chirino** [comment]
PRs merged and service is available on staging.  Example endpoint:

`https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/mapper/v1/java-inspections/twitter/twitter4j.Status.json`

**Comment by gashcrumb** [comment]
Let's see if we can get this in place by the end of this sprint perhaps?

**Comment by rhuss** [comment]
Actually I really believe that its already available (somehow). The pom.xml which is retrieved was syndesis-rest was feed to atlasmap-ui which then called out to Maven previously. This for sure doesnt' happen anymore, or ? So fetching the pom.xml is useless imo, but I need someone to verify this.

**Comment by igarashitm** [comment]
Just to record I found, the integration POM was supposed to be used for java inspection, for the class which is not in the atlasmap runtime classpath. Right now we have all the syndesis connectors in atlasmap spring-boot runtime dependencies, which should be removed at some point. This is why it's working without maven classpath right now. One of maven classpath or binary upload (required for custom connector) will be eventually needed when we remove connectors from atlasmap runtime classpath. Or rely on precomputed inspection via maven and completely disable on demand java inspection.
