### ISSUE TITLE
UI HTTP URI lost during redirections

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-ui#716]
I can copy paste urls like:
* https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/integrations
* https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/settings/oauth-clients

and paste them into new browser window but I always end up on dashboard

**Comment by jimmidyson** [comment]
Yeah this looks like caddy doing a redirect rather than sending back the default page... Let me take a look.

**Comment by jimmidyson** [comment]
Fixed in #718
