### ISSUE TITLE
Add tooltip to datamapper navbar

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-ui#724]
![tooltip.png](https://images.zenhubusercontent.com/5939117e51aa2c305780da73/ccb69c83-d2ef-4d07-b321-b981b1785e24)

please keep in mind also support for e2e tests - we need to be able to select this "buttons" somehow

**Comment by gashcrumb** [comment]
With https://github.com/atlasmap/atlasmap-ui/pull/72 merged this can be marked fix after one of us opens a PR that updates the commit SHA

@igarashitm do you have updates to the data mapper you're looking to get in soon?

**Comment by igarashitm** [comment]
Nope, I don't have UI update right now, please go ahead!
