### ISSUE TITLE
Create button placement Integration vs. Connection

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#736]
#Create Integration button is still aligned to right edge of page, but Create Connection is grouped with filter and aligned right.

Probably cause by placement to div `toolbar-actions.pfng-action` vs. `toolbar-pf-action-right`.

![screen shot 2017-08-07 at 09 20 09](https://user-images.githubusercontent.com/5637792/29016206-b762c150-7b51-11e7-9e47-3ceae55a3acd.png)

![screen shot 2017-08-07 at 09 20 17](https://user-images.githubusercontent.com/5637792/29016208-ba16add0-7b51-11e7-8568-238f958444cd.png)

**Comment by dsimansk** [comment]
Probably related to https://github.com/syndesisio/syndesis-ui/pull/732, @astefanutti wdyt?

**Comment by astefanutti** [comment]
@dsimansk that is indeed a consequence of #732. It follows the default PatternFly component layout where action buttons are placed right after the sort group, while the right aligned group is meant for the view selection buttons.

I'm working on updating the integrations toolbar accordingly, hence the current discrepancy.

**Comment by gashcrumb** [comment]
@astefanutti mind if I assign this to you?  Thanks!

**Comment by astefanutti** [comment]
@gashcrumb was about to 😉

**Comment by astefanutti** [comment]
Fixed at 4130f88fa256a8ae69f193eb0ad5027e4235754d.
