### ISSUE TITLE
Missing Publish button when creating integration

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#737]
Currently I can only see `Save` button that just saves as draft but no way to `Publish`.

![screen shot 2017-08-07 at 10 13 09](https://user-images.githubusercontent.com/5637792/29017875-0aefb736-7b59-11e7-9379-cc9e1e6c54a0.png)

**Comment by gashcrumb** [comment]
Ah, of course, `save and publish` is only on the name/description page.  Let me add it to this page too.
