### ISSUE TITLE
Pull out "insert step/connection popover" into separate component

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#765]
Right here -> https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/edit-page/flow-view/flow-view.component.html#L24-L50

the code is also duplicated here -> https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/edit-page/flow-view/flow-view.component.html#L60-L86

**Comment by akieling** [comment]
We could contribute a popover to PatternFly NG and use it when available.

**Comment by gashcrumb** [comment]
I think this issue is less necessary now that the view has been refactored, there's no longer any duplicated code.  Also for the actual popover we're using the ngx-bootstrap one.  So I think this actually can be closed.

**Comment by akieling** [comment]
Yep, I think it can be closed.
