### ISSUE TITLE
Usability issue when adding step/connection in visual representation of integration

### ISSUE THREAD

**Issue by akieling** [syndesisio/syndesis-ui#774]
In the visual representation of an integration (left-hand side of the page), when the user moves the mouse pointer over the plus sign, a tooltip with the 'Add a step" and "Add a connection" links shows up. When the user moves the mouse pointer to the right to click on one of the links, the tooltip disappears.

**Comment by rhuss** [comment]
have the same issue, but only since recently.

**Comment by gashcrumb** [comment]
@akieling ah, that's my fault, fixed the page to display properly on firefox too but added this side-effect.
