### ISSUE TITLE
Fetch integration detail page history

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#794]
Follow on from #786 the table showing the integrations history needs to be populated with data fetched from the backend.

Related to syndesisio/syndesis-project#22

Probably is going to need syndesisio/syndesis-rest#493

**Comment by gashcrumb** [comment]
@rhuss do we have an endpoint for this yet?

**Comment by rhuss** [comment]
@gashcrumb no, there is no endpoint yet. Still discussing with @iocanel on the general PR https://github.com/syndesisio/syndesis-rest/pull/493 but I'm afraid @iocanel is too busy right now. I'm going to jump on that next week so that I hope we can demo it at the end of the week.
