### ISSUE TITLE
Connect icon to edit integration description/name

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#795]
I added an icon on the detail page which could be used to toggle an edit field for the description, might also want one for the name, does nothing right now.

There's two options here, the icon could link to the 'integration-basics' page in the editor which has input fields for the name and the description.

Or the edit icon could toggle in-place editing of either field, much like the name can be edited in-place when you're in the editor.

Currently the way the page flow is working, you can't normally edit the description field unless you forget to enter a name, i.e. there's no direct link to the 'integration-basics' page currently, just a stop-gap that occurs if the user tries to save the integration but hasn't named it.

@dongniwang @sjcox-rh any opinion?  See screenshot in #792

**Comment by dongniwang** [comment]
Really like the toggle icon! 👍  And I vote for in-line editing for this icon.
