### ISSUE TITLE
'Create Connection' workflow: form fields already populated

### ISSUE THREAD

**Issue by akieling** [syndesisio/syndesis-ui#810]
The fields in step 3 of connection creation are showing information provided in the previous connection creation.

Steps to reproduce:
- Create a connection specifying name, description, and tags
- Create another connection. On step 3, you should see the connection details from previous connection

Expected behavior:
The connection details should always be empty on connection creation.

**Comment by kahboom** [comment]
Was able to replicate this issue. Thanks @akieling !
