### ISSUE TITLE
Connection description/tags not editable once they're created

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#819]
On the connection edit page you can only edit the connection parameters, you can't edit the name, description or tags.

An option might be to make use of the in-place editor widget I added for https://github.com/syndesisio/syndesis-ui/issues/795

**Comment by akieling** [comment]
@dongniwang @sjcox-rh Do you have any mockups/designs for editing connection name, description, and tags?

**Comment by dongniwang** [comment]
The "Edit" button on top right of the screen only controls the right panel. So my questions is, I'm fine with just using the in-place editor for Connection Name and Description. But when user clicks "Edit", should they see editable fields for Connection Name and Description?

**Comment by gashcrumb** [comment]
That'd be a nice way maybe to handle it, so assuming then the icons for editing the name/description/tags only show up when you click edit?  That sounds alright, at least sounds nicer than clicking 'Edit' and having every field on the page turn into a text input :-)

**Comment by gashcrumb** [comment]
I suppose if we change the name we also need to ensure it's validated, might need to implement #823 as part of this.

**Comment by akieling** [comment]
I'm not sure it will be clear to the user the Edit button on the top right corner only controls the right panel.

**Comment by akieling** [comment]
Unfortunately, the editable component doesn't support multiple values. I wonder if it makes sense changing it to support editing tags. Will the component used for tags be changed to a PatternFly component in the future?

**Comment by gashcrumb** [comment]
I was thinking for the tags we'd add support to the component to allow for passing in a custom template, then use the same tag input component that's being used on the 3rd page of the create connection wizard.

**Comment by gashcrumb** [comment]
@dongniwang After discussing this issue with @akieling we've come to the conclusion that the layout for the connection detail page makes this issue difficult to implement in a user-friendly fashion.

I propose we rework the layout of the connection detail page so it's layout is more like the integration detail page, i.e. something like:

### Name _(Icon in front of it maybe?)_
_tag1_ _tag2_ _tag3_

**Connection description here and stuff**

**form or oauth buttons here**

I think maybe have in-place editing for the name, tags and description, and then an edit button to show the form and validate control.  WDYT?

**Comment by dongniwang** [comment]
Hmmm, I see where you're coming from. The current connection details page is a legacy design from a while ago I believe. To be honest, I don't fully understand the design decision behind having a two-column layout. 

I agreed it would be great to keep these kinds of detail pages in a similar layout - just one column and more linear structure. 

@sjcox-rh, what do you think? If you're on board, we can come up with a design for this.

**Comment by gashcrumb** [comment]
We could probably stub this out quickly enough in the UI if you like, WDYT @akieling?

**Comment by dongniwang** [comment]
That works too, then maybe @sjcox-rh and I can review and give feedback via the staging site?

**Comment by gashcrumb** [comment]
sure!  We could put screenshots in the PR too, probably be the quickest...

**Comment by dongniwang** [comment]
sounds like a plan! 👍

**Comment by sjcox-rh** [comment]
@gashcrumb @dongniwang this all sounds good. If you just follow the template from the integrations details page then that should work Stan!

And what Dongni said, we'll be happy to review when it's done.

As far as why it the legacy design was designed as such, I think they wanted to show a preview of what the connection card would look like. Nice idea, but not completely necessary given the restrictions for editting.

**Comment by akieling** [comment]
@dongniwang do you think the Connection Fields form should stay as is and not have inline editing?

**Comment by dongniwang** [comment]
@akieling Are you talking about this form? see screenshot below. 
![image](https://user-images.githubusercontent.com/24943812/29879073-1092d242-8d72-11e7-90e2-4a8eb0abb58a.png)

My suggestion is to keep the form format for this section and do not apply inline editing. Because:

- It is likely that user would be editing at least two fields at the same time, e.g. updating consumer key and consumer secret at the same time. So it would make sense to just give them a form. My understanding is that they're a pair, please correct me if I'm wrong. 
- PatternFly suggests in-line edit is not for bulk action (http://www.patternfly.org/pattern-library/forms-and-controls/inline-edit/)

**Comment by akieling** [comment]
@dongniwang @gashcrumb Please have a look at the screenshots and let me know what you think.

![screenshot-localhost-4200-2017-09-04-08-21-02.png](https://images.zenhubusercontent.com/5975f9ca61b4ca3b0a75775d/12446ab1-9466-4358-97db-f852a3328c47)
![screenshot-localhost-4200-2017-09-04-08-23-43.png](https://images.zenhubusercontent.com/5975f9ca61b4ca3b0a75775d/a5a31379-75d5-4437-9c47-a6ca3ff94631)

**Comment by gashcrumb** [comment]
@akieling no worries.  I think we can close this issue and just raise new issues for any changes required, make sense?

**Comment by dongniwang** [comment]
@akieling Great work! Thanks for making the updates. I do have two nitpicking suggestions. Please see screenshots below. 

![connection details page](https://user-images.githubusercontent.com/24943812/30075487-9dd3ec56-9243-11e7-8317-cf92c07f3773.png)
