### ISSUE TITLE
Edit Integration: Only Action name is shown for endpoints

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#821]
For the endpoints there is only the action name shown in the overview:

![image](https://user-images.githubusercontent.com/99080/29618749-6bc1124a-8819-11e7-9056-f0ba7d30c105.png)

Even when choosing the endpoint the connection name never shows up.

However, these are normally generic names which are not unique. Instead, I would expect here some combination of connection + action name as the connection name ("Twitter Demo") is provided by the user (maybe something like "Twitter Demo - Mention", or two lines with "Twitter Demo" and "Mention".

**Comment by gashcrumb** [comment]
Connection name is shown in a tooltip.

One problem with showing both is it can get pretty lengthy especially with user-supplied values, i.e. `My Twitter Connection - Mention`.  So maybe the design needs a little revisit.

Also, food for thought, imagine if we ever localize this app, how would this look in German?

@dongniwang @sjcox-rh FYI

**Comment by dongniwang** [comment]
Showing both connection name and action can certainly make things really lengthy. I think that's why right now there's Logo + Connection Name on tooltip, then the action is shown in the gray box. 

> Also, food for thought, imagine if we ever localize this app, how would this look in German?

Haha, what about Chinese and Japanese (with square shape looking characters)? ;)

**Comment by gashcrumb** [comment]
>Haha, what about Chinese and Japanese (with square shape looking characters)? ;)

Exactly!  :-)

**Comment by gashcrumb** [comment]
So the question then is do we think the tooltip is enough or should we make connections have 2 lines.  Was hoping to knock out an example to get a screenshot but the styling is a bit dicey in that part of the page :-(

**Comment by rhuss** [comment]
Actually I find the name of the connection more informative as the action name (which can get lengthy as well). Its also the connection which is chosen first by a user and the user can choose a name freely (so has influence on what is shown)

However if we assume that there is usually only a single connection configured of a certain type, than probably the icon alone is enough.

BTW I tried to get to the hover over tooltip, but failed for me.

Maybe a compromise would be to show the connection name on the right side when the step is selected ?

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gashcrumb** [comment]
suppose also tooltips only work for desktops, no way to 'hover' on a tablet/touch device...

**Comment by dongniwang** [comment]
So tooltip also didn't show up when I hover over the connection circle...

> Maybe a compromise would be to show the connection name on the right side when the step is selected ?

What do you mean by this @rhuss

**Comment by rhuss** [comment]
I mean, when I select the endpoint step (twitter or salesforce) the connection name is also not show in the details page on the right side. I suppose there would be enough Screen real estate to put the full name (connection + action) somewhere

![image](https://user-images.githubusercontent.com/99080/29659577-0583b360-88bf-11e7-8b29-2e45b15ebf80.png)

**Comment by gashcrumb** [comment]
Ah, absolutely, thanks for clarifying...  Let me add that in.

**Comment by gashcrumb** [comment]
Screenshots in the linked PR...
