### ISSUE TITLE
editable.component.ts should support validation

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#823]
To support stuff like https://github.com/syndesisio/syndesis-ui/issues/818

**Comment by akieling** [comment]
Shall we add another input attribute that takes a validation function? The validation function would return an error message or null.

**Comment by gashcrumb** [comment]
Yeah, that'd make sense.  Might also want to support returning a Promise or Observable too so it's easy to do server-side validation.
