### ISSUE TITLE
No step can be added after another step

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#824]
When trying to add a step _after_ another step via the + sign:

![image](https://user-images.githubusercontent.com/99080/29620698-ef744ac6-881e-11e7-892c-b02926e48a31.png)

its created _before_ this step:

![image](https://user-images.githubusercontent.com/99080/29620722-0093a9e6-881f-11e7-871e-10f0919e5301.png)

Its should be inserted right after it, though.

**Comment by gashcrumb** [comment]
I very well could have broken that :-)
