### ISSUE TITLE
Integration list toolbar should be fixed position

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#834]
Right now it scrolls with the page, but I think it should be fixed.  Not sure on the tabs, perhaps that shouldn't scroll off the page either.

@dongniwang @sjcox-rh ?

**Comment by gashcrumb** [comment]
Same goes for the connection list page, could raise a separate issue but probably a similar fix

**Comment by gashcrumb** [comment]
Assuming the same for the integration detail page actually as well, that one scrolls when it probably shouldn't?

**Comment by dongniwang** [comment]
See screenshot below for reference. 

I think area 1 - toolbar should be fixed position. But not sure about area 2 either...based on the current design, it feels weird if the tabs are fixed...

Another related question, i thought the **Create Integration** would be on the far right, or maybe that was one of the old designs? 

![image](https://user-images.githubusercontent.com/24943812/29718768-d1238654-8981-11e7-9e4f-c14368268f9d.png)

**Comment by gashcrumb** [comment]
Think there's another issue open for the button., will check after the standup

**Comment by gashcrumb** [comment]
Ah, doesn't look like it, let me create one...

**Comment by gashcrumb** [comment]
Yep, those button locations moved when we switched to the patternfly angular2 component, just needs a tweak to get them back to the right spot.

**Comment by gashcrumb** [comment]
Also, I agree if the tabs were fixed it'd look weird.  Also I think that wastes a lot of screen real estate.

**Comment by astefanutti** [comment]
Indeed the create button follows the patternfly-ng toolbar component design. It can be moved to the right into what's supposed to be the view selection section. 

For the tabs, I was actually thinking we could just integrate the state filtering as another filter into the toolbar. Now that we use the toolbar component, that's easy to add the state filter, that would save screen estate, and be consistent from a UX standpoint.

**Comment by gashcrumb** [comment]
That seems reasonable.  BTW, opened a PR that moves the buttons into the view section if you want to review...

**Comment by gashcrumb** [comment]
Let's create a new issue for the state filtering I think...
