### ISSUE TITLE
Only first step on integration can be deleted

### ISSUE THREAD

**Issue by lvydra** [syndesisio/syndesis-ui#840]
If you have more then one step on integration only the first one can be deleted.

**Comment by gashcrumb** [comment]
I can't seem to reproduce this locally but did come across another bug, is your version running against the most recent commit SHA?

**Comment by lvydra** [comment]
Have you tried to create a new integration with multiple steps?

**Comment by gashcrumb** [comment]
Yup, however there does seem to be a problem sometimes with the modal, but for example:

before deleting the 'store data' step:

![screen shot 2017-08-28 at 10 42 15](https://user-images.githubusercontent.com/351660/29778560-cfee2d62-8bdd-11e7-91dc-b2ccebd233a1.png)

After:

![screen shot 2017-08-28 at 10 42 35](https://user-images.githubusercontent.com/351660/29778565-d59341a8-8bdd-11e7-8f69-e0e1e271686c.png)

**Comment by gashcrumb** [comment]
Ah, or is that the issue, i.e. this error in the javascript console:

```
ERROR TypeError: modal is undefined
Stack trace:
[215]/ModalService.prototype.show@https://localhost:4200/main.bundle.js:400:9
[1346]/FlowViewStepComponent.prototype.deletePrompt@https://localhost:4200/1.chunk.js:4321:9
View_FlowViewStepComponent_16/<@ng:///IntegrationsModule/FlowViewStepComponent.ngfactory.js:490:21
handleEvent@https://localhost:4200/vendor.bundle.js:12103:98
callWithDebugContext@https://localhost:4200/vendor.bundle.js:13395:39
debugHandleEvent@https://localhost:4200/vendor.bundle.js:12983:12
dispatchEvent@https://localhost:4200/vendor.bundle.js:9003:12
renderEventHandlerClosure/<@https://localhost:4200/vendor.bundle.js:9595:20
decoratePreventDefault/<@https://localhost:4200/vendor.bundle.js:52479:53
ZoneDelegate.prototype.invokeTask@https://localhost:4200/polyfills.bundle.js:5989:17
onInvokeTask@https://localhost:4200/vendor.bundle.js:4330:28
ZoneDelegate.prototype.invokeTask@https://localhost:4200/polyfills.bundle.js:5988:17
Zone.prototype.runTask@https://localhost:4200/polyfills.bundle.js:5756:28
ZoneTask/this.invoke@https://localhost:4200/polyfills.bundle.js:6051:28
```

'cause I'm definitely seeing that one :-)

**Comment by lvydra** [comment]
I got this one
`ERROR TypeError: n is undefined
Stack trace:
.p9rx/u</l.prototype.show@https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/main.3f2f672c9e03580227bb.bundle.js:1:268265
["9TWe"]/s</l.prototype.deletePrompt@https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/1.d3d5f02441245d97530b.chunk.js:1:71745
m/<@https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/1.d3d5f02441245d97530b.chunk.js:1:35464
Ln/_@https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/vendor.940b09417750af08933c.bundle.js:260:1448
ar/<.handleEvent@https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/vendor.940b09417750af08933c.bundle.js:260:8473
$t@https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/vendor.940b09417750af08933c.bundle.js:211:1741
Se/<@https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/vendor.940b09417750af08933c.bundle.js:218:2363
m/<@https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/vendor.940b09417750af08933c.bundle.js:645:764
.ZSR1/</</E</F</t.prototype.invokeTask@https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/polyfills.963faf392a3eda1d3019.bundle.js:36:10887
["3j3K"]/</Ki</t.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvokeTask@https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/vendor.940b09417750af08933c.bundle.js:316:8008
.ZSR1/</</E</F</t.prototype.invokeTask@https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/polyfills.963faf392a3eda1d3019.bundle.js:36:10800
.ZSR1/</</E</E</n.prototype.runTask@https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/polyfills.963faf392a3eda1d3019.bundle.js:36:6056
t/this.invoke@https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/polyfills.963faf392a3eda1d3019.bundle.js:36:11848`

**Comment by gashcrumb** [comment]
Okay cool, so that's the issue, will look into it, thanks!

**Comment by gashcrumb** [comment]
@astefanutti any ideas on this one?  This occurs because the modal IDs get set when the step components are created, when you delete a step the page doesn't fully redraw I guess, so the modal service's map of id -> modal gets inconsistent.

**Comment by gashcrumb** [comment]
Found it, the modal has the ID passed in, but it can change, so just need to enhance the modal component to deal with changes to the ID and ensure change detection is triggered whenever the step array changes.
