### ISSUE TITLE
Add a query parameter 'position' when fetching filter options or send outputDataShape

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#855]
For extracting the possible options for the filter in the BasicFilter, the endpoint `/integrations/filter/options` is called with the current to be defined integration in the POST body.

In order to determine the latest outputShape of the integration, the position of the current filter step within the integration should be sent as a query parameter `position` (where the position is the position is the position the filter step will take).

Alternatively, we could let the UI extract the latest outputShape in the current integration which is part of the latest `action` value before the filter step and only send this outputShape as post payload to the endpoint. Tbh, from a separation-of-concern POV I'd prefer this approach so that the backend only serves what is requested (without deeper logic and might be more easily reused as the datashape is much simpler to send than the whole integration). But I'm fine with either approach.

wdyt, @gashcrumb ?

**Comment by gashcrumb** [comment]
We do have some code in the current-flow service that the views use that grabs the previous and subsequent connections for figuring out input and output data shapes on the UI side:

https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/edit-page/current-flow.service.ts#L144-L150

and

https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/edit-page/current-flow.service.ts#L177-L183

**Comment by rhuss** [comment]
This would be awesome if we can change to the dataShape only (the outputDataShape from the closest action before the filter step). The backend change is trivial just let me know when this is available.
