### ISSUE TITLE
OAuth flow with Twitter is broken.

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#857]
When doing an oauth handshake with Twitter and Twitter redirects to the connection create wizard, the button "Connect Twitter" is still active.

* Pressing "Next" leads back to the initial connector select page.
* Connecting again leads to the same effect.
* Removing the "-cred.." cookie does not help
* Nothing suspicious in the Java console nor network tab.

@gashcrumb @zregvart : Any ideas how to continue to debug ?

**Comment by rhuss** [comment]
I'm stuck at that page:

![image](https://user-images.githubusercontent.com/99080/29816286-d2c09526-8cb3-11e7-94cc-3449877bd3a3.png)

**Comment by rhuss** [comment]
Same for Salesforce

![image](https://user-images.githubusercontent.com/99080/29816312-ec306658-8cb3-11e7-9150-35fddb9b2469.png)

**Comment by rhuss** [comment]
On syndesis-rest I see a 

```
2017-08-29 10:19:18.660  WARN [-,fe672e60f2df6484,fe672e60f2df6484,false] 1 --- [  XNIO-3 task-7] o.a.h.c.protocol.ResponseProcessCookies  : Invalid cookie header: "set-cookie: personalization_id="v1_p0bcHhNQO+H7wwZKMKqj6Q=="; Expires=Thu, 29 Aug 2019 10:19:18 UTC; Path=/; Domain=.twitter.com". Invalid 'expires' attribute: Thu, 29 Aug 2019 10:19:18 UTC
2017-08-29 10:19:18.660  WARN [-,fe672e60f2df6484,fe672e60f2df6484,false] 1 --- [  XNIO-3 task-7] o.a.h.c.protocol.ResponseProcessCookies  : Invalid cookie header: "set-cookie: guest_id=v1%3A150400195856254879; Expires=Thu, 29 Aug 2019 10:19:18 UTC; Path=/; Domain=.twitter.com". Invalid 'expires' attribute: Thu, 29 Aug 2019 10:19:18 UTC
2017-08-29 10:19:36.417  WARN [-,52aceb900b917a0e,52aceb900b917a0e,false] 1 --- [  XNIO-3 task-8] o.a.h.c.protocol.ResponseProcessCookies  : Invalid cookie header: "set-cookie: personalization_id="v1_Mu0R2q6NRX62BdpWWfqD+w=="; Expires=Thu, 29 Aug 2019 10:19:36 UTC; Path=/; Domain=.twitter.com". Invalid 'expires' attribute: Thu, 29 Aug 2019 10:19:36 UTC
2017-08-29 10:19:36.417  WARN [-,52aceb900b917a0e,52aceb900b917a0e,false] 1 --- [  XNIO-3 task-8] o.a.h.c.protocol.ResponseProcessCookies  : Invalid cookie header: "set-cookie: guest_id=v1%3A150400197629599303; Expires=Thu, 29 Aug 2019 10:19:36 UTC; Path=/; Domain=.twitter.com". Invalid 'expires' attribute: Thu, 29 Aug 2019 10:19:36 UTC
```

**Comment by rhuss** [comment]
@gashcrumb sorry, this still does not work for me (neither on staging)

**Comment by rhuss** [comment]
The behaviour is unchanged.

**Comment by gashcrumb** [comment]
Are you sure staging has been updated recently?  Just tried it again here
and it works for me.  Note you have to click 'Next' until #771 is fixed
which requires some backend work as well.

**Comment by rhuss** [comment]
It was updated 7 hours ago, right after the PR to #865 was merged. Its still then when I press "Next" then I got thrown back to the connector selection. I tried it on https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/ but also on a local minishift installation where I installed syndesis-ui directly from master.

**Comment by rhuss** [comment]
Whats really strange that the callback directly lead to the page without the button (as it was last week).  You had to press "Next" to finish the connection, that's ok.

Now it mostly first leads to this page with a _immediate_ replacement of this side with the page with a button. You can see how the later page replaces the former. When you now press "Next" you get not to the page for entering the connection name but back to the connector selector screen (step 1).

**Comment by rhuss** [comment]
Actually syndesis-ui is rebuild and will be available on stages in minutes.

**Comment by gashcrumb** [comment]
hmm -> https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/connections/-Ksp-DM8Hmqk37SqB2e2

**Comment by gashcrumb** [comment]
clear your cache?  seems odd that'd it'd still misbehave, the redirect back to the connector select screen was due to a bad merge it turns out...

**Comment by rhuss** [comment]
![image](https://user-images.githubusercontent.com/99080/29895607-0bf7e084-8dda-11e7-917b-099fb228ce26.png)

will try now again in an incognito window ...

**Comment by rhuss** [comment]
with cleared cache ...

**Comment by rhuss** [comment]
still no luck (even with a different browser). Could you please try it yourself at https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/connections ? Select twitter, and then do the oauth dance.

**Comment by rhuss** [comment]
Sorry you have to go to  https://syndesis-staging.b6ff.rh-idev.openshiftapps.com/ , then select connnections, "New connection" ...

No deep linking possible yet (i think)

**Comment by gashcrumb** [comment]
Yeah, I've made 4 twitter connections on staging so far, one from dev and the other 3 from staging.

**Comment by zregvart** [comment]
I've just created a Twitter connection on staging, the only thing is that I was presented with _Connect to Twitter_ button after callback. But clicking _Next_ I could name and save the connection. On Firefox 52.2.0 in incognito.

**Comment by rhuss** [comment]
I tried it now with staging, and it works, too (but still have this small flicker with the "no properties to configure page coming first", overlaid/exchanged immediately with the "Connect to Twitter" button. When I press now next, I can name the the connection.

However, when I do the same on my local, yarn started, syndesis-ui instance, I end up with 

![image](https://user-images.githubusercontent.com/99080/29907199-40702c0a-8e1a-11e7-9162-9c7ea2d11255.png)

after the callback. When I press "Next" here I'm back at

![image](https://user-images.githubusercontent.com/99080/29907212-57176cb6-8e1a-11e7-97f7-73b0d3e0a727.png)

when I now select "Twitter" here, do the oauth dance again, then:

![image](https://user-images.githubusercontent.com/99080/29907254-8ca8cac8-8e1a-11e7-91d2-cc8e26757ac2.png)

"Next" brings again back to the connector selector page.

------

I can create a connection here though by doing these steps:

* New connection
* Select Twitter
* Do OAuth Dance
* "Next"
* Select Twitter again
* **Don't** do the OAuth dance again, but press "Next" directly
* Enter connection name & description
* Press "Create"

This will take over the access token from the first OAuth flow.

-----

All this with a freshly started Chrome, incognito window and

![image](https://user-images.githubusercontent.com/99080/29907226-6b6dead2-8e1a-11e7-941f-cdee9eaef2bc.png)

**Comment by rhuss** [comment]
Also:

* I did a fresh git rebase on `master` in syndesis-ui first
* `yarn clean`
* Removed all cookies to https://localhost:4200

Sorry if this all sounds desperate, but I am.

**Comment by rhuss** [comment]
Darn! I knew it must be something simple. My git rebase didn't worked really. Now all is good (except that flicker and the 'Connect Button' being still there

Good start in the pre-demo day ;-(

Sorry for all the noise ...
