### ISSUE TITLE
Add JSON schema support for the datamapper source/target document

### ISSUE THREAD

**Issue by igarashitm** [syndesisio/syndesis-ui#861]

**Comment by igarashitm** [comment]
The first commit attached here is just adding an entry point for the JSON schema, nothing else. Let's start here.

datamapper initializes the source/target document here from their DataShape 
https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts#L184-L201

Right now it doesn't even load nor put the content into createDocumentDefinition(), so only java is allowed for DataShape.type. In order to support JSON schema, we need to load the JSON schema from somewhere, and pass it along.

**Comment by gashcrumb** [comment]
Is this related to https://github.com/syndesisio/syndesis-ui/issues/606 by any chance?

**Comment by igarashitm** [comment]
It looks like so, and it's a datamapper part of the syndesisio/syndesis-project#14. Retrieve a JSON schema from component metadata and pass it into the atlasmap.

**Comment by igarashitm** [comment]
JSON schema inspection in atlasmap has been implemented here - https://github.com/atlasmap/atlasmap/issues/153

**Comment by igarashitm** [comment]
if DataShape.kind == json-instance || json-schema || xml-instance || xml-schema
then we need a content. We'll need a extra key in the DataShape to indicate where the metadata can be retrieved.
https://github.com/igarashitm/syndesis-ui/blob/77e81e1d37689d7fbdb08bff57eae3a41a55f309/src/app/integrations/edit-page/step-configure/data-mapper/data-mapper-host.component.ts#L164-L175
