### ISSUE TITLE
Fixed toolbars and breadcrumbs

### ISSUE THREAD

**Issue by astefanutti** [syndesisio/syndesis-ui#867]
Now that we have fixed toolbars for connections and integrations lists with #859, I wonder whether that'd make sense for other places to be consistent?

Integration details:
<img width="872" alt="screen shot 2017-08-30 at 15 26 57" src="https://user-images.githubusercontent.com/366207/29874700-df080604-8d97-11e7-9905-bf66c1b360d5.png">

Connection details:
<img width="872" alt="screen shot 2017-08-30 at 15 27 21" src="https://user-images.githubusercontent.com/366207/29874703-df330b6a-8d97-11e7-9bd3-ca180dd47e2b.png">

Settings:
<img width="869" alt="screen shot 2017-08-30 at 15 27 41" src="https://user-images.githubusercontent.com/366207/29874702-df3217d2-8d97-11e7-8614-2fffc7c30cea.png">

New integration:
<img width="732" alt="screen shot 2017-08-30 at 15 28 02" src="https://user-images.githubusercontent.com/366207/29874701-df280a76-8d97-11e7-92ec-9b40920d7c74.png">

**Comment by astefanutti** [comment]
@syndesisio/design-ux WDYT?

**Comment by gashcrumb** [comment]
+1 from me, only not sure about the settings page, that's how the design was.  But it'd be nice.

**Comment by dongniwang** [comment]
Haha, thanks @astefanutti for including all the screenshots! It made me realize we have some inconsistency going on with the use of white and gray... especially looking at the toolbar and breadcrumb...

So, here's my suggestion (Red box is the fixed area):

**Integration details:**
![image](https://user-images.githubusercontent.com/24943812/29879836-3931aae6-8d74-11e7-98d2-6d55dab4f0cf.png)

**Connection details:**
![image](https://user-images.githubusercontent.com/24943812/29879895-63e04720-8d74-11e7-9268-d1d2cd2bb8f4.png)

**New integration - choose a connection:**
Assuming we'll have many more connections in the future, so it's helpful to always have access to the filter/sorting toolbar.
![image](https://user-images.githubusercontent.com/24943812/29879946-8478b846-8d74-11e7-9b44-66f7e647b7ea.png)

**Global settings:**
My initial feedback would be to keep only the tab area fixed, so when user goes to another tab, they can tell the title and description changing..but I also see the need for having the filter/sorting toolbar fixed, then the question becomes - how many applications are we expecting to see here? 
![image](https://user-images.githubusercontent.com/24943812/29880219-390feeaa-8d75-11e7-9b20-709470e07c31.png)

**Comment by sjcox-rh** [comment]
@dongniwang I agree with all your suggestions, except im torn on having the filter tools part of the fixed area. 

My main concern is that since the filter tools aren't on every page of the create integration workflow, the fixed area would change from step to step. I feel like it would be best to keep it consistent across the app.

Unless this is easy to implement different fixed areas from screen to screen then ignore me :] @gashcrumb @kahboom @astefanutti 

Also, would it be possible to make sure all toolbar areas are the same bg color? I noticed the connection details page is white. Can we address that with this issue or should I create another one?

Thanks!

**Comment by astefanutti** [comment]
@sjcox-rh it should be quite easy to implement different fixed areas. So we could just have the breadcrumb included in the fixed area for the create integration workflow.

That may be better anyway in other situations, like the create connection view, where that would lead to too much fixed screen estate:

<img width="1067" alt="screen shot 2017-08-31 at 10 48 42" src="https://user-images.githubusercontent.com/366207/29914766-0350a046-8e3a-11e7-8058-e7c4cd99ac2a.png">

The only downside is that there is no breadcrumbs in the connections and integrations lists view, so the toolbars are fixed in that case, which may be a little inconsistent.

**Comment by astefanutti** [comment]
@sjcox-rh forgot to answer for the background color... Don't bother creating a new issue, I'll fixed that in the same time.

**Comment by dongniwang** [comment]
@astefanutti - Breadcrumbs on both the Connection Details page and Global Settings page should be gray. 

cc: @akieling @gashcrumb 

![image](https://user-images.githubusercontent.com/24943812/30073857-626dafe0-923d-11e7-8020-dfac156290e5.png)

![image](https://user-images.githubusercontent.com/24943812/30073892-7a482c80-923d-11e7-9873-b6a0d748e771.png)

**Comment by astefanutti** [comment]
Should be fixed at HEAD revision.
