### ISSUE TITLE
Migrate 'properties' in configure-actions to definitions/propertyDefinitionSteps

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#868]

**Comment by gashcrumb** [comment]
@zregvart I wonder, for this we need to be able to potentially re-create the set of pages related to configuring an endpoint in the integration when the user goes into the editor.  Is it worth maybe decorating the action as it shows up in the step array in the integration?  Otherwise the editor is going to need to fetch that data individually I guess for each connection in the integration I think.

**Comment by zregvart** [comment]
@gashcrumb not sure how the action is set on the integration step, but we could make sure that it holds the same action with definition as the one from connector/connection, would that help? Or if I'm understanding correctly defining property definition steps on integration steps (that's a mouthful) could be a better option.
And we we could add an endpoint for dynamic property values for integration action steps also (something like `/api/v1/integrations/{integrationId}/steps/{stepIdx}/properties`.

**Comment by rhuss** [comment]
A connection does not hold the Action, only the Connector. The action is the _class_ holding the the property definitions. The integration steps hold the action values (filled in data), but could replicate the property definitions, too (or the whole action).

@zregvart isn't it also necessary to add the values from previously created steps here so that the endpoint can create the property definitions steps depending on selected values ?

**Comment by zregvart** [comment]
> A connection does not hold the Action, only the Connector. The action is the class holding the the property definitions. The integration steps hold the action values (filled in data), but could replicate the property definitions, too (or the whole action).

(Just for completeness) One caveat to this is that for dynamic properties we need to tie the action to a connection in order to determine values of properties.

> @zregvart isn't it also necessary to add the values from previously created steps here so that the endpoint can create the property definitions steps depending on selected values ?

I'm not at all sold on the previous steps define next steps in action definitions, considering that connectors have actions with as narrow scope as we can make them.
Configured properties (the values) depend on the what's selected in previous steps, but I don't think we now have and, I can't think of an example where the selection of action properties changes depending on previous steps.

**Comment by rhuss** [comment]
@zregvart ok, I understood. But what I not yet understand is how the possible values (e.g. the possible id fields) get to the client when the custom object has been selected (these id fields are specific to the custom object, right ?). For me the 'possible values aka enum' is part of the property definition, the 'selected value' is then the actual value. But I likely misunderstood that.

**Comment by zregvart** [comment]
> @zregvart ok, I understood. But what I not yet understand is how the possible values (e.g. the possible id fields) get to the client when the custom object has been selected (these id fields are specific to the custom object, right ?). For me the 'possible values aka enum' is part of the property definition, the 'selected value' is then the actual value. But I likely misunderstood that.

The UI needs to send over the user supplied properties to the `/api/v1/connections/{connectionId}/actions/{actionId}/properties` (via GET) which in turn combines these with action property definitions (for any non specified, with `null` value) and connection properties. These aggregated properties are sent over to the _verifier_ that uses Camel Metadata extension for the specified connector to return any property values that can be specified.

So on first call there are no configured action properties, the _verifier_ will get only connection properties along with action properties having `null` values. Having called the Camel Metadata extension without specifying the object type (it's `null`) the metadata extension returns all object types (currently raw JSON, in future I think it's better to make it JSON schema), metadata adapter then looks at this and formats it to a list of value-display value pairs. When the UI receives this, user can pick the object type (step1), then in the next step the type of the object is defined (the action property for object type has value), and UI can call into that same endpoint with one query parameter specified. When this follows the same route to the metadata extension at that point it can reason that with the specified object type the caller is interested in specific object's schema, which it returns, metadata adapter transforms JSON schema taking the fields specified into a list of value-display value pairs, and with that returned to the UI, the UI can now offer the user the list of fields.

For SFDC adapter filters for id lookup fields if the action parameter name equals the action property that is used to determine uniqueness.

(HTH)

**Comment by zregvart** [comment]
Since we're doing this in the comments :) perhaps it wouldn't be such a bad idea for the metadata extension to return all JSON schema all the time and leave the smarts to the adapter in _verifier_.

**Comment by rhuss** [comment]
You mean the cartesian product of all combinations ? Isn't this too expensive wrt to querying salesforce ?

**Comment by zregvart** [comment]
Salesforce has two metadata operations (it's actually called metadata IIRC), one to fetch all and one to fetch single object's definition (we use both now). We could fetch all, cache, and perform computations on that to derive the combination we need.

**Comment by gashcrumb** [comment]
So yeah, currently the step object in the integration holds a reference to the connection and to the action.  So having the definition object in that action would be super-helpful, mostly when reloading an existing integration.

That being said I could probably also fetch this on-demand without a lot of hassle if the user happens to go to the action configure page.  

I also think generally if we can avoid referencing step positions in the integration in the API we'll be better off, best to keep the API agnostic of that, otherwise I foresee issues keeping the state of the integration synchronized between the frontend and backend.  Anyways, am still contemplating this one :-)

**Comment by gashcrumb** [comment]
@zregvart added a bit more support and am using the definition name/description now in the UI for menu items etc.

Wonder, it'd be handy if there was also an example/test connection/action that had a couple pages so I can tighten up navigation between pages etc.

**Comment by zregvart** [comment]
Yeah, I'll create one for Salesforce.

**Comment by gashcrumb** [comment]
This bit is done, new issue opened for the enum values and Zoran was nice enough to sort the data shape stuff :-)
