### ISSUE TITLE
Bogus Dialog when entering "Configure Connector" the first time

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#875]
Now when entering the configure dialog for a connection, the following dialog shows up:

![image](https://user-images.githubusercontent.com/99080/29964149-716999b4-8f09-11e7-8ccd-35d879615297.png)

Also, I'd like to remark that this step (2) should be called "Configure Connection", not "Configure Connector".

**Comment by gashcrumb** [comment]
Is this after the oauth page flow?  Given the message is the success message, I guess maybe the actual status field isn't 'SUCCESS' like the code is expecting but something different...

**Comment by gashcrumb** [comment]
It'd be awesome when you get a chance if you could capture the URL when on this page.

**Comment by rhuss** [comment]
![image](https://user-images.githubusercontent.com/99080/29987711-d293102a-8f69-11e7-9ea0-b9e098cc20ef.png)

It's for salesforce. Just tried to create a _second_ salesforce connection on OSO Pro (the demo).

**Comment by rhuss** [comment]
So, I pressed "New Connection" --> "Salesforce". Thats it. (but I already did a succesful creat connection before)

**Comment by gashcrumb** [comment]
@zregvart Wonder, can you reproduce this?  There's no salesforce account set up for staging currently...

Am wondering if it's due to having oauth set up once already, does that skip the whole oauth page flow then?

**Comment by zregvart** [comment]
I've configured Salesforce client id/secret on staging, I don't see that message ("Succesfilly authorized Syndesis's access") but the second step is named "Configure Connector" so I guess just that needs to be corrected.

**Comment by gashcrumb** [comment]
This issue regarding the titles was raised here -> https://github.com/syndesisio/syndesis-ux/issues/36

I'll raise a new issue for it in this repo so it can be tracked separately, also will double-check the behavior of the alert here as well.

**Comment by gashcrumb** [comment]
Raised #889 for the title changes...

**Comment by gashcrumb** [comment]
@zregvart thanks for setting that up BTW, can reproduce the issue now.  It seems to occur when you go and create a *second* salesforce connection.
