### ISSUE TITLE
Connection can be edited even when auth done via OAuth

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#877]
![image](https://user-images.githubusercontent.com/99080/29965664-d0054a54-8f0e-11e7-9955-1df721e9d0f8.png)

This page is reached via the pulldown menu on the connection itself. This is at least inconsistent to the way the connection is presented when clicking directly on it.

**Comment by rhuss** [comment]
![image](https://user-images.githubusercontent.com/99080/29965693-f62a588c-8f0e-11e7-82c7-641a14c9bc67.png)

**Comment by gashcrumb** [comment]
@akieling wonder, does this happen with the new connection detail page?

**Comment by gashcrumb** [comment]
Just checked, with the new detail page this is fixed.
