### ISSUE TITLE
align notifications position on settings page

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-ui#882]
CC @gashcrumb  @sjcox-rh 
![inline](https://user-images.githubusercontent.com/8707241/30018638-ee94a702-915d-11e7-918d-3ad590b21ec6.png)

![not-inline](https://user-images.githubusercontent.com/8707241/30018608-d86e3330-915d-11e7-90fd-c28f26c3d657.png)

**Comment by jludvice** [comment]
To be honest, I'd expect the sucess notification to appear on the top right corner,  
the same place where error notification shows up :)

Is there any reason to have success inside the form?

**Comment by gashcrumb** [comment]
Well, hence the UXD label :-)

**Comment by dongniwang** [comment]
@jludvice thanks for raising the issue. 

Although they are both notifications, they serve different purposes. 

The first one is [Inline Notifications ](http://www.patternfly.org/pattern-library/communication/inline-notifications/). We're using this within the form area to notify users whether they have successfully registered the OAuth apps. In this case, the notifications are specifically for the action of registration. 

The second one is a [Global Notification](http://www.patternfly.org/pattern-library/communication/toast-notifications/). This is to notify the user of a system occurrence. I consider deleting a registered OAuth app a system-wide action, which means this action affect not just the global settings page, but integrations that are using the OAuth app. This is why we're using the toast notifications for the delete behavior. 

Does this make sense? 

cc: @sjcox-rh

**Comment by akieling** [comment]
@dongniwang @sjcox-rh 
A few questions:
- Shouldn't the form be left aligned or centered?
- What about having just the primary action as a button and the secondary actions in a dropdown?
- The List View should expand when the list item is clicked, right? Do we need a button for that?
- When you click on 'Edit' to expand the list item and click on 'Save', we show a message saying the registration was successful. Shouldn't the button be called 'Register' instead of 'Save'?

**Comment by dongniwang** [comment]
@akieling 

- I think it would look nicer if the form aligns left (for responsive reason). 
- Are you talking about the "Register" "Edit" and "Delete" buttons? Hmm...I think it certainly looks cleaner if we only have one button, but have a secondary dropdown would ask users to perform an extra click to get to what they wanted to do. Also, we actually don't have that many buttons. @gashcrumb Any suggestions here?
-  Having the icon (down caret) on the far left is following the PF design for [list view](http://www.patternfly.org/pattern-library/content-views/list-view/#/design) . 
- If users are updating something in the future, then I think it wouldn't make sense to have "register". And in this case, do we want button to change to "Update"? Feels like Save is a more generic term here.

**Comment by jludvice** [comment]
ok, thanks for explanation @dongniwang 

I guess the notification position issue is resolved, isn't it ?

**Comment by gashcrumb** [comment]
Yes, I think so, we should create new issues to track any required changes beyond the notification positioning.
