### ISSUE TITLE
Can't type more than 1 letter into create connection form

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-ui#883]
After typing one letter into any input field the focus goes away from input.
Effectivelly I can't write credentials in

CC @dsimansk @lvydra @mmelko 
![create-connection](https://user-images.githubusercontent.com/8707241/30025767-4a20b0cc-917a-11e7-8eb1-56ea313c5a63.png)

**Comment by jludvice** [comment]
CC @akieling

**Comment by akieling** [comment]
@jludvice I'll have a look

**Comment by akieling** [comment]
@gashcrumb @kahboom 
Every time the user presses a key, we emit the updated connection:
https://github.com/syndesisio/syndesis-ui/blob/206644e9b786098d10865a9a2e1882496564de2d/src/app/connections/view/view.component.ts#L249
Which causes this method to be executed:
https://github.com/syndesisio/syndesis-ui/blob/206644e9b786098d10865a9a2e1882496564de2d/src/app/connections/create-page/current-connection.ts#L251
Which emits another event:
https://github.com/syndesisio/syndesis-ui/blob/206644e9b786098d10865a9a2e1882496564de2d/src/app/connections/create-page/current-connection.ts#L256-L259
Which causes this method to be executed:
https://github.com/syndesisio/syndesis-ui/blob/206644e9b786098d10865a9a2e1882496564de2d/src/app/connections/create-page/current-connection.ts#L108-L129
Where `connection-check-connector`, `connection-check-credentials`, and `connection-set-connection` events are triggered.
I'm confused. Why are we executing all this stuff on every key press?

**Comment by gashcrumb** [comment]
@akieling it's angular change detection on the form triggering the update with every individual change.  It'd probably be better to decouple the form from the connection object and use a `(blur)` event maybe to synchronize the user input?  Either that or just completely decouple it and update the connection object when the user clicks 'Next', that probably would make more sense actually.

**Comment by akieling** [comment]
OK, I'll change the code to only update the connection object when the user clicks 'Next'.
