### ISSUE TITLE
Reusable Filter w/ Support for Multiple Properties

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#89]
Add filtering using multiple properties in Angular 2. This feature should be reusable and, as such, a part of the Shared Feature Module (see #116).

## Reference
- [JIRA User Story](https://issues.jboss.org/browse/IPAAS-145)
- [Connections: Connection Library](https://github.com/hawtio/hawtio-ipaas/issues/42)

### InVision Designs:
- [Connection Library](https://redhat.invisionapp.com/share/ZQ9OF7V5Y)

**Comment by kahboom** [comment]
This will be part of the Shared Feature Module (see #116). Sorting is already supported; filtering still needs to be completed, so I will update this issue to reflect that.

**Comment by gashcrumb** [comment]
This is halfway done, the filters there but it only supports filtering on one property.

**Comment by gashcrumb** [comment]
We kinda get this now via the patternfly toolbar component.
