### ISSUE TITLE
Selectable element for `In Progress` status

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#897]
All other status messages are wrapped with span element, but `In Progress` by its nature is a bit different. Ideally I'd like to add some wrapper text status to be distinctively selectable. Any ideas @jludvice @gashcrumb @kahboom?

Something like `<div class="status">` would be probably sufficient to wrap around those divs? 

```html
<span _ngcontent-c9="" class="label label-inactive">
          Inactive
</span>
```

```
<div _ngcontent-c9="">
        <div _ngcontent-c9="" class="spinner spinner-sm spinner-inline"></div>
        In Progress
</div>
```

**Comment by gashcrumb** [comment]
Absolutely, if required the wrapper div could also have a class that reflects the status if it helps.

**Comment by dsimansk** [comment]
Hi @gashcrumb, sorry for the late response. Sorry for the late response, I've found(with @lvydra hint) that this implementation that access top level `div[class=syndesis-integration-status]` is currently sufficient for us. As your PR is already prepared, I'd suggest to keep also status class, might be useful later. Wdyt?

**Comment by gashcrumb** [comment]
yeah, fine by me!
