### ISSUE TITLE
Clicking the browser Back button during the create integration flow and I got this...

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ui#910]
Accidentally clicked the browser back button during the create integration flow and I saw this...

Wondered if we should explicitly say that clicking on the Back button may cause some issues...and users should use the Cancel button to get back to the integration flow.  

Any suggestions for this? 

![image](https://user-images.githubusercontent.com/24943812/30169901-9f45f2c2-93bb-11e7-9749-8def03327418.png)

**Comment by gashcrumb** [comment]
Nah, that's just a bug, the back button should kinda work, or the app should deal with it.
