### ISSUE TITLE
A thin line is striking through the scroll bar area

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ui#913]
This is probably nitpicking, but it kind of looks weird with the line getting through the scroll bar area. See screenshot below. 

![image](https://user-images.githubusercontent.com/24943812/30177987-7cd12968-93d5-11e7-9dab-cc3e8d71296d.png)

**Comment by astefanutti** [comment]
Should hopefully be addressed with the work from #867.
