### ISSUE TITLE
[Naming an Integration] Breadcrumb has white background color and it's overlapping the left pane scroll bar

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ui#914]
I'm viewing this on a laptop size screen and noticing the following...

- Breadcrumb background color should be gray to ensure consistency. 
- Breadcrumb should not cover part of the scroll bar of the left visualization pane area. 

Is this a responsiveness issue? 

![image](https://user-images.githubusercontent.com/24943812/30178602-87b6b85a-93d7-11e7-869d-ac38409bfdc0.png)

**Comment by gashcrumb** [comment]
Note you can get to this page by clearing the integration name at the top-left and then clicking 'save', it's really a stopgap to ensure the user names the integration before we allow saving it.

**Comment by dongniwang** [comment]
Encountered the same issue again when I was adding a third connection to the integration. But this time is the filter toolbar covering the scroll bar. 

![image](https://user-images.githubusercontent.com/24943812/30182886-6578a2c6-93e6-11e7-82a2-5b92a22ba3ff.png)

**Comment by astefanutti** [comment]
Should hopefully be addressed with the work from #867.

**Comment by astefanutti** [comment]
Should be fixed with #925.
