### ISSUE TITLE
Mysterious GET to https://localhost:4200/null showing up in network tab

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#916]
Not sure where this is coming from but we should track this down:

![capture](https://user-images.githubusercontent.com/351660/30214087-2cc86770-9479-11e7-880c-413d1aacea1a.PNG)

**Comment by zregvart** [comment]
You might be aware of this, but it might help if not. There should be an _Initiator_ column in the specific requests row. Also you can track dependencies between requests, see https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#initiators-dependencies.

**Comment by gashcrumb** [comment]
Yep, good call, on the surface it looks like it's coming from angular, but noticed one line amidst all the other frames referencing:

https://github.com/syndesisio/syndesis-ui/blob/master/src/app/app.component.html#L38

So might be worth guarding these img tags with an *ngIf perhaps.
