### ISSUE TITLE
Change text on the Add a Step page to be more informative

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/syndesis-ui#920]
To be consistent with headings in other pages, "step" should have an initial cap: "Add a Step". 

Can you replace "Choose a step from below" with:
A step specifies an operation on the data in the integration. Click one to add it.

**Comment by dongniwang** [comment]
Adding a screenshot to help clarify which page that we're talking about. 

![image](https://user-images.githubusercontent.com/24943812/30380211-fd6059b0-9866-11e7-89e4-2c9f118b2ca9.png)
