### ISSUE TITLE
Top bar is missing Syndesis logo

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#924]
![screen shot 2017-09-11 at 10 36 36](https://user-images.githubusercontent.com/5637792/30265719-4e72eaec-96dd-11e7-9cb9-e8adc8644ec6.png)

**Comment by dsimansk** [comment]
@gashcrumb probably caused by https://github.com/syndesisio/syndesis-ui/commit/10091c943ebaa37e5407e9f6dbfb12a3dbe541d0. Is there a file missing in the commit?

**Comment by gashcrumb** [comment]
No, honestly not sure what that was supposed to be referencing.  In any case we'll need to work on that logo for productization, have created a separate issue to track that and will open a PR to put the logo back into place for now.
