### ISSUE TITLE
Data Mapper not present in steps list

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#926]
When loading available stes for integrations, there're 500 errors present for the following request URL. There's no request payload and the error response

```
https://<syndesis-ui-url>/api/v1/connections/1/actions/io.syndesis:twitter-mention-connector:latest
```

```
developerMsg: "Internal Server Exception. HTTP 500 Internal Server Error"
errorCode: 500
userMsg: "Please contact the administrator and file a bug report"
```

**Comment by gashcrumb** [comment]
So there's 2 issues you're reporting in one :-)

In any case there's some mismatch currently, the data mapper step is only available if the source and target connections have output and input data shapes respectively, and many of the example integrations and connections are missing this.  And also we likely have to adapt where the code is looking for these data shapes.

Also the HTTP 500 is from us starting to implement dynamic properties, nothing to see there, though maybe @zregvart might be interested in that error :-)

**Comment by dsimansk** [comment]
So the test uses Twitter Mention -> SF Create/Update contact. They both should have dataShapes in place.

![download](https://user-images.githubusercontent.com/5637792/30314287-91e604a8-97a0-11e7-815c-7dcb9cb8a55e.png)

**Comment by zregvart** [comment]
@dsimansk could it be that the `syndesis-db` pod was restarted at that time, in the logs the only errors I can find are `org.postgresql.util.PSQLException: ERROR: relation "jsondb" does not exist`

**Comment by dsimansk** [comment]
@zregvart you're right, the 500 error code was probably caused by inconsistent db data. And I've merged 2 unrelated issues into 1 by mistake :)

But to the OP I still can't get Data Mapper to load for above mentioned integration.

**Comment by zregvart** [comment]
@dsimansk @gashcrumb do you think it's a good idea to add data shapes to integrations on the backend? I could go through `deployment.json` and check for data shapes. We'll need to revisit `deployment.json` with the new connectors anyhow. Would that fix this?

**Comment by gashcrumb** [comment]
I think it would, yep, filling in those blanks would be awesome!

On Sep 12, 2017 4:57 AM, "Zoran Regvart" <notifications@github.com> wrote:

@dsimansk <https://github.com/dsimansk> @gashcrumb
<https://github.com/gashcrumb> do you think it's a good idea to add data
shapes to integrations on the backend? I could go through deployment.json
and check for data shapes. We'll need to revisit deployment.json with the
new connectors anyhow. Would that fix this?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/syndesisio/syndesis-ui/issues/926#issuecomment-328788847>,
or mute the thread

**Comment by zregvart** [comment]
created syndesisio/syndesis-rest#589

**Comment by akieling** [comment]
@gashcrumb what needs to be done in the UI to fix this issue?

**Comment by gashcrumb** [comment]
@akieling Nothing as far as I know so far, this is currently a backend/data issue.

**Comment by zregvart** [comment]
I'm trying to debug this, but as it seems that the previous and subsequent step's action don't get updated with output/input data shapes from the dynamic metadata thinggy.
