### ISSUE TITLE
Make top bar logo, icon and title easily overridden

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#927]
Currently there's no icon it looks like, in any case it should be possible to override the top nav bar's logo and icon either via configuration or as part of building the image so that the console can be productized properly.

**Comment by gashcrumb** [comment]
@sjcox-rh @dongniwang lemme know if we have a logotype or icon to use for this.

**Comment by kahboom** [comment]
This would also be good for documentation text like the guided tour, since there may be references to Syndesis throughout that will need to be easily swapped out.

**Comment by gashcrumb** [comment]
@kahboom after I get a PR in for this you can inject the `ConfigService` and use `configService.getSettings('branding', 'appName');`

@sjcox-rh @dongniwang also need a branded favicon if it needs to be different than the glasses icon which is what's currently being used.

**Comment by gashcrumb** [comment]
Let's keep this open until we have the product icons

**Comment by kahboom** [comment]
Thanks @gashcrumb !

**Comment by dongniwang** [comment]
I know SJ is working on the logo, and will probably send it out some time today. Not sure about the favicon part...

**Comment by gashcrumb** [comment]
With the latest PR and the right config.json settings:

![capture](https://user-images.githubusercontent.com/351660/30712857-6be8d266-9edb-11e7-88a9-28011580a26a.PNG)

**Comment by gashcrumb** [comment]
Think this is all set now, we can open new issues for changes
