### ISSUE TITLE
Set up CD for E2E Tests

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#93]
Create a staging environment using CD for the E2E tests that, using GitHub hooks, spin up a Selenium server and, subsequently, run Protractor tests with each push to master for both the `redhat-ipaas/ipaas-client` and `redhat-ipaas/ipaas-client-java` GitHub repositories (so, run the tests for each repository update, irrespective of one another). The staging environment should be on our dedicated OpenShift.

This has already been done for each of the repositories themselves.

**Comment by kahboom** [comment]
Assigning to @dsimansk for now, but whoever gets to it first can change this ;D.

**Comment by dsimansk** [comment]
There's a [small blocker](https://github.com/jludvice/ipaas-ui/commit/36b00cdd662968067952c0a4298ea918a867f12e#commitcomment-21186396), but it seems that solution is near.

**Comment by kahboom** [comment]
@dsimansk @jludvice @iocanel - How is this looking?

**Comment by jludvice** [comment]
Here is my expectations on build pipeline.

I expect that following things will happen in the pipeline/jenkins job - before e2e tests are started
* **deploy ipaas into test openshift** (ipaas-ui, ipaas-rest, keycloak, ...?)
    * build the ipaas-ui from current sources (current PR for instance)
    * this will be time consuming because it will build docker containers and launch pods
* install required tools - browser + xwindow or xvfb (maybe we can have docker image with required tools pre-build?)
* provide GitHub login credentials 
   * either expose as shell variables
   * or inject some config file with jenkins
* provide url to ipaas ui
* launch e2e tests (they will open browser on ipaas-ui deployed in openshift)
* archive cucumber html report
* clean up

Test execution will be the same on developers laptop and in the pipeline.
Tests won't contain any code related to infrastructure/automation.

**Comment by jludvice** [comment]
refactor protractor conf to support multiple envs - #332
