### ISSUE TITLE
yarn v1.x.x breaks dependency installation

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-ui#934]
Was sorting out an issue this morning with the help of @astefanutti . Discovered that the next major version of Yarn, 1.x.x, breaks everything when you try to run dependencies. To reproduce, assuming you are on OS X and using Homebrew, from the project root dir:

1. `brew upgrade yarn`
2. `rm -rf node_modules`
3. `yarn cache clean`
4. `yarn install`

You get the following:

```
webpack: Compiling...
Hash: 6e56c4c994d500a5265c                                                         
Time: 3594ms
chunk    {0} styles.bundle.js, styles.bundle.js.map (styles) 644 kB {5} [initial] [rendered]
chunk    {1} scripts.bundle.js, scripts.bundle.js.map (scripts) 912 kB {5} [initial]
chunk    {2} main.bundle.js, main.bundle.js.map (main) 40 bytes {4} [initial]
chunk    {3} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 28 bytes {5} [initial]
chunk    {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 302 kB [initial] [rendered]
chunk    {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry]

ERROR in multi webpack-dev-server/client?https://localhost:4200 ./src/main.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in '~/Projects/syndesis-ui'
 @ multi webpack-dev-server/client?https://localhost:4200 ./src/main.ts

ERROR in multi ./src/polyfills.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in '~/Projects/syndesis-ui'
 @ multi ./src/polyfills.ts
webpack: Failed to compile.
```

Screenshot:

<img width="736" alt="screenshot 2017-09-12 13 52 06" src="https://user-images.githubusercontent.com/3844502/30327998-f94b6046-97c5-11e7-8a72-d2e11152eb4c.png">

Interestingly enough, `yarn` seems to work, but `yarn install` results in a 503 unexpected error:

<img width="839" alt="screenshot 2017-09-12 14 12 30" src="https://user-images.githubusercontent.com/3844502/30327982-edee4510-97c5-11e7-9b71-af2e7b5a58f3.png">
<img width="840" alt="screenshot 2017-09-12 14 17 16" src="https://user-images.githubusercontent.com/3844502/30327985-ef6abc34-97c5-11e7-8719-5a6d037a7abf.png">

**Comment by astefanutti** [comment]
Thanks a lot to @kahboom for testing it before everyone else so that we won't have to waste all our time on that 😄!

**Comment by gashcrumb** [comment]
Have we tracked down actual issues in the yarn repo or reported these problems?  Would be good to link them to this issue for tracking purposes.

**Comment by kahboom** [comment]
Btw an easy way to downgrade if you're using Homebrew:

- `brew info yarn` - See that the Yarn version currently being used has an asterisk next to it, you likely still have the older `0.27.5` (or whichever) still installed as well.
- `brew switch yarn 0.27.5`
- `brew info yarn` - Check that the asterisk is now next to the older version.
