### ISSUE TITLE
Create help icon in UI with link to iPaaS product documentation

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ui#936]
@dongniwang commented on [Wed Aug 09 2017](https://github.com/syndesisio/syndesis-ux/issues/31)

@fbolton commented on [Mon Mar 13 2017](https://github.com/syndesisio/syndesis-ui/issues/243)

This is a suggestion that comes from Nacia Owens, as low-cost way of integrating the iPaaS docs (created by the Fuse documentation team) with the UI:

> here's an idea that might be quick to implement: can you include a simple, clickable help icon (?) in the banner that would take the user to the iPaaS document on the portal? If Fintan provides the URL for the page where the iPaaS doc will be published, it might be possible to implement this link as a first step towards providing help in the UI?

---

@naciao commented on [Tue Mar 21 2017](https://github.com/syndesisio/syndesis-ui/issues/243#issuecomment-288127123)

Revising the timeline for this item: the documentation target for the linked help icon will be delivered for the technology preview, not for the demo.

---

@naciao commented on [Tue May 16 2017](https://github.com/syndesisio/syndesis-ui/issues/243#issuecomment-301849832)

Suggest that we promote this up and out of the backlog, perhaps re-evaluate what kind of embedded help would be most useful to the citizen integrator, and plan to provide some help in the UI for the technology preview.

---

@dongniwang commented on [Wed Aug 09 2017](https://github.com/syndesisio/syndesis-ui/issues/243#issuecomment-321364827)

@gashcrumb @kahboom Any objections of me moving this to the ux repo? If possible, let's target this for sprint 16? 

cc: @sjcox-rh 

---

@gashcrumb commented on [Wed Aug 09 2017](https://github.com/syndesisio/syndesis-ui/issues/243#issuecomment-321366877)

+1 go for it!

---

@naciao commented on [Thu Aug 10 2017](https://github.com/syndesisio/syndesis-ux/issues/31#issuecomment-321541242)

Thanks for moving this into sprint 16. Let me know when you need the doc URL, I will coordinate with Fintan on his Fuse doc Jira that tracks this (https://issues.jboss.org/browse/FUSEDOC-2121).

---

@dongniwang commented on [Fri Aug 25 2017](https://github.com/syndesisio/syndesis-ux/issues/31#issuecomment-324932472)

The help icon is added as part of the First Time User Experience design, see https://github.com/syndesisio/syndesis-ux/issues/30. 

Implementation of the help icon can be found here http://www.patternfly.org/pattern-library/application-framework/masthead/

cc: @sjcox-rh @naciao @gashcrumb @kahboom 

---

@fbolton commented on [Tue Sep 12 2017](https://github.com/syndesisio/syndesis-ux/issues/31#issuecomment-328794257)

For the TP1 sample tutorial(s), you can use either of the following URLs for the help icon (depending on whether you prefer single-page HTML or multi-page HTML):

Single-page HTML:
https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/6.3/html-single/fuse_ignite_sample_integration_tutorial/

Multi-page HTML:
https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/6.3/html/fuse_ignite_sample_integration_tutorial/

Currently, there is a dummy doc at this location (so that you can verify the URL). At TP1 release time, this will be replaced by the content that @TovaCohen and @nichmoore are developing.

**Comment by fbolton** [comment]
Caution, @dongniwang @gashcrumb @kahboom ! We are not ready to use those placeholder URLs yet. I just got from feedback from @naciao that the TP1 doc ought to be categorized under Fuse 7.0 (not Fuse 6.3, as in the first draft). Most likely, the version number in the URLs will change from 6.3 to 7.0. I'll get back to you when I've confirmed this.

**Comment by fbolton** [comment]
The version of the placeholder URLs has now changed to 7.0-TP. @dongniwang @gashcrumb @kahboom, the following URLs have been blessed by @kcbabo, so you can now go ahead and use either of them for the Help Icon:

Single-page HTML:
https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html-single/fuse_ignite_sample_integration_tutorial/

Multi-page HTML:
https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/7.0-tp/html/fuse_ignite_sample_integration_tutorial/

**Comment by kahboom** [comment]
Thank you @fbolton! I can work on this.

**Comment by dongniwang** [comment]
See screenshot below for help icon reference. 

I think we can keep the caret. 
- **Documentation**: link goes to the Single-page HTML URL that @fbolton provided. 
- **Contact Us**: do we have a generic email address for people who want to ask question/provide feedback? This is a question for @kcbabo 
- **About** : It should display an [About Modal ](http://www.patternfly.org/pattern-library/communication/about-modal/). Not sure what content we have for this about modal. Another question for @kcbabo 

If that's too much to work on before Friday. I'm fine with only having the Documentation link and just style the Contact Us and About as not clickable. 

cc: @sjcox-rh @kahboom 

![image](https://user-images.githubusercontent.com/24943812/30657554-f9970546-9e05-11e7-9420-8bb7fd62900a.png)

**Comment by naciao** [comment]
Thanks, Dongni. It would be great to have all three helpful items on this pulldown menu, but I really feel that the link to Documentation is essential for the TP1 users. to be successful.

**Comment by aileenc** [comment]
Contact Us should direct to fuse-ignite-tech-preview@redhat.com

**Comment by kahboom** [comment]
Also, the Contact Us should probably lead to a contact form, but we can just leave email for now.

**Comment by kahboom** [comment]
Once we have the content for the About modal, please let me know ASAP.

**Comment by aileenc** [comment]
We can leave out About Modal for now as we're running out of time for TP1.
Most important thing is to have the doc link in there.

**Comment by kahboom** [comment]
@aileenc Thanks. Just FYI, the About is already set up, so we can add it in whenever we do get the content and just copy and paste it, but we can of course postpone it for post-TP1.
