### ISSUE TITLE
Having "Done" button before the integration is ready to be published is misleading...

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ui#939]
Don't remember if we have decided to have a "Done" button here. But it could be misleading since the integration is not ready to be published yet. Even if users don't add a step/connection, they still need to name the integration. 

Can we change the "Done" to "Next" here? 

cc: @sjcox-rh 

![image](https://user-images.githubusercontent.com/24943812/30342771-fcadfc46-97c8-11e7-9b82-3ab106e831b2.png)

**Comment by dongniwang** [comment]
Really hard to notice the **Done** on this page as it only displays less than 1s. But we can probably get rid of the Done as well. 

![image](https://user-images.githubusercontent.com/24943812/30342960-aba70dbe-97c9-11e7-8c52-dd0811b9788a.png)

**Comment by gashcrumb** [comment]
It's 'Done' as in done configuring the step.  It used to always be 'Next' but that was confusing too, there's previous issues where it was decided to have 'Done' instead of 'Next' once we're out of effectively a wizard-style flow of pages.  

Also note that on these particular screens there's now at least the potential to have more than 1 page of configuration, i.e. for salesforce eventually page 1 will be picking the target object and page 2 will be what field to use as the unique identifier, in this case page 1 would have 'Next' and page 2 would actually have 'Previous' and 'Done'.

Also in general for these pages, the top-right is the worst place to have the action buttons, feels more like they should be underneath the form :-)

**Comment by gashcrumb** [comment]
Also the twitter mention action complicates things, as there's no config for it, but we don't technically know that in the UI until we fetch the form data from the backend.  It didn't look or feel right for the page to immediately punt the user to the save or add step page so I added the message that + a delay, also given that we fetch the form data on the fly, there's a chance that an error could occur which will also show up on this page via an alert.

**Comment by dongniwang** [comment]
I see. Both Done and Next are confusing because of the placement. It's out of context since it aligns with the breadcrumb, and some of the buttons are for controlling only a sub-section of the entire integration workflow. To me, the breadcrumb is a more high-level control. 

Ahhh, the buttons. It's on my list of to-do items to figure out these buttons...and the buttons used to be at the bottom of the page. Then we decided to move it to the top so it's consistent with Data Mapper.

**Comment by dongniwang** [comment]
> Also the twitter mention action complicates things, as there's no config for it, but we don't technically know that in the UI until we fetch the form data from the backend. It didn't look or feel right for the page to immediately punt the user to the save or add step page so I added the message that + a delay, also given that we fetch the form data on the fly, there's a chance that an error could occur which will also show up on this page via an alert.

Agreed. I understand adding the message. What happen if there's actually an error? Do users need to perform anything on that page then?

**Comment by gashcrumb** [comment]
> Agreed. I understand adding the message. What happen if there's actually an error? Do users need to perform anything on that page then?

Contact support I guess :-)  This would be more of a system issue I think.

It probably wouldn't be that hard to move those buttons so they're under the form, want me to give that a go?

**Comment by dongniwang** [comment]
> Contact support I guess :-) This would be more of a system issue I think.

Would it be possible to use a loading screen here? So we don't need a Done button. And with the loading screen we can still display success/error messages. 

As for the buttons, here's what I'm proposing: 

1. Move breadcrumb to the top of page right below the masthead. 
2. For buttons 
    - Only integration related buttons will be placed on the same line of breadcrumb. 
    - Buttons for step configuration or action configuration will be using the buttons on forms style (below the interaction area). 

cc: @sjcox-rh 

![image](https://user-images.githubusercontent.com/24943812/30345818-9b062764-97d4-11e7-94db-923d06fcea14.png)

**Comment by gashcrumb** [comment]
We should create a separate issue for the breadcrumbs, I think that's actually a big change to implement.  

Let's track moving the page-specific buttons like these in this issue however.

**Comment by dongniwang** [comment]
Agreed it's a big impact item. We probably need a UXD issue first for the breadcrumb? Maybe to create a PR so it gets to the repo with history of decisions. 

Then for the page-specific buttons, do we need to go through all the pages to identify potential changes?

**Comment by gashcrumb** [comment]
For the breadcrumbs yes, it's worthwhile, also it'd be good to try and make them consistent across the app.

In regards to the buttons so far for this case I think it's needed on the action configuration page (this one) and the step configuration page *except* for the data mapper.

The save or add step should be fine as those buttons are for saving the integration.  The connection, step and action select pages don't have buttons.

**Comment by astefanutti** [comment]
While I'm at it, I'd be happy to refactor the breadcrumb. Let me know when the design has stabilised.
