### ISSUE TITLE
Use present enum values for action properties

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-ui#949]
We have added `enum` property to action definition properties, it could be defined statically within `deployment.json` or it can appear filled dynamically, for instance if the values depend on another action property.

Currently we have a input box, this could be a combo box offering those values.

`enum` is an array containing `value` and `label` properties, `label` is displayed to the user, `value` is the value that needs to be set in `configuredProperties`.

For example on this screen:

![screenshot from 2017-09-14 14-16-21](https://user-images.githubusercontent.com/1306050/30429342-62553552-9957-11e7-96c6-1b84c23ca01d.png)

This is a simplified JSON containing the `enum` property:

```json
{
      "propertyDefinitionSteps":[
         {
            "description":"Specify the Salesforce object name",
            "name":"Object name",
            "properties":{
               "sObjectName":{
                  "enum":[
                     {
                        "label":"Contact",
                        "value":"Contact"
                     },...
                  ]
               }
            }
         }
      ]
   }
```

See  #868

**Comment by zregvart** [comment]
@akieling would you mind taking a look at this?

**Comment by gashcrumb** [comment]
Should actually be doing this -> https://github.com/syndesisio/syndesis-ux/blob/master/designs/salesforceobjects/salesforceobjects.md#choose-object

Question is do we do this for all enum values or maybe have a specific type so the form service knows to insert this as a custom control, I personally vote for the latter.

**Comment by gashcrumb** [comment]
If you want to do typeahead as a first pass you can just add a 'list' attribute with an array of strings, like:

https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.model.ts#L51

`paths` in this case is passed into that function.  It might be good for the forms service to kinda do this whenever the 'enum' property is present anyways, as then it behaves like an input/combobox hybrid.

**Comment by gashcrumb** [comment]
hmm, we've no object description in that enum, so that page in the design where you pick the object is gonna look real blank :-)

I still vote for typeahead or combobox for starters :-)

**Comment by zregvart** [comment]
Created https://github.com/syndesisio/syndesis-rest/issues/596

**Comment by gashcrumb** [comment]
@zregvart when you fetch the objects from salesforce is there a `description` field?  It'd be cool if that could also be passed along in the `enum` attribute.

**Comment by zregvart** [comment]
@gashcrumb enums items should contain `label` and `value` is that OK, or we need another field?

**Comment by gashcrumb** [comment]
I guess it depends on if we feel like we can implement the design as-is by the end of the sprint.  If not then we stick with a typeahead and leave that design for later.  If so then we'll definitely need a `description` field on the enum too.  And we'll need to decide how the object selector should be shown, i.e. should the `type` field be something other than text/string, or should there be some other attribute that the UI can use to know if it should use that design.

**Comment by akieling** [comment]
It would be great if we could define those things before doing any work. We need to map configuration to form fields. In the current case, the design uses a table view, which is a complex UI component. If we want to deliver something quickly, it might be better to use a combobox or select. Mapping different types to different form fields sounds like a good strategy. Alternatively, we could also inspect the `enum` field.

**Comment by zregvart** [comment]
I kinda think we should rethink the UX design. For Salesforce objects description is not given via the API. Stored procedures could have comments on them but depending on the database its applicability can vary.

**Comment by gashcrumb** [comment]
Yep, why don't we for now just set the `list` property on the input field in the form service with the enum values, which will at least let the user pick other objects and we can revisit the UX design later.

**Comment by akieling** [comment]
#955 closes this issue. @dongniwang let's review the UX later, OK?
