### ISSUE TITLE
[Enhancement][Datamapper] Set search field active after clicking on search icon

### ISSUE THREAD

**Issue by apupier** [syndesisio/syndesis-ui#962]
it would be convenient to  set the search field active after clicking on search icon automatically, it will avoid to have another click to start typing which will be the next action planned as a user after i clicked on search

see 0'40" of https://drive.google.com/file/d/0B_udTBpEdqO8UFJSblY2YUNyTU0/view

**Comment by gashcrumb** [comment]
Let's track this here -> https://github.com/atlasmap/atlasmap-ui/issues/82
