### ISSUE TITLE
Need SQL stored procedure icon

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#972]
![capture](https://user-images.githubusercontent.com/351660/30546275-2f8b0074-9c5a-11e7-8e46-1feffa5a2cfa.PNG)

And it should go into `/src/assets/icons/sql-stored.connection.png`

@sjcox-rh @dongniwang do you guys know if we have one handy?

**Comment by dongniwang** [comment]
I have no idea...this is a question for SJ then...

**Comment by sjcox-rh** [comment]
@gashcrumb Here is the icon for SQL. I've uploaded png. Let me know if this works for ya, thanks! If not I can email you an svg. Thanks!

![ipaas_connectionicons_sql](https://user-images.githubusercontent.com/16257540/30557553-884092f2-9c63-11e7-9744-096bdab93d15.png)

**Comment by gashcrumb** [comment]
LOL, is that big enough do you think?  Lemme give it a try and see how it looks..

**Comment by kahboom** [comment]
ROFL
