### ISSUE TITLE
Data mapper integration side panel looks different from the one in the creation flow 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ui#973]
Other than the background color is different (white vs. gray), part of the integration side panel in the data mapper is covered by the scroll bar. Also, hovering on connections and steps icon in the data mapper side panel shows no tooltips. 

Would it be helpful if we add tooltips to the connections and steps? I know we have that on the integration details page.  

cc: @sjcox-rh 

![image](https://user-images.githubusercontent.com/24943812/30547094-5d915cfa-9c5c-11e7-9fdb-8179c12c9ebc.png)

![image](https://user-images.githubusercontent.com/24943812/30547288-db4fe7e2-9c5c-11e7-84ea-ee83b1f4c895.png)

**Comment by gashcrumb** [comment]
I thought the background was grey in the design, i.e. it's supposed to be a cut-down version of that view so the data mapper has more space.

+1 to having tooltips and yes, it should be adjusted to look ok when a scrollbar is present, especially on Windows which has a wider scrollbar.

**Comment by dongniwang** [comment]
Hmm...I honestly don't remember if it's supposed to be white or gray :( The background color is less important here. You're right, it's supposed to be a cut-down version. Only found this design on InVision (which has a black background color): 
https://redhat.invisionapp.com/share/VQ8UZ7PCE#/225286606_IPaaS_DataMapper_Transformations_2-24-17-pdf_3

If it's not too hard to add the tooltips, that would be great!

**Comment by sjcox-rh** [comment]
Yeah the designs that @dongniwang sent were the latest (back from Feb though) for the stripped down integration visualization on data mapper. It was supposed to be the darker background to differentiate it from the rest of the content on the page but like Dongni said, not super important at this time if it's too time consuming of a change, @gashcrumb 

+1 on tooltips!

**Comment by gashcrumb** [comment]
We should at least try and ensure there's no horizontal scroll bar for starters, @astefanutti any chance you could have a look at this one?

**Comment by astefanutti** [comment]
@gashcrumb sure, let me have a look at it. Just that on Mac it displays better so hopefully I'll be able to fix it for Windows as well.

**Comment by astefanutti** [comment]
Should be fixed (scrollbar, background color) with #1012. I've just created #1013 to follow-up on the tooltips.
