### ISSUE TITLE
Make filter toolbars look the same in create integration flow

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ui#975]
This is probably an unfortunate oversight during the earlier design phase. After discussing this with @sjcox-rh, we think it's better to make it look the same to ensure consistency throughout the workflow. 

The filter toolbar in the second screenshot should look the same as the one in the first screenshot. 

![image](https://user-images.githubusercontent.com/24943812/30558320-023b59f0-9c7f-11e7-8d07-38933a666eba.png)

![image](https://user-images.githubusercontent.com/24943812/30558326-06683c46-9c7f-11e7-815e-1da654c189bb.png)

**Comment by sjcox-rh** [comment]
Thanks for creating this issue @dongniwang!  Yeah sorry we didn't catch this sooner in our designs. We just want to make sure that the filter tool is consistent throughout the whole app, no need to appear different on different steps/actions.
