### ISSUE TITLE
Make sure empty states are up-to-date based on FTUE designs

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-ui#978]
Here is a list of empty states that users could encounter during their first use of the application. Please double check and make sure empty states in the application are up-to-date based on these designs. 

![connection page empty state](https://user-images.githubusercontent.com/24943812/30600937-ae36a034-9d2e-11e7-8298-41a7ae4e5b58.png)
![dashboard empty state](https://user-images.githubusercontent.com/24943812/30600938-ae38c67a-9d2e-11e7-8387-935a1861fe12.png)
![integration list page empty state](https://user-images.githubusercontent.com/24943812/30600939-ae3d2706-9d2e-11e7-8365-84cbcaa9be20.png)
![create connection empty state](https://user-images.githubusercontent.com/24943812/30600949-b442e8e8-9d2e-11e7-81e1-baceb9a0bc47.png)
![create integration empty state](https://user-images.githubusercontent.com/24943812/30600941-b1058848-9d2e-11e7-88e6-065e6a5fbd59.png)

**Comment by gashcrumb** [comment]
@dongniwang is there a dashboard/home page one too?

**Comment by dongniwang** [comment]
> is there a dashboard/home page one too?

@gashcrumb 
https://user-images.githubusercontent.com/24943812/30600938-ae38c67a-9d2e-11e7-8387-935a1861fe12.png
