### ISSUE TITLE
FTUE - distinctive GH's callback URL

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-ui#982]
Proposed by @jludvice on our meeting today. 

In a section `Register Syndesis` we could display callback URL (with a copy-to-clipboard button) that is clearly recognizable and can be copied over to GH's registration form.

@dongniwang @kahboom wdyt?

![screen shot 2017-09-20 at 14 09 08](https://user-images.githubusercontent.com/5637792/30643029-a5c4c6da-9e0d-11e7-9462-c735ef081269.png)

**Comment by dongniwang** [comment]
Yes, that would be great! 

This is the form users will be filling out. I see "Homepage URL" and "Authorization callback URL", can we also provide Homepage URL?

![image](https://user-images.githubusercontent.com/24943812/30648777-d682f920-9dec-11e7-906f-a980abfab733.png)

**Comment by dsimansk** [comment]
Homepage and callback URLs can be the same in our case.

**Comment by kahboom** [comment]
@jimmidyson Depending on who this is easier for and what we are working on at the moment, one of us can probably take this. Let's stay in sync with what parts of the app you're working on so we don't get a ton of merge conflicts. 👍

**Comment by jimmidyson** [comment]
@kahboom As discussed, I'm going to back off the UI updates as I've become an angular2 n00b once more through lack of exposure... Let me know if you need me to try to pick anything up though, I really don't mind if needed.
