### ISSUE TITLE
Wrong autocomplete fields in filter when being after datamapper

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#983]
It looks like that the wrong datashape is sent for fetching the autocomplete fields when the filter comes after a datamapping step which changes the outputShape. It still uses the autocomplete fields from the incoming and starting connection.

Not sure whether this can be easily done (and whether the datamapper carries an outputShape at all). But what could be done, too, is to check whether there is a datamapper step before the filter step and then use the the _inputShape_ of the next connection coming after the filter step.

**Comment by gashcrumb** [comment]
Yeah, currently datamapper steps don't contain data shapes at all, but I can definitely do the latter option easily enough I think.
