### ISSUE TITLE
Cannot read property 'initCfg' of undefined

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-ui#990]
So here I just created a quick oracle EBS to twitter integration and then added a data mapper step.  The data mapper fails to load with the below error:

![capture](https://user-images.githubusercontent.com/351660/30658885-2df92ee6-9e0a-11e7-96bd-dd1dec37ae82.PNG)

@akieling @igarashitm FYI...

**Comment by igarashitm** [comment]
So in some reason target document is not there. At least NPE here doesn't look good, it should raise a readable error, like target document is not found or like that. And there may be a inspection error for the target document before hit this?

**Comment by gashcrumb** [comment]
Turns out the code skips adding any data shape if 'type' isn't specified, which isn't used for non-java types.

**Comment by akieling** [comment]
@gashcrumb @igarashitm I'm still getting this error. Are you?

**Comment by gashcrumb** [comment]
Lemme double check but I wasn't getting it after that PR
