### ISSUE TITLE
"Registration Successful" --> "Registration successful"

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#996]
![image](https://user-images.githubusercontent.com/99080/30682659-b86747b6-9eaa-11e7-96c9-abd4fdff07cc.png)

**Comment by gashcrumb** [comment]
I vaguely remember the design having them both capitalized...

**Comment by rhuss** [comment]
ah, ok. just thought this was a typo. Feel free to close if this is intended.

**Comment by dongniwang** [comment]
Should be "Registration successful!"...sorry if the design has both words capitalized. 

http://www.patternfly.org/pattern-library/communication/inline-notifications/
