### ISSUE TITLE
Tag for connection has differ UI than tags for integrations

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis-ui#997]
When defining a connection:

![image](https://user-images.githubusercontent.com/99080/30685313-c879ffd6-9eb4-11e7-8535-5ab3c69d2d41.png)

but this seems to be a plain text field. I wonder whether we are using tags at all for connections ? Maybe just disable this input for the moment ?

**Comment by rhuss** [comment]
Interestingly, the tags entered here are completely ignored. When I create such a connection and then go to "Edit connection" this looks like:

![image](https://user-images.githubusercontent.com/99080/30685585-b120ece0-9eb5-11e7-8eda-239baf9673ff.png)

So it seems, an implicit tag "Twitter" (base on the type of the connection I guess) has been created, but my manually added tags have been ignored.

**Comment by gashcrumb** [comment]
Hmm, it should have appended the connector ID to your entered in tags.  And yeah, the tag input itself doesn't look like I'd expect, we were using a custom widget for that one.

**Comment by akieling** [comment]
@rhuss did you hit enter after typing each tag?

**Comment by rhuss** [comment]
no, I just used "," as I was used to it. But you are right, one needs to hit enter. (its about different then I'm used to it, where entering ',' or TAB will mark the tag.

The tags are then taken over, too (but not for non-completed tags which one has not confirmed with enter).

Maybe one can change the prefilled text to: "Add tag and press ENTER" ?

**Comment by akieling** [comment]
I agree. I'll change the placeholder and ask the user to press Enter.

**Comment by akieling** [comment]
Actually, we can define other keys to separate tags, not just the Enter key.
